---
title             : "@regnerIndividualDifferencesWorking2010"
shorttitle        : "@regnerIndividualDifferencesWorking2010"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h3.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

# @eppi-centreReviewGuidelinesExtracting2003 & @criticalappraisalskillsprogrammeCASPSystematicReview2018

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [x] Not applicable (whole study is focus of data extraction)  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?

- [x] Explicitly stated (please specify)  

The study was informed by existing research on stereotype threat, working memory, and choking under pressure. The authors cite multiple studies showing that stereotype threat hinders performance by reducing working memory capacity.

### Do authors report how the study was funded?

- [x] Not stated/unclear (please specify)

The authors do not report any funding information for this study.

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

The study focuses on stereotype threat effects on women's performance in logical reasoning, and how individual differences in working memory capacity moderate these effects.

### What is/are the population focus/foci of the study?

The population focus is on male and female engineering students in France.

### What is the relevant age group? 

- [x] 21 and over  

The mean age of participants was 21 years.

### What is the sex of the population focus/foci?

- [x] Mixed sex  

The study included both male and female participants.

### What is/are the educational setting(s) of the study?

- [x] Higher education institution  

The participants were engineering students at selective engineering schools.

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)  

The study was carried out in France.

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

The study examines how stereotype threat affects women's performance on a logical reasoning task (Raven's Advanced Progressive Matrices), and how individual differences in working memory capacity moderate this effect.

### What are the study research questions and/or hypotheses?

- [x] Implicit (please specify)  

The implicit research question is whether women with high working memory capacity are more able to resist stereotype threat effects compared to women with low working memory capacity.

## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)  

The study measures:
1. Working memory capacity (using a reading span task)
2. Logical reasoning ability (using Raven's Advanced Progressive Matrices)
3. Stereotype threat condition (diagnostic vs. diagnostic but gender fair)

### Study timing

- [x] Cross-sectional  

The study collected data at a single time point.

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?

- [x] Only after  

The outcome measure (logical reasoning performance) was taken after the stereotype threat manipulation.

## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.

- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  

Participants were randomly assigned to either the "diagnostic" or "diagnostic but gender fair" condition.

### How do the groups differ?

- [x] Explicityly stated (please specify)  

The groups differ in the instructions given for the logical reasoning task. One group was told the test was "diagnostic" of logical reasoning ability, while the other group was told it was "diagnostic but gender fair".

### Number of groups

- [x] Two  

There were two experimental groups based on the stereotype threat manipulation.

### Was the assignment of participants to interventions randomised?

- [x] Random  

Participants were randomly assigned to the two experimental conditions.

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?

- [x] Not stated/unclear (please specify)  

The paper does not provide information on whether the allocation sequence was concealed.

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [ ] Yes
- [ ] No
- [x] Can't tell

The paper does not provide enough information to determine if the groups were treated equally apart from the experimental manipulation.

### Study design summary 

This was a cross-sectional experimental study with random assignment to two groups differing in stereotype threat instructions. The study examined how working memory capacity (measured pre-test) moderated the effects of stereotype threat on women's logical reasoning performance.

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 

- [x] Implicit (please specify)

The authors seem to be aiming for findings representative of high-achieving engineering students, as they selected participants from highly selective engineering schools.

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?

- [x] Explicitly stated (please specify)

The sampling frame was students in their last or second-to-last year at highly selective engineering schools in France.

### Which methods does the study use to select people or groups of people (from the sampling frame)?

- [x] Not stated/unclear (please specify)

The paper does not provide details on how specific participants were selected from the sampling frame.

### Planned sample size

- [x] Not stated/unclear (please specify)

The planned sample size is not reported.

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?

- [x] Not stated/unclear (please specify)

The paper does not provide information on recruitment methods.

### Were any incentives provided to recruit people into the study?

- [x] Not stated/unclear (please specify)

The paper does not mention any incentives for participation.

### Was consent sought?

- [x] Not stated/unclear (please specify)

The paper does not mention whether or how consent was obtained.

### Are there any other details relevant to recruitment and consent?

- [x] No

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?

- [x] Explicitly stated (please specify)

The total sample size was 117 participants (64 males, 53 females).

### What is the proportion of those selected for the study who actually participated in the study? 

- [x] Not stated/unclear (please specify)

The paper does not provide information on the response rate or proportion of selected individuals who participated.

### Which country/countries are the individuals in the actual sample from?

- [x] Explicitly stated (please specify)

The participants were from France.

### What ages are covered by the actual sample?

- [x] 21 and over

The mean age of participants was 21 years (SD = 1.54 years).

### What is the socio-economic status of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)

The paper does not provide information on the socio-economic status of participants.

### What is the ethnicity of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)

The paper does not provide information on the ethnicity of participants.

### What is known about the special educational needs of individuals within the actual sample?

- [x] Not stated/unclear (please specify)

The paper does not provide information on any special educational needs of participants.

### Is there any other useful information about the study participants?

- [x] Explicitly stated (please specify no/s.)

Participants were fourth- and fifth-year engineering students at highly selective engineering schools in France.

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 

- [x] Unclear (please specify)

Without information on the total population of engineering students or the selection process, it's unclear how representative the sample is of the intended population.

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?

- [x] Not applicable (not following samples prospectively over time)

This was a cross-sectional study, not a longitudinal one.

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [x] Not applicable (not following samples prospectively over time)

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [x] Not applicable (not following samples prospectively over time)

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [x] Details

The main types of data collected were:
(a) To define the sample: Year of study in engineering school
(b) To measure aspects of the sample: Working memory capacity (reading span task), logical reasoning ability (Raven's Advanced Progressive Matrices)

### Which methods were used to collect the data?

- [x] Psychological test

The study used a reading span task to measure working memory capacity and Raven's Advanced Progressive Matrices to measure logical reasoning ability.

### Details of data collection methods or tool(s).

- [x] Explicitly stated (please specify)

Working memory was assessed using the French version of the reading span task. Logical reasoning was assessed using Raven's Advanced Progressive Matrices, with 36 items to be completed in 30 minutes.

### Who collected the data?

- [x] Not stated/unclear

The paper does not specify who collected the data.

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?

- [x] Details

The authors do not explicitly discuss reliability, but they use established measures (reading span task and Raven's Advanced Progressive Matrices) which are known to have good psychometric properties.

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?

- [x] Details

The authors do not explicitly discuss validity, but they use established measures that are known to be valid for measuring working memory and logical reasoning.

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?

- [x] Not stated/unclear (please specify)

The paper does not provide information on whether there was concealment from those measuring outcomes.

### Where were the data collected?

- [x] Unclear/not stated (please specify)

The paper does not specify where data were collected.

### Are there other important features of data collection?

- [x] Details

No other important features of data collection are mentioned in the paper.

## Methods - Data analysis

### Which methods were used to analyse the data?

- [x] Explicitly stated (please specify)

The authors used multiple regression analysis to analyze the data.

### Which statistical methods, if any, were used in the analysis?

- [x] Details

The authors used multiple regression analysis, including tests of simple slopes for examining interaction effects.

### What rationale do the authors give for the methods of analysis for the study?

- [x] Details

The authors do not provide an explicit rationale for their choice of analysis methods.

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.

- [x] Not stated/unclear (please specify)

The paper does not explicitly state whether analysis was based on 'intention to intervene' or 'intervention received'.

### Do the authors describe any ways they have addressed the reliability of data analysis?

- [x] Details

The authors do not explicitly describe methods to address reliability of data analysis.

### Do the authors describe any ways they have addressed the validity of data analysis?

- [x] Details

The authors controlled for participants' prior performance on standard tests of math and physics in their analysis, which helps address validity.

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [x] Details

The authors controlled for participants' prior performance on standard tests of math and physics in their analysis.

### Please describe any other important features of the analysis.

- [x] Details

The authors used mean-centered working memory scores in their regression analysis.

### Please comment on any other analytic or statistical issues if relevant.

- [x] Details

No other relevant analytic or statistical issues are apparent.

## Results and Conclusions

### How are the results of the study presented?

- [x] Details

Results are presented through regression coefficients and a figure showing accuracy scores as a function of threat condition, gender, and working memory capacity.

### What are the results of the study as reported by authors?

- [x] Details

The authors found a significant three-way interaction between gender, threat condition, and working memory capacity. Low working memory women showed stereotype threat effects, performing worse in the diagnostic condition than in the gender-fair condition. High working memory women and men showed no stereotype threat effects.

### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [ ] Yes
   - [x] No
   - [ ] Can't tell

The authors report regression coefficients and p-values, but do not report confidence intervals.

### Are there any obvious shortcomings in the reporting of the data?

- [x] Yes (please specify)

The authors do not report effect sizes or confidence intervals, which would provide more information about the precision and practical significance of their findings.

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?

- [x] Yes (please specify)

The authors report on all variables mentioned in their research question: gender, stereotype threat condition, working memory capacity, and logical reasoning performance.

### Do the authors state where the full original data are stored?

- [x] No

The authors do not provide information on data storage or availability.

### What do the author(s) conclude about the findings of the study?

- [x] Details

The authors conclude that stereotype threat effects are moderated by working memory capacity, with only low working memory women showing stereotype threat effects. They suggest that this provides the first direct evidence that stereotype threat differs from choking under pressure, as high working memory individuals were able to resist stereotype threat.

## Quality of the study - Reporting 

### Is the context of the study adequately described?

- [x] Yes (please specify)

The authors provide adequate context, describing the background of stereotype threat research and the rationale for examining working memory as a moderator.

### Are the aims of the study clearly reported?

- [x] Yes (please specify)

While not explicitly stated, the aim of the study (to examine whether working memory capacity moderates stereotype threat effects) is clear from the introduction.

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?

- [x] No (please specify)

The description of the sample and recruitment process is limited. More information on the selection process and characteristics of the engineering schools would be beneficial.

### Is there an adequate description of the methods used in the study to collect data?

- [x] Yes (please specify)

The authors provide adequate descriptions of the working memory and logical reasoning tasks used to collect data.

### Is there an adequate description of the methods of data analysis?

- [x] Yes (please specify)

The authors describe their regression analysis approach, including how they examined interaction effects.

### Is the study replicable from this report?

- [x] No (please specify)

While key aspects of the method are described, lack of detail on recruitment, precise instructions, and data analysis procedures would make exact replication difficult.

### Do the authors avoid selective reporting bias?

- [x] Yes (please specify)

The authors appear to report on all variables and analyses mentioned in their research question and methods.

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?

- [x] Yes, some concerns (please specify)

The paper does not mention obtaining informed consent or ethical approval, which raises some concerns.

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [x] No (please specify)

There is no mention of student or parent involvement in the design or conduct of the study.

### Is there sufficient justification for why the study was done the way it was?

- [x] Yes (please specify)

The authors provide justification for their approach based on previous research on stereotype threat and working memory.

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [x] Yes (please specify)

The experimental design with random assignment to conditions is appropriate for examining the causal effects of stereotype threat and its moderation by working memory capacity.

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?

- [x] A little (please specify)

While the experimental design helps rule out some alternative explanations, the lack of information on potential confounds and the single-session design limit the ability to rule out all alternative explanations.

### How generalisable are the study results?

The results may generalize to high-achieving engineering students in France, but generalizability to other populations or cultures is unclear.

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?

- [x] Medium trustworthiness (please specify)

The study uses appropriate measures and analysis techniques, but lacks some important details on sampling and procedures. The use of established measures and the experimental design increase trustworthiness, but the lack of information on potential confounds and limited generalizability reduce it somewhat.

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [x] Medium trustworthiness

The authors' conclusions are generally justified based on their findings, but they could have been more cautious in their interpretations given the limitations of the study (e.g., single sample, lack of long-term follow-up).

# @wellsNewcastleottawaScaleNOS2014

## **CASE CONTROL STUDIES**

This study is not a case-control study, so this section is not applicable.

## **COHORT STUDIES**

This study is not a cohort study, so this section is not applicable.

# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

This checklist is designed for systematic reviews, not individual studies, so it is not directly applicable to this paper.

## ARE THE RESULTS OF THIS REVIEW VALID?

Not applicable for this individual study.

## WHAT ARE THE RESULTS?

Not applicable for this individual study.

## WILL THE RESULTS HELP LOCALLY?

Not applicable for this individual study.


# References


::: {#refs custom-style="Bibliography"}
:::
