---
title             : "@forbesRetrainingAttitudesStereotypes2010"
shorttitle        : "@forbesRetrainingAttitudesStereotypes2010"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h3.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

# @eppi-centreReviewGuidelinesExtracting2003 & @criticalappraisalskillsprogrammeCASPSystematicReview2018

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [x] Not applicable (whole study is focus of data extraction)  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?
*Please write in authors' declaration if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  

The study was explicitly informed by prior research on stereotype threat, attitudes, stereotypes, working memory, and motivation. The authors cite numerous studies and theories throughout the introduction to establish the rationale for their research questions.

### Do authors report how the study was funded?

- [x] Explicitly stated (please specify)  

The research was supported by a Social and Behavioral Sciences Research Institute Dissertation Research Grant awarded to the first author, and National Institute of Mental Health Grant #1R01MH071749 to the second author.

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

The study focuses on the effects of retraining attitudes and stereotypes on motivation and cognitive capacity in stereotype threatening contexts, particularly for women in math domains.

### What is/are the population focus/foci of the study?

The population focus is on women, particularly those who are moderately math-identified.

### What is the relevant age group? 

- [x] 17 - 20  
- [x] 21 and over  

The participants were university students, likely ranging from late teens to early 20s.

### What is the sex of the population focus/foci?

- [x] Female only  

The primary focus was on female participants, though some studies included male participants for comparison.

### What is/are the educational setting(s) of the study?

- [x] Higher education institution  

The study was conducted with university students.

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)  

The study was carried out in the United States.

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

The study examines the effects of retraining math attitudes and gender-math stereotypes on women's math motivation and working memory capacity in stereotype threatening contexts. It uses associative training tasks to modify attitudes and stereotypes, and measures outcomes through math choice tasks, working memory assessments, and math performance tests.

### What are the study reserach questions and/or hypotheses?
*Research questions or hypotheses operationalise the aims of the study. Please write in authors' description if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  

The study tests several hypotheses, including:
1. Retraining women to have a positive math attitude will increase their math motivation.
2. The effects of attitude retraining on motivation will be enhanced when stereotypes are present.
3. Retraining gender stereotypes about math will improve women's working memory capacity under stereotype threat.
4. Stereotype retraining will improve math performance, mediated by increased working memory capacity.

## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)  

The study measures:
- Math motivation (time spent on math problems)
- Working memory capacity
- Math performance
- Math attitudes
- Gender-math stereotypes

### Study timing
*Please indicate all that apply and give further details where possible.*

- [x] Prospective  

The study used a two-session design, with training in session 1 and outcome measures in session 2, 24-30 hours later.

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?

- [x] Before and after  

Outcome measures were taken 24-30 hours after the training intervention.

## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.

- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  

Participants were randomly assigned to different training conditions (attitude and/or stereotype retraining).

### How do the groups differ?

- [x] Explicityly stated (please specify)  

Groups differed based on the type of training received:
- Attitude training: like math vs. dislike math
- Stereotype training: stereotype reinforcement vs. counterstereotype retraining

### Number of groups

- [x] Four or more (please specify)  

Study 3, which is most relevant to H3, had four groups in a 2x2 design (attitude training x stereotype training).

### Was the assignment of participants to interventions randomised?

- [x] Random  

Participants were randomly assigned to training conditions.

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?

- [x] Yes (please specify)  

The training tasks were presented as categorization tasks related to memory, concealing the true purpose of the study.

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [x] Yes

All participants completed similar tasks, with only the specific training content differing between groups.

### Study design summary 

This study used a randomized experimental design with multiple between-subjects factors (attitude training, stereotype training, task description). Participants completed training tasks in session 1 and outcome measures in session 2. The design allowed for causal inferences about the effects of attitude and stereotype retraining on math motivation, working memory, and performance under stereotype threat conditions.

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 

- [x] Implicit (please specify)  

While not explicitly stated, the authors seem to be aiming for findings representative of moderately math-identified women in university settings.

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?

- [x] Explicitly stated (please specify)  

Participants were recruited from university mass testing sessions based on their responses to math identification questions.

### Which methods does the study use to select people or groups of people (from the sampling frame)?

- [x] Explicitly stated (please specify)  

Women were considered eligible if their average response to three math identification items was between 3.50 and 5.50 on a seven-point scale.

### Planned sample size

- [x] Not stated/unclear (please specify)  

The planned sample size is not explicitly stated for each study.

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?

- [x] Not stated/unclear (please specify)  

The specific recruitment methods are not detailed, beyond using mass testing sessions to identify eligible participants.

### Were any incentives provided to recruit people into the study?

- [x] Explicitly stated (please specify)  

Participants received course credit for their participation.

### Was consent sought?

- [x] Participant consent sought

While not explicitly stated, it is standard practice to obtain informed consent in psychological research.

### Are there any other details relevant to recruitment and consent?

- [x] No

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?

- [x] Explicitly stated (please specify)  

Study 3, which is most relevant to H3, had 120 participants included in the final analyses.

### What is the proportion of those selected for the study who actually participated in the study? 

- [x] Not stated/unclear (please specify)  

This information is not provided in the paper.

### Which country/countries are the individuals in the actual sample from?

- [x] Explicitly stated (please specify)  

The participants were from the United States.

### What ages are covered by the actual sample?

- [x] Not stated/unclear (please specify)  

The exact age range is not specified, but participants were university students.

### What is the socio-economic status of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)  

This information is not provided in the paper.

### What is the ethnicity of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)  

This information is not provided in the paper.

### What is known about the special educational needs of individuals within the actual sample?

- [x] Not stated/unclear (please specify)  

This information is not provided in the paper.

### Is there any other useful information about the study participants?

- [x] Explicitly stated (please specify no/s.)  

Participants were moderately math-identified women, as determined by their responses to math identification questions in mass testing sessions.

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 

- [x] Unclear (please specify)  

Without more information about the broader university population, it's unclear how representative the sample is.

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?

- [x] Explicitly stated (please specify)  

In Study 3, 9 out of 129 participants (7%) were excluded from analyses due to not following directions, correctly identifying the study purpose, or computer failure.

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [x] No

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [x] No

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [x] Details

(a) To define the sample: Math identification questions from mass testing sessions
(b) To measure aspects of the sample as findings: Math motivation (time spent on math problems), working memory scores, math performance accuracy

### Which methods were used to collect the data?

- [x] Self-completion questionnaire
- [x] Psychological test
- [x] Practical test

### Details of data collection methods or tool(s).

- [x] Explicitly stated (please specify)  

- Math motivation: Choice task between math and verbal problems, measuring time spent on math
- Working memory: Vowel counting version of the Reading Span Test
- Math performance: Necessary Arithmetic Operations Test (NAOT)
- Attitude and stereotype training: Modified versions of the Implicit Association Test (IAT)

### Who collected the data?

- [x] Researcher

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?

The authors do not explicitly discuss reliability of their measures, but they use established tasks (e.g., Reading Span Test) and their own previously published measures (e.g., Schmader & Johns, 2003).

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?

The authors cite previous research using similar measures and tasks, implying construct validity. They also use multiple outcome measures to assess different aspects of performance under stereotype threat.

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?

- [x] Yes (please specify)

Participants were unaware of the true purpose of the study and their condition assignment. The experimenters were female, but it's unclear if they were blind to condition.

### Where were the data collected?

- [x] Implicit (please specify)  

Data were likely collected in university laboratory settings, though this is not explicitly stated.

### Are there other important features of data collection?

No other important features are mentioned.

## Methods - Data analysis

### Which methods were used to analyse the data?

- [x] Explicitly stated (please specify)  

The primary analyses used ANOVAs and t-tests to compare outcomes between conditions. Regression analyses were used for mediation analyses.

### Which statistical methods, if any, were used in the analysis?

ANOVAs, t-tests, regression analyses, Sobel tests for mediation

### What rationale do the authors give for the methods of analysis for the study?

The authors do not provide an explicit rationale for their choice of analytical methods, but the methods are standard for experimental designs in psychology.

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.

- [x] 'Intention to intervene'

Analyses were conducted on the full sample, excluding only those who failed to follow instructions or identified the study purpose.

### Do the authors describe any ways they have addressed the reliability of data analysis?

The authors do not explicitly discuss reliability of data analysis.

### Do the authors describe any ways they have addressed the validity of data analysis?

The authors use multiple outcome measures and conduct mediation analyses to establish the validity of their findings.

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

The authors use random assignment to conditions to control for potential confounds.

### Please describe any other important features of the analysis.

The authors conduct supplementary analyses to examine the role of math identification in moderating effects.

### Please comment on any other analytic or statistical issues if relevant.

No other major analytic issues are apparent.

## Results and Conclusions

### How are the results of the study presented?

Results are presented through text descriptions, statistical test results, and figures showing mean differences between conditions.

### What are the results of the study as reported by authors?

For H3, the key results are:
- Women trained to associate their gender with being good at math showed higher working memory capacity under stereotype threat compared to those who reinforced the stereotype.
- This effect was only present when stereotype threat was induced.
- The increased working memory capacity mediated improved math performance for women trained with the counterstereotype.

### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [x] No

The authors report effect sizes (η2) but not confidence intervals.

### Are there any obvious shortcomings in the reporting of the data?

- [x] No

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?

- [x] Yes (please specify)

The authors report results for all key variables: math motivation, working memory, and math performance.

### Do the authors state where the full original data are stored?

- [x] No

### What do the author(s) conclude about the findings of the study?

The authors conclude that retraining gender stereotypes about math can improve women's working memory capacity and math performance under stereotype threat. They argue that stereotypes, rather than attitudes, are key to cognitive impairments due to stereotype threat.

## Quality of the study - Reporting 

### Is the context of the study adequately described?

- [x] Yes (please specify)

The authors provide a thorough theoretical background and rationale for the study.

### Are the aims of the study clearly reported?

- [x] Yes (please specify)

The aims and hypotheses are clearly stated throughout the introduction.

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?

- [x] Yes (please specify)

The authors describe their sampling criteria and recruitment methods, though some details (e.g., exact recruitment procedures) are lacking.

### Is there an adequate description of the methods used in the study to collect data?

- [x] Yes (please specify)

The authors provide detailed descriptions of their training tasks and outcome measures.

### Is there an adequate description of the methods of data analysis?

- [x] Yes (please specify)

The analytical methods are described, though more detail on some aspects (e.g., handling of missing data) could be provided.

### Is the study replicable from this report?

- [x] Yes (please specify)

The methods are described in sufficient detail to allow replication.

### Do the authors avoid selective reporting bias?

- [x] Yes (please specify)

The authors report results for all key variables and conditions.

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?

- [x] No concerns

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [x] No (please specify)

There is no indication of student involvement in the study design.

### Is there sufficient justification for why the study was done the way it was?

- [x] Yes (please specify)

The authors provide a clear rationale for their study design based on prior research and theory.

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [x] Yes (please specify)

The experimental design with random assignment to conditions is appropriate for testing causal effects of attitude and stereotype retraining.

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?

- [x] A lot (please specify)  

The experimental design with random assignment and use of established measures helps rule out many alternative explanations. The two-session design also minimizes demand characteristics and priming effects.

### How generalisable are the study results?

The results may be generalizable to moderately math-identified women in university settings, but caution should be taken in generalizing to other populations or contexts.

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?

- [x] High trustworthiness (please specify)

The study uses appropriate methods and measures, has a strong theoretical foundation, and employs rigorous experimental design. The findings are generally consistent across multiple studies.

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [x] High trustworthiness

The authors provide thorough discussion of their findings in relation to prior research and theory. They acknowledge limitations and suggest directions for future research.

# @wellsNewcastleottawaScaleNOS2014

This section is not applicable as the study is not a case-control or cohort study.

# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

### Did the review address a clearly focussed issue?
- Was there enough information on:
  - The population studied
  - The intervention given
  - The outcomes considered
- [x] Yes

The study clearly focuses on the effects of attitude and stereotype retraining on women's math motivation, working memory, and performance under stereotype threat.

### Did the authors look for the appropriate sort of papers?
- The 'best sort of studies' would:
  - Address the review's question
  - Have an appropriate study design
- [x] Can't tell

This is not a review paper, so this question is not applicable.

## ARE THE RESULTS OF THIS REVIEW VALID?

### Do you think the important, relevant studies were included?
- [x] Can't tell

This is not a review paper, so this question is not applicable.

### Did the review's authors do enough to assess the quality of the included studies?
- [x] Can't tell

This is not a review paper, so this question is not applicable.

### If the results of the review have been combined, was it reasonable to do so?
- [x] Can't tell

This is not a review paper, so this question is not applicable.

## WHAT ARE THE RESULTS?

### What is the overall result of the review?

This is not a review paper. The overall results of this experimental study suggest that retraining gender stereotypes about math can improve women's working memory capacity and math performance under stereotype threat conditions.

### How precise are the results?
- Are the results presented with confidence intervals?
- [x] No

The results are presented with effect sizes (η2) but not confidence intervals.

## WILL THE RESULTS HELP LOCALLY?

### Can the results be applied to the local population?
- [x] Can't tell

The applicability to local populations would depend on the specific context and how similar it is to the university setting of this study.

### Were all important outcomes considered?
- [x] Yes

The study considered multiple relevant outcomes: math motivation, working memory capacity, and math performance.

### Are the benefits worth the harms and costs?
- [x] Yes

The interventions used in this study (brief retraining tasks) are low-cost and low-risk, with potential benefits for reducing stereotype threat effects.


# References


::: {#refs custom-style="Bibliography"}
:::
