---
title             : "@schmaderConvergingEvidenceThat2003"
shorttitle        : "@schmaderConvergingEvidenceThat2003"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h3.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here

- [x] Not applicable (whole study is focus of data extraction)

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?

- [x] Explicitly stated (please specify)

The study was informed by previous research on stereotype threat and working memory capacity. The authors cite work by Steele and colleagues on stereotype threat effects, as well as research on working memory capacity by Engle and others.

### Do authors report how the study was funded?

- [x] Explicitly stated (please specify)

The research was supported in part by National Science Foundation Grant BCS-0112427 and by a faculty small grant awarded to Toni Schmader from the University of Arizona Foundation.

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

The study focuses on stereotype threat and its effects on working memory capacity and math test performance for women.

### What is/are the population focus/foci of the study?

The population focus is female undergraduate students.

### What is the relevant age group? 

- [x] 17 - 20
- [x] 21 and over

The study used undergraduate students, likely spanning both age ranges.

### What is the sex of the population focus/foci?

- [x] Female only

### What is/are the educational setting(s) of the study?

- [x] Higher education institution

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)

The study was carried out in the United States, at the University of Arizona.

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

The study examines how stereotype threat affects women's working memory capacity and math test performance. It investigates whether reduced working memory capacity mediates the effect of stereotype threat on math performance.

### What are the study reserach questions and/or hypotheses?

- [x] Explicitly stated (please specify)

The main hypothesis was that stereotype threat interferes with test performance because it reduces individuals' working memory capacity. Specifically, they predicted that women under stereotype threat would show reduced working memory capacity and that this reduction would mediate the effect of stereotype threat on math test performance.

## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)

The study measures working memory capacity, math test performance, stereotype threat (manipulated), anxiety, test difficulty perceptions, and gender identity threat.

### Study timing

- [x] Cross-sectional

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?

- [x] Only after

Measurements were taken after the stereotype threat manipulation.

## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.

- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)

Participants were randomly assigned to either a stereotype threat condition or a control condition.

### How do the groups differ?

- [x] Explicityly stated (please specify)

In the stereotype threat condition, women participated as the sole female in a session with male confederates and were told they would be taking a math test. In the control condition, women participated in all-female sessions and were told they would complete a problem-solving task.

### Number of groups

- [x] Two

Stereotype threat condition and control condition.

### Was the assignment of participants to interventions randomised?

- [x] Random

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?

- [x] Not stated/unclear (please specify)

The paper does not explicitly state whether allocation was concealed.

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [ ] Yes
- [x] No
- [ ] Can't tell

The groups differed in the gender composition of the testing session and the description of the upcoming task.

### Study design summary 

This study used a randomized experimental design with two conditions: stereotype threat and control. Female undergraduate participants were randomly assigned to one of these conditions. In the stereotype threat condition, women participated as the sole female in a session with male confederates and were told they would be taking a math test. In the control condition, women participated in all-female sessions and were told they would complete a problem-solving task. All participants completed a working memory task followed by a standardized math test.

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 

- [x] Implicit (please specify)

While not explicitly stated, the authors seem to be aiming for findings representative of female undergraduate students with moderate to high math ability.

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?

- [x] Explicitly stated (please specify)

Participants were selected from undergraduate psychology students who had scored 500 or higher on the quantitative section of the SAT and who indicated awareness of the stereotype about women's math ability.

### Which methods does the study use to select people or groups of people (from the sampling frame)?

- [x] Explicitly stated (please specify)

Participants were randomly selected from those meeting the criteria and randomly assigned to conditions.

### Planned sample size

- [x] Not stated/unclear (please specify)

The planned sample size is not explicitly stated.

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?

- [x] Not stated/unclear (please specify)

The specific recruitment methods are not described in detail.

### Were any incentives provided to recruit people into the study?

- [x] Explicitly stated (please specify)

Participants completed the study in exchange for course credit or $10.

### Was consent sought?

- [x] Participant consent sought

The paper mentions that participants signed a consent form.

### Are there any other details relevant to recruitment and consent?

- [x] No

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?

- [x] Explicitly stated (please specify)

The final sample consisted of 28 female undergraduates.

### What is the proportion of those selected for the study who actually participated in the study? 

- [x] Not stated/unclear (please specify)

This information is not provided in the paper.

### Which country/countries are the individuals in the actual sample from?

- [x] Explicitly stated (please specify)

The participants were from the United States, specifically students at the University of Arizona.

### What ages are covered by the actual sample?

- [x] Not stated/unclear (please specify)

The specific ages are not reported, but the sample consisted of undergraduate students.

### What is the socio-economic status of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)

This information is not provided in the paper.

### What is the ethnicity of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)

The ethnicity of participants is not reported.

### What is known about the special educational needs of individuals within the actual sample?

- [x] Not stated/unclear (please specify)

No information is provided about special educational needs.

### Is there any other useful information about the study participants?

- [x] Explicitly stated (please specify no/s.)

Participants had scored 500 or higher on the quantitative section of the SAT and indicated awareness of the stereotype about women's math ability.

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 

- [x] Unclear (please specify)

The paper does not provide enough information to determine representativeness.

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?

- [x] Not applicable (not following samples prospectively over time)

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [x] Not applicable (not following samples prospectively over time)

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [x] Not applicable (not following samples prospectively over time)

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [x] Details

(a) To define the sample: SAT scores and awareness of gender stereotypes about math ability.
(b) To measure aspects of the sample: Working memory capacity, math test performance, anxiety, perceived test difficulty, and gender identity threat.

### Which methods were used to collect the data?

- [x] Self-completion questionnaire
- [x] Psychological test
- [x] Clinical test

### Details of data collection methods or tool(s).

- [x] Explicitly stated (please specify)

Working memory was measured using a modified operation-span task. Math performance was measured using a 30-item multiple-choice test from GRE practice exams. Self-report measures were used for anxiety, perceived difficulty, and gender identity threat.

### Who collected the data?

- [x] Researcher

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?

The authors mention using established measures (e.g., GRE practice questions) but do not explicitly discuss reliability.

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?

The authors discuss modifying the working memory task to address potential confounds and use established measures for other constructs.

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?

- [x] No (please specify)

The experimenters were aware of participants' condition assignments.

### Where were the data collected?

- [x] Explicitly stated (please specify)

Data were collected in a laboratory setting at the University of Arizona.

### Are there other important features of data collection?

- [x] Details

The study used confederates in the stereotype threat condition to create a solo status situation for female participants.

## Methods - Data analysis

### Which methods were used to analyse the data?

- [x] Explicitly stated (please specify)

The authors used t-tests to compare group means and regression analyses for mediation testing.

### Which statistical methods, if any, were used in the analysis?

T-tests, regression analyses, Sobel test for mediation.

### What rationale do the authors give for the methods of analysis for the study?

The authors do not explicitly justify their choice of analytical methods.

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.

- [x] 'Intention to intervene'

### Do the authors describe any ways they have addressed the reliability of data analysis?

The authors do not explicitly address reliability of data analysis.

### Do the authors describe any ways they have addressed the validity of data analysis?

The authors conducted reverse mediation analyses to rule out alternative explanations.

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

The authors do not explicitly describe strategies to control for confounding variables.

### Please describe any other important features of the analysis.

The authors used mediation analyses to test their hypothesis about working memory capacity mediating the effect of stereotype threat on math performance.

### Please comment on any other analytic or statistical issues if relevant.

No other major analytic or statistical issues are apparent.

## Results and Conclusions

### How are the results of the study presented?

Results are presented through text descriptions, statistical test results, and one figure showing the mediation model.

### What are the results of the study as reported by authors?

Women in the stereotype threat condition showed lower working memory capacity and poorer math test performance compared to the control condition. Working memory capacity mediated the effect of stereotype threat on math performance.

### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [ ] Yes
   - [x] No
   - [ ] Can't tell

### Are there any obvious shortcomings in the reporting of the data?

- [x] No

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?

- [x] Yes (please specify)

The authors report on all main variables: working memory capacity, math test performance, and mediational analyses.

### Do the authors state where the full original data are stored?

- [x] No

### What do the author(s) conclude about the findings of the study?

The authors conclude that stereotype threat reduces women's working memory capacity, which in turn mediates the effect of stereotype threat on math test performance.

## Quality of the study - Reporting 

### Is the context of the study adequately described?

- [x] Yes (please specify)

The authors provide adequate context about stereotype threat research and working memory capacity.

### Are the aims of the study clearly reported?

- [x] Yes (please specify)

The aims to test whether working memory capacity mediates stereotype threat effects are clearly stated.

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?

- [x] Yes (please specify)

The sample characteristics and selection criteria are adequately described.

### Is there an adequate description of the methods used in the study to collect data?

- [x] Yes (please specify)

The methods for collecting data on working memory and math performance are well described.

### Is there an adequate description of the methods of data analysis?

- [x] Yes (please specify)

The statistical analyses, including mediation tests, are adequately described.

### Is the study replicable from this report?

- [x] Yes (please specify)

The methods are described in sufficient detail to allow replication.

### Do the authors avoid selective reporting bias?

- [x] Yes (please specify)

The authors report on all main variables and analyses mentioned in their aims.

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?

- [x] No concerns

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [x] No (please specify)

There is no indication of student or parent involvement in the study design or conduct.

### Is there sufficient justification for why the study was done the way it was?

- [x] Yes (please specify)

The authors justify their approach based on previous research on stereotype threat and working memory.

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [x] Yes (please specify)

The experimental design with random assignment was appropriate for testing the causal effects of stereotype threat.

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?

- [x] A little (please specify)

While the experimental design helps rule out some alternative explanations, the authors acknowledge potential limitations and conduct additional analyses to address some concerns.

### How generalisable are the study results?

The results may be generalizable to female undergraduate students with moderate to high math ability, but further research would be needed to establish broader generalizability.

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?

- [x] Medium trustworthiness (please specify)

The study uses appropriate methods and analyses, but some limitations (e.g., sample size, potential demand characteristics) suggest medium trustworthiness.

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [x] Medium trustworthiness

The authors provide reasonable justification for their conclusions, but acknowledge some limitations and the need for further research.


# References


::: {#refs custom-style="Bibliography"}
:::
