---
title             : "@hutterWomenStereotypeThreat2019"
shorttitle        : "@hutterWomenStereotypeThreat2019"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h3.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [X] Not applicable (whole study is focus of data extraction)  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?

- [X] Explicitly stated (please specify)  

The study was informed by previous research on stereotype threat effects, particularly the mere effort account and working memory interference perspective. It references work by Steele & Aronson (1995), Jamieson & Harkins (2007, 2009), Schmader et al. (2008), and others.

### Do authors report how the study was funded?

- [X] Not stated/unclear (please specify)  

The paper does not mention any funding sources.

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

The study focuses on stereotype threat effects on women's math performance, examining the motivational and prepotent response mechanisms proposed by the mere effort account versus the working memory interference perspective.

### What is/are the population focus/foci of the study?

The population focus is female undergraduate students.

### What is the relevant age group? 

- [X] 17 - 20  
- [X] 21 and over  

The participants were female undergraduates aged 18-25 years (M=20.50, SD=1.61).

### What is the sex of the population focus/foci?

- [X] Female only  

### What is/are the educational setting(s) of the study?

- [X] Higher education institution  

### In Which country or cuntries was the study carried out?

- [X] Explicitly stated (please specify)  

The study was carried out in the UK.

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

The study examines stereotype threat effects on women's math performance, comparing the mere effort account (focusing on motivation and prepotent responses) to the working memory interference perspective. It investigates how stereotype threat affects performance on different types of math questions (solve vs. comparison) and the role of inhibitory ability.

### What are the study reserach questions and/or hypotheses?

- [X] Explicitly stated (please specify)  

The study hypothesized that:
1) Stereotype threat would lead to performance boost for solve questions and performance decrement for comparison questions.
2) Higher inhibitory ability would protect overall math performance following stereotype threat, but would not protect non-prepotentiated comparison question performance.

## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [X] Explicitly stated (please specify)  

The study measured:
- Math performance (overall and by question type)
- Inhibitory ability (using a Stroop task)
- Indirect math motivation
- Gender identification
- Math identification

### Study timing

- [X] Cross-sectional  

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?

- [X] Only after  

Measurements were taken after the stereotype threat manipulation and math test.

## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.

- [X] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  

Participants were randomly assigned to stereotype threat or no-stereotype threat conditions, and to solve or comparison question types.

### How do the groups differ?

- [X] Explicityly stated (please specify)  

The groups differed based on:
1) Stereotype threat condition (stereotype threat vs. no-stereotype threat)
2) Math question type (solve vs. comparison)

### Number of groups

- [X] Four or more (please specify)  

There were 4 groups: 2 (stereotype threat condition) x 2 (question type)

### Was the assignment of participants to interventions randomised?

- [X] Random  

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?

- [X] Not stated/unclear (please specify)  

The paper does not explicitly state if allocation was concealed.

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [X] Yes

All groups completed the same procedures aside from the experimental manipulations.

### Study design summary 

This was a 2 (condition: stereotype threat, no-stereotype threat) × 2 (question type: solve, comparison) between-subjects experimental design with inhibitory ability as a continuous moderator variable. Participants were randomly assigned to conditions and completed a Stroop task, math test, and post-test measures.

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 

- [X] Implicit (please specify)

While not explicitly stated, the authors seem to be aiming for findings representative of female undergraduate students in the UK.

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?

- [X] Explicitly stated (please specify)

The study used an opportunity sample of female undergraduate psychology students at a UK university.

### Which methods does the study use to select people or groups of people (from the sampling frame)?

- [X] Explicitly stated (please specify)

The study used an opportunity sample of female undergraduate psychology students.

### Planned sample size

- [X] Explicitly stated (please specify)

The planned sample size was 165 participants.

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?

- [X] Not stated/unclear (please specify)

The specific recruitment methods are not described in the paper.

### Were any incentives provided to recruit people into the study?

- [X] Not stated/unclear (please specify)

The paper does not mention any incentives for participation.

### Was consent sought?

- [X] Not stated/unclear (please specify)

The paper does not explicitly mention obtaining consent, though this was likely done as standard practice.

### Are there any other details relevant to recruitment and consent?

- [X] No

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?

- [X] Explicitly stated (please specify)

The actual sample size was 165 female undergraduate students.

### What is the proportion of those selected for the study who actually participated in the study? 

- [X] Not stated/unclear (please specify)

The paper does not provide information on the proportion of selected participants who actually participated.

### Which country/countries are the individuals in the actual sample from?

- [X] Explicitly stated (please specify)

The participants were from the UK.

### What ages are covered by the actual sample?

- [X] 17 to 20
- [X] 21 and over

The participants were aged 18-25 years (M=20.50, SD=1.61).

### What is the socio-economic status of the individuals within the actual sample?

- [X] Not stated/unclear (please specify)

The socio-economic status of participants is not reported.

### What is the ethnicity of the individuals within the actual sample?

- [X] Explicitly stated (please specify)

All participants identified as British Caucasian.

### What is known about the special educational needs of individuals within the actual sample?

- [X] Not stated/unclear (please specify)

No information is provided about special educational needs.

### Is there any other useful information about the study participants?

- [X] Explicitly stated (please specify no/s.)

All participants had achieved at least a GCSE C grade in Math and were native English speakers.

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 

- [X] Unclear (please specify)

The representativeness of the sample is not explicitly discussed.

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?

- [X] Not applicable (not following samples prospectively over time)

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [X] Not applicable (not following samples prospectively over time)

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [X] Not applicable (not following samples prospectively over time)

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [X] Details

The main types of data collected were:
a) To define the sample: age, ethnicity, language, math grade
b) As findings: Stroop task performance (inhibitory ability), math test scores, manipulation check items, indirect math motivation, gender identification, math identification

### Which methods were used to collect the data?

- [X] Exams
- [X] Clinical test
- [X] Self-completion questionnaire

### Details of data collection methods or tool(s).

- [X] Explicitly stated (please specify)

The study used:
- A Stroop task to measure inhibitory ability
- A math test with solve and comparison questions
- Self-report measures for manipulation checks, motivation, and identifications

### Who collected the data?

- [X] Explicitly stated (please specify)

A female experimenter conducted the study.

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?

- [X] Details

The authors do not explicitly discuss reliability of their measures.

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?

- [X] Details

The authors mention piloting the math questions to ensure equal difficulty across solve and comparison types.

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?

- [X] Not stated/unclear (please specify)

The paper does not explicitly state if outcome assessors were blinded to condition.

### Where were the data collected?

- [X] Explicitly stated (please specify)

Data were collected in a laboratory setting at the university.

### Are there other important features of data collection?

- [X] Details

The math test was conducted under timed conditions (18 minutes total) to simulate exam conditions.

## Methods - Data analysis

### Which methods were used to analyse the data?

- [X] Explicitly stated (please specify)

The study used moderated regression analysis and ANCOVAs.

### Which statistical methods, if any, were used in the analysis?

- [X] Details

The study used moderated regression analysis, ANCOVAs, and simple regressions for follow-up analyses.

### What rationale do the authors give for the methods of analysis for the study?

- [X] Details

The authors do not provide an explicit rationale for their choice of analysis methods.

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.

- [X] Not stated/unclear (please specify)

The basis for data analysis is not explicitly stated, but appears to be 'intention to intervene'.

### Do the authors describe any ways they have addressed the reliability of data analysis?

- [X] Details

The authors do not explicitly discuss reliability of their data analysis.

### Do the authors describe any ways they have addressed the validity of data analysis?

- [X] Details

The authors do not explicitly discuss validity of their data analysis.

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [X] Details

The authors included indirect math motivation, gender identification, and math identification as covariates in some analyses.

### Please describe any other important features of the analysis.

- [X] Details

The authors used centered continuous scores for inhibitory ability in their moderated regression analysis.

### Please comment on any other analytic or statistical issues if relevant.

- [X] Details

No other major analytic or statistical issues are apparent.

## Results and Conclusions

### How are the results of the study presented?

- [X] Details

Results are presented through text descriptions of statistical outcomes, tables of regression results, and figures showing interactions.

### What are the results of the study as reported by authors?

- [X] Details

Key results include:
- Stereotype threat led to better performance on solve vs. comparison questions
- Higher inhibitory ability protected overall math performance under stereotype threat
- Inhibitory ability did not specifically protect comparison question performance under stereotype threat
- Stereotype threat did not affect indirect math motivation or identifications

### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [X] No

### Are there any obvious shortcomings in the reporting of the data?

- [X] No

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?

- [X] Yes (please specify)

The authors report on all key variables mentioned in their aims and hypotheses.

### Do the authors state where the full original data are stored?

- [X] No

### What do the author(s) conclude about the findings of the study?

- [X] Details

The authors conclude that their findings support the mere effort account over the working memory interference perspective. They argue that stereotype threat motivates overproduction of prepotent responses rather than interfering with working memory.

## Quality of the study - Reporting 

### Is the context of the study adequately described?

- [X] Yes (please specify)

The study context is well described, including background on stereotype threat theories and previous research.

### Are the aims of the study clearly reported?

- [X] Yes (please specify)

The study aims and hypotheses are clearly stated.

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?

- [X] Yes (please specify)

The sample characteristics and selection criteria are adequately described.

### Is there an adequate description of the methods used in the study to collect data?

- [X] Yes (please specify)

The data collection methods are described in sufficient detail.

### Is there an adequate description of the methods of data analysis?

- [X] Yes (please specify)

The data analysis methods are adequately described, though more detail on rationale could have been provided.

### Is the study replicable from this report?

- [X] Yes (please specify)

The methods are described in sufficient detail to allow replication.

### Do the authors avoid selective reporting bias?

- [X] Yes (please specify)

The authors appear to report on all variables and analyses mentioned in their aims and methods.

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?

- [X] No concerns

No ethical concerns are apparent from the reported methods.

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [X] No (please specify)

There is no mention of student or parent involvement in study design or conduct.

### Is there sufficient justification for why the study was done the way it was?

- [X] Yes (please specify)

The authors provide adequate justification for their study design based on previous research and theory.

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [X] Yes (please specify)

The experimental design was appropriate for testing the stated hypotheses about stereotype threat effects.

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?

- [X] A little (please specify)

The randomized design helps control for some biases, but there may be potential confounds in the sample selection and measures used.

### How generalisable are the study results?

- [X] Details

The results may be generalizable to female undergraduate students in the UK, but generalizability to other populations is limited.

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?

- [X] Medium trustworthiness (please specify)

The study has a sound design and analysis, but some limitations in sample and measures affect trustworthiness.

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [X] Medium trustworthiness

The conclusions are generally well-justified based on the findings, but some interpretations could benefit from more cautious framing or additional evidence.


# References


::: {#refs custom-style="Bibliography"}
:::
