---
title             : "@forbesRetrainingAttitudesStereotypes2010"
shorttitle        : "@forbesRetrainingAttitudesStereotypes2010"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h3.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

# @eppi-centreReviewGuidelinesExtracting2003 & @criticalappraisalskillsprogrammeCASPSystematicReview2018

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [ ] Not applicable (whole study is focus of data extraction)  
- [x] Specific focus of this data extraction (please specify)  

- Study 1 
- 2 was excluded since it didn't measure working memory
- 3 was excluded since it was not clear whether or not it was in the academic context. In the other studies it was explicitly mentioned that participants were compensated with course credit, inferring that they were students. Only in Study 3 the authors skipped this description and simply mentioned that the participants were moderately math-identified women, no mention of compensation or anything else that could be related to the academic context.  
- 4 was excluded since it does not actually measure the impact stereotype threat has on working memory, instead it measures whether or not working memory improved under retraining.  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?
*Please write in authors' declaration if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Stereotype threat
- Stereotype threat and working memory
- Work of Amodio and Devine (2006)
- Stereotype threat and motivation  
- mere effort perspective on stereotype threat  

### Do authors report how the study was funded?

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

This research was supported by a Social and Behavioral Sciences Research Institute Dissertation Research Grant awarded to the first author, and National Institute of Mental Health Grant #1R01MH071749 to the second author.


## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

- The present research will examine experimentally if changing stereotypes and attitudes differently affects the cognitive capacity and motivation needed for successful test performance.  

### What is/are the population focus/foci of the study?

- women under maths stereotype threat   

### What is the relevant age group? 

- [ ] Not applicate (focus not learners)  
- [ ] 0 - 4  
- [ ] 5 - 10  
- [ ] 11 - 16  
- [ ] 17 - 20  
- [ ] 21 and over  
- [x] Not stated/unclear  

### What is the sex of the population focus/foci?

- [ ] Not applicate (focus not learners)  
- [x] Female only  
- [ ] Male only  
- [ ] Mixed sex  
- [ ] Not stated/unclear  

### What is/are the educational setting(s) of the study?

- [ ] Community centre  
- [ ] Correctional institution  
- [ ] Government department  
- [x] Higher education institution  
- [ ] Home  
- [ ] Independent school  
- [ ] Local education authority  
- [ ] Nursery school  
- [ ] Other early years setting  
- [ ] Post-compulsory education institution  
- [ ] Primary school  
- [ ] Residential school  
- [ ] Secondary school  
- [ ] Special needs school  
- [ ] Workplace  
- [ ] Other educational setting  

### In Which country or cuntries was the study carried out?

- [ ] Explicitly stated (please specify)  
- [x] Not stated/unclear (please specify)  

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

### What are the study reserach questions and/or hypotheses?
*Research questions or hypotheses operationalise the aims of the study. Please write in authors' description if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  


**Study 1**:
- The purpose of Study 1 was to test the hypothesis that retraining women to have a positive maths attitude will motivated them to spend more time working at maths problems compared to women reinforced with a negative maths. We hypothesized that retraining attitudes would elevate motivation in a neutral context, but would not increase working memory capacity or performance on complex maths problems when cues to threat are present.

**Study 4**:
- We assume that having the counter stereotype about women and maths is specifically beneficial when cues to stereotype threat are present. 
- Study 4 focused exclusively on counterstereotype retraining as a means to improve women's maths performance, as mediated by an increase in working memory, when cues to stereotype threat are present.



## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Study 1**:
- pIAT
- maths motivation
- working memory capacity
- maths performance

**Study 4**:
- pIAT and traditional IAT
- working memory
- maths test 
- demographic questionnaire



### Study timing
*Please indicate all that apply and give further details where possible.*

*If the study examines one or more samples, but each at only one point in time it is cross-sectional.*  
*If the study examines the same samples, but as they have changed over time, it is retrospective, provided that the interest is in starting at one timepoint and looking backwards over time.*  
*If the study examines the same samples as they have changed over time and if data are collected forward over time, it is prospective provided that the interest is in starting at one timepoint and looking forward in time.*  

- [ ] Cross-sectional  
- [ ] Retrospective  
- [x] Prospective  
- [ ] Not stated/unclear (please specify)  

- prospective


### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?
*If at least one of the outcome variables is measured both before and after the intervention, please use the before and after category.*

- [ ] Not applicable (not an evaluation)  
- [ ] Before and after  
- [x] Only after  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  

- after


## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.
*Please give further details where possible.*

- [ ] Not applicable (not more than one group)  
- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  
- [ ] No prospective allocation but use of pre-existing differences to create comparison groups (e.g. receiving different interventions, or characterised by different levels of a variable such as social class)  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  

### How do the groups differ?

- [ ] Not applicable (not more than one group)  
- [x] Explicityly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Study 1**:
- "like maths" vs "dislike maths"

**Study 4**:
- 2 (stereotype training: 'stereotype reinforcement' or 'counterstereotype retraining') x 2 (Task description: 'Diagnostic maths test' or 'Problem solving task') factorical design.



### Number of groups
*For instance, in studies in which comparisons are made between groups, this may be the number of groups into which the dataset is divided for analysis (e.g. social class, or form size), or the number of groups allocated to, or receiving, an intervention.*

- [ ] Not applicable (not more than one group)  
- [ ] One  
- [x] Two  
- [ ] Three  
- [ ] Four or more (please specify)  
- [ ] Other/unclear (please specify)  

**Study 1**:
- two

**Study 4**:
- four


### Was the assignment of participants to interventions randomised?

- [ ] Not applicable (not more than one group)  
- [ ] Not applicate (no prospective allocation)  
- [x] Random  
- [ ] Quasi-random  
- [ ] Non-random  
- [ ] Not stated/unclear (please specify) 

- random  

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?
*Bias can be introduced, consciously or otherwise, if the allocation of pupils or classes or schools to a programme or intervention is made in the knowledge of key characteristics of those allocated. For example: children with more serious reading difficulty might be seen as in greater need and might be more likely to be allocated to the 'new' programme, or the opposite might happen. Either would introduce bias.*

- [ ] Not applicable (not more than one group)  
- [ ] Not applicable (no prospective allocation)  
- [x] Yes (please specify)  
- [ ] No (please specify)  
- [ ] Not stated/unclear (please specify)  

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [x] Yes
- [ ] No
- [ ] Can’t tell

### Study design summary 
*In addition to answering the questions in this section, describe the study design in your own words. You may want to draw upon and elaborate the answers you have already given.*

**Study 1**:
1. pIAT
2. 24 to 30 hours break
3. math effort task, working memory measure, math strategy test
4. debriefing  

**Study 4**:
1. pIAT and traditional IAT
2. 24 to 30 hours break
3. Stereotype threat manipulation
   - either just a demographic questionnaire without the gender and information that they were to complete problem solving tasks(no stereotype threat)
   - recording of a male researcher that they would be completing a diagnostic measure of their natural maths ability after the working memory task, they were also asked to mark their gendre on a demographic questionniare)
4. working memory measue (from Study 1 and 3)
5. maths test (GRE)
6. debriefing


## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 
*Please write in authors' description. If authors do not specify please indicate reviewers' interpretation.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- moderately math identified women under math stereotype threat 

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?
*e.g. telephone directory, electoral register, postcode, school listing, etc. There may be two stages – e.g. first sampling schools and then classes or pupils within them.*

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)


**Study 1**:
- Based on mass survey data, women were considered eligible if their average response to three items: "Being good at maths is an important part of who I am", "I think that I'm good at tasks that require the use of maths", and "I like tasks that involve maths or computation" was between 3.5 and 5.5 on a 7-point scale.
- We targeted moderately maths identified women because those who are at the extremes of identification are also likely to have extreme attitudes toward the domain that would be more resistant to attitude change.  

**Study 4**:
- We did not select individuals on any predetermined characteristics like maths identification.  

### Which methods does the study use to select people or groups of people (from the sampling frame)?
*e.g. selecting people at random, systematically - selecting for example every 5th person, purposively in order to reach a quota for a given characteristic.*

- [ ] Not applicable (no sampling frame)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:
- characteristic: moderate maths identification and gender = female  

### Planned sample size
*If more than one group please give details for each group separately.*

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [x] Not stated/unclear (please specify)

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?
*e.g. letters of invitation, telephone contact, face-to-face contact.*

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Were any incentives provided to recruit people into the study?

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Not stated/unclear (please specify)

- Participants were compensated with course credit.  

### Was consent sought?
*Please comment on the quality of consent if relevant.*

- [ ] Not applicable (please specify)
- [ ] Participant consent sought
- [ ] Parental consent sought
- [ ] Other consent sought
- [ ] Consent not sought
- [x] Not stated/unclear (please specify)

### Are there any other details relevant to recruitment and consent?

- [x] No
- [ ] Yes (please specify)

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?
*If more than one group is being compared please give numbers for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:
- Fifty-eight (N = 58) moderately math identified women participated in the experiment for course credit and were randomly assigned to a 'like maths' or 'disklike maths' training condition.  

**Study 4**:
- One hundred and ninety women (N = 190) participated in the experiment for course credit.


### What is the proportion of those selected for the study who actually participated in the study? 
*Please specify numbers and percentages if possible.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

**Study 4**:
- nine participants were excluded for not following directions in either the training or working memory task and four were excluded for correctly identifying hte purpose of the study. Thus 177 participants were included in the analysies.  

### Which country/countries are the individuals in the actual sample from?
*If UK, please distinguish between England, Scotland, N. Ireland, and Wales if possible. If from different countries, please give numbers for each. If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What ages are covered by the actual sample?
*Please give the numbers of the sample that fall within each of the given categories. If necessary, refer to a page number in the report (e.g. for a useful table). If more than one group is being compared, please describe for each group. If follow-up study, age at entry to the study.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] 0 to 4
- [ ] 5 to 10
- [ ] 11 to 16
- [ ] 17 to 20
- [ ] 21 and over
- [x] Not stated/unclear (please specify)

### What is the socio-economic status of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is the ethnicity of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is known about the special educational needs of individuals within the actual sample?
*e.g. specific learning, physical, emotional, behavioural, intellectual difficulties.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Is there any other useful information about the study participants?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify no/s.)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 
*Please specify basis for your decision.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (no sampling frame)
- [x] High (please specify)
- [ ] Medium (please specify)
- [ ] Low (please specify)
- [ ] Unclear (please specify)

**Study 1**:
- They wanted to find moderately maths identified women, which they did.  

**Study 4**:
- high


### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?
*If the study involves more than one group, please give drop-out rates for each group separately. If necessary, refer to a page number in the report (e.g. for a useful table).*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (not following samples prospectively over time)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear

- not stated  

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (not following samples prospectively over time)
- [ ] Not applicable (no drop outs)
- [ ] Yes (please specify)
- [x] No

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (not following samples prospectively over time)
- [ ] Yes (please specify)
- [x] No

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [ ] Details

**Study 1**:
- Maths motivation -> b
- Working memory capacity -> b
- Maths performance -> b
- maths identification -> a

**Study 4**:
- demographic questionnaire -> a and b (due to the stereotype threat manipulation)
- working memory capacity -> b
- maths test -> b



### Which methods were used to collect the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Curriculum-based assessment
- [ ] Focus group
- [ ] Group interview
- [ ] One to one interview (face to face or by phone)
- [ ] Observation
- [ ] Self-completion questionnaire
- [ ] Self-completion report or diary
- [ ] Exams
- [ ] Clinical test
- [ ] Practical test
- [ ] Psychological test
- [ ] Hypothetical scenario including vignettes
- [ ] School/college records (e.g. attendance records etc)
- [ ] Secondary data such as publicly available statistics
- [ ] Other documentation
- [ ] Not stated/unclear (please specify)

### Details of data collection methods or tool(s).
*Please provide details including names for all tools used to collect data and examples of any questions/items given. Also please state whether source is cited in the report.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:
- Maths identification (for questions see above)
- Maths motivation: the motivation task was comprised of 30 maths and 30 remote associates (RAT) problems presented to participants on a series of choice screens
- Working memory capacity: The working memory task that participants completed was a vowel counting version adapted by Schmader and Johns (2003) from the Reading Span Test (Daneman & Carpenter, 1980)
- Maths performance: Was assessed with the Necessary Arithmetic Operations Test (NAOT; Ekstrom, French, Harman, & Dermen, 1976).  

**Study 4**:
- same stereotype retraining task described in Study 3 during Session 1
- maths test composed of 30 moderately difficult maths problems taken from the GRE (Schmader & Johns, 2003).

### Who collected the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Researcher
- [ ] Head teacher/Senior management
- [ ] Teaching or other staff
- [ ] Parents
- [ ] Pupils/students
- [ ] Governors
- [ ] LEA/Government officials
- [ ] Other education practitioner
- [ ] Other (please specify)
- [ ] Not stated/unclear

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?
*e.g. test-retest methods (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?
*e.g. mention previous validation of tools, published version of tools, involvement of target population in development of tools. (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?
*Not applicable – e.g. analysis of existing data, qualitative study. No – e.g. assessment of reading progress for dyslexic pupils done by teacher who provided intervention. Yes – e.g. researcher assessing pupil knowledge of drugs - unaware of pupil allocation.*

- [ ] Not applicable (please say why)
- [ ] Yes (please specify)
- [ ] No (please specify)

### Where were the data collected?
*e.g. school, home.*

- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Unclear/not stated (please specify)

### Are there other important features of data collection?
*e.g. use of video or audio tape; ethical issues such as confidentiality etc.*

- [ ] Details

## Methods - Data analysis

### Which methods were used to analyse the data?
*Please give details e.g. for in-depth interviews, how were the data handled? Details of statistical analysis can be given next.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

### Which statistical methods, if any, were used in the analysis?

- [ ] Details

**Study 1**:
*Maths motivation*:
- means calculation
- independent samples t-test on the total amount of time participants spent working on maths problems during the choice task
- parallel analysis  
*Working memory and maths test performance*:
- independent samples t-test on women's working memory scores and performance accuracy on the maths test  
*Self-reported maths attitudes*:
- Means calculation
- regression analysis of both retraining condition and post-training self-report attitudes  

**Study 4**:
*Working memory:*
- 2 x 2 ANOVA conducted on participants' working memory scores
- simple effects analyses  
*Maths test performance*:
- 2 x 2 ANOVA conducted on participants' maths test accuracy
- simple effects analyses  
*Mediated Moderation analyses*:
- regression analyses as per guidelines of Muller, Judd, and Yzerbyt (2005)   
*Supplementary Analyses*:
- within-cell correlations
- parallel analyses with maths performance

### What rationale do the authors give for the methods of analysis for the study?
*e.g. for their methods of sampling, data collection, or analysis.*

- [ ] Details

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.
*'Intention to intervene' means that data were analysed on the basis of the original number of participants as recruited into the different groups. 'Intervention received' means data were analysed on the basis of the number of participants actually receiving the intervention.*

- [ ] Not applicable (not an evaluation study with prospective allocation)
- [ ] 'Intention to intervene'
- [ ] 'Intervention received'
- [ ] Not stated/unclear (please specify)

### Do the authors describe any ways they have addressed the reliability of data analysis?
*e.g. using more than one researcher to analyse data, looking for negative cases.*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of data analysis?
*e.g. internal or external consistency; checking results with participants.*

- [ ] Details

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [ ] Details

### Please describe any other important features of the analysis.

- [ ] Details

### Please comment on any other analytic or statistical issues if relevant.

- [ ] Details

## Results and Conclusions

### How are the results of the study presented?
*e.g. as quotations/figures within text, in tables, appendices.*

- [ ] Details

**Study 1**:
- table
- in text

**Study 4**:
- Figures
- in text


### What are the results of the study as reported by authors?
*Please give details and refer to page numbers in the report(s) of the study where necessary (e.g. for key tables).*

- [ ] Details

**Study 1**:
*Maths motivation*:
- initial analyses of performance on the choice task revealed that participants looked at more maths problems than RAT problems, tended to provide an answer to them maths problems they looked at, and those answers were typically accurate 
- They also spent more total time on maths problems compared to RAT problems
- All participants spent some time on both kinds of problems (i.e., there were neither floor nor ceiling effects) and there was considerable variability in time spent on both types of problems.  
- Independent samples t-test conducted on the total amount of time participants spent working on maths problems during the choice task revealed that, as predicted, women trained to like maths spent significantly more time working on maths problems compared to women trained to dislike maths, although they were not necessarily more accurate in their solutions to the problems they answered
- Even with a 24 hour delay, the retraining task was successful at affecting women's motivation for maths
- In the parallel analysis conducted on the total time spent working on RAT problems revealed no differences between the two conditions
- Participants had a fixed amount of time to work on either type of problem or do noting, this suggests that the pattern of motivation effects was shaped more by the training of women's attitudes towards maths than by the yoked inverse training of their attitudes towards language.  

*Working memory and maths test performance*:
- Independent samples t-test on women's working memory scores and performance accuracy on the maths test revealed no significant differences on either variable
- Neither variable showed floor or ceiling effects
- These analyses provide no evidence that retraining attitudes enhances working memory or performance on complex maths test when cues to threat are present.  

*Self-reported maths attitudes*:
- Women trained to like maths reported comparable levels of self-reported maths liking compared to women trained to dislike maths
- When both retraining condition and post-training self-report attitudes were entered simultaneously into a regression analysis predicting maths motivation, both attitude retraining and self-reported maths attitudes had unique but independent relationships to maths motivation
- There was no evidence that the effects of attitude retraining on motivation were due to conscious changes in women's attitudes towards maths. 
- Self-report measures of maths liking were taken in subsequent studies but showed no effects of the attitude retraining manipulation and will thus not be discussed further.  



**Study 4**:
*Working memory*:
- A 2 x 2 ANOVA conducted on participants' working memory scores revealed a marginal main effect for stereotype threat training, that was qualified by the predicted interaction
- The main effect for task description was not significant
- Simple effects analyses revealed a pattern in the diagnostic condition that replicated the result from Study 3
- Women who received counterstereotype retraining exhibited greater working memory capacity when taking a 'diagnostic maths test' compared to women who received reinforcement training
- When the situation was stereotype neutral, stereotype retraining had no effect on working memory capacity.
- Among women who received counterstereotype retraining, working memory was higher in the diagnostic maths test condition compared to the problem solving task condition
- Women trained to reinforce the stereotype did not show significantly lower working memory when they believed they would be taking a 'diagnostic maths test' compared to a 'problem solving task'.  
*Maths test performance*:
- A 2 x 2 ANOVA conducted on participants' maths test accuracy yielded only the predicted interaction
- The main effects were not significant
- Consistent with the working memory findings, simple effects analyses indicated that women who thought they were taking a diagnostic maths test performed better on the maths test when they were retrained with the counterstereotype - women are good at maths - than when the traditional stereotype was reinforced.
- Stereotype retraining had no effect on accuracy in the problem solving condition as women retrained with the counterstereotype performed comparably to women who reinforced the stereotype
- Although women who thought their maths ability was being assessed did not under perform those in the problem solving condition when the stereotype was reinforced, they did outperform their problem solving counterparts when they were retrained to associate maths with things women are good at.  
*Mediated moderation analyses*:
- In the first analysis training type, task diagnosticity and the interaction term was entered in to a model predicting working memory
- Consistent with the ANOVA results described above, only the interaction was significant
- A parallel analysis on maths test accuracy yielded the same interaction pattern
- A final regression analysis revealed that when working memory was added to the second model, it was a significant predictor of maths test accuracy, and the interaction predicting test performance became non-significant
- A Sobel test testing for the indirect pathway was significant
- These results are consistent with the hypothesis that counterstereotype retraining can increase women's performance under stereotype threat because it increases their working memory capacity.  
*Supplementary Analyses*:
- It is notable that the effect of our diagnosticity manipulation on working memory and performance was more of a performance lift effect for those trained with a counterstereotype than a performance impairment effect for those reinforced with the stereotype. 
The lack of clear impairment due to threat could be due to the fact that our sample was comprised of women of all levels of maths identification, where prior research suggests that stereotype threat effects should be most pronounced among those who most value or most identify with the domain
- Consistent with this assumption, within-cell correlations revealed that among women taking the ‘diagnostic maths test’, those who received counterstereotype retraining had a significant positive relationship between an earlier mass survey measure of maths identification and working memory but this pattern was significantly reversed among those trained to reinforce the stereotype
- There was no relationship among these variables for women 'taking a problem solving task'.
- Parallel analyses with maths performance revealed that pre-test maths identification was generally positive realted to maths performance for all conditions and was not significantly different between conditions.
- Given that measures of maths identification are likely to be conflated with past maths experience, the domain-general measure of working memory capacity might have been a more sensitive way to detect how identification with the domain exposes one to stereotype threat.  


### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [ ] Yes
   - [x] No
   - [ ] Can’t tell
   
### Are there any obvious shortcomings in the reporting of the data?

- [ ] Yes (please specify)
- [x] No

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?
*This excludes variables just used to describe the sample.*

- [x] Yes (please specify)
- [ ] No

### Do the authors state where the full original data are stored?

- [ ] Yes (please specify)
- [x] No

### What do the author(s) conclude about the findings of the study?
*Please give details and refer to page numbers in the report of the study where necessary.*

- [ ] Details

**Study 1**:  
Results from Study 1 provide evidence that retraining maths attitudes affects women's motivation for choosing to work on maths. Women instructed to indirectly yet repeatedly associate maths-related constructs with things they like chose to spend more time solving maths problems compared to women trained to associate maths with things they dislike. Whereas Kawakami et al. showed motivation effects immediately following their approach retraining manipulation, we were able to confirm that attitude associative training effects persist even with a 24 hour delay, thus minimizing a simple priming explanation. We found no evidence that retraining maths attitudes improved women's working memory capacity or maths performance under standard stereotype threat conditions. As we have argued, having a positive association with maths might not improve complex cognitive processing.  


**Study 4**:



## Quality of the study - Reporting 

### Is the context of the study adequately described?
*Consider your answer to questions: Why was this study done at this point in time, in those contexts and with those people or institutions? (Section B question 2) Was the study informed by or linked to an existing body of empirical and/or theoretical research? (Section B question 3) Which of the following groups were consulted in working out the aims to be addressed in the study? (Section B question 4) Do the authors report how the study was funded? (Section B question 5) When was the study carried out? (Section B question 6)*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Are the aims of the study clearly reported?
*Consider your answer to questions: What are the broad aims of the study? (Section B question 1) What are the study research questions and/or hypotheses? (Section C question 10)*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?
*Consider your answer to all questions in Methods on ‘Sampling Strategy’, ‘Recruitment and Consent’, and ‘Actual Sample’.*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods used in the study to collect data?
*Consider your answer to the following questions in Section I: Which methods were used to collect the data? Details of data collection methods or tools Who collected the data? Do the authors describe the setting where the data were collected? Are there other important features of the data collection procedures?*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods of data analysis?
*Consider your answer to the following questions in Section J: Which methods were used to analyse the data? What statistical methods, if any, were used in the analysis? Who carried out the data analysis?*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is the study replicable from this report?

- [ ] Yes (please specify)
- [ ] No (please specify)

### Do the authors avoid selective reporting bias?
*(e.g. do they report on all variables they aimed to study as specified in their aims/research questions?)*

- [ ] Yes (please specify)
- [ ] No (please specify)

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?
*Consider consent, funding, privacy, etc.*

- [ ] Yes, some concerns (please specify)
- [ ] No concerns

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [ ] Yes, a lot (please specify)
- [ ] Yes, a little (please specify)
- [ ] No (please specify)

### Is there sufficient justification for why the study was done the way it was?

- [ ] Yes (please specify)
- [ ] No (please specify)

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [ ] Yes (please specify)
- [ ] No (please specify)

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?
*e.g. (1) In an evaluation, was the process by which participants were allocated to or otherwise received the factor being evaluated concealed and not predictable in advance? If not, were sufficient substitute procedures employed with adequate rigour to rule out any alternative explanations of the findings which arise as a result? e.g. (2) Was the attrition rate low and if applicable similar between different groups?*

- [ ] A lot (please specify)
- [ ] A little (please specify)
- [ ] Not at all (please specify)

### How generalisable are the study results?

- [ ] Details

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?
*In some studies it is difficult to distinguish between the findings of the study and the conclusions. In those cases please code the trustworthiness of this combined results/conclusion.** Please remember to complete the weight of evidence questions B-D which are in your review specific data extraction guidelines. ***

- [ ] High trustworthiness (please specify)
- [ ] Medium trustworthiness (please specify)
- [ ] Low trustworthiness (please specify)

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [ ] Not applicable (results and conclusions inseparable)
- [ ] High trustworthiness
- [ ] Medium trustworthiness
- [ ] Low trustworthiness
    

# @wellsNewcastleottawaScaleNOS2014

## **CASE CONTROL STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Exposure categories. A maximum of two stars can be given for Comparability.

## Selection

### Is the case definition adequate?
   - a) yes, with independent validation 
   - b) yes, e.g., record linkage or based on self reports
   - c) no description

### Representativeness of the cases
   - a) consecutive or obviously representative series of cases *
   - b) potential for selection biases or not stated

### Selection of Controls
   - a) community controls *
   - b) hospital controls
   - c) no description

### Definition of Controls
   - a) no history of disease (endpoint) *
   - b) no description of source

## Comparability

### Comparability of cases and controls on the basis of the design or analysis
   - a) study controls for _______________ (Select the most important factor.) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Exposure

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview where blind to case/control status *
   - c) interview not blinded to case/control status
   - d) written self report or medical record only
   - e) no description

### Same method of ascertainment for cases and controls
   - a) yes *
   - b) no

### Non-Response rate
   - a) same rate for both groups *
   - b) non respondents described
   - c) rate different and no designation

---

## **COHORT STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Outcome categories. A maximum of two stars can be given for Comparability.

## Selection

### Representativeness of the exposed cohort
   - a) truly representative of the average _______________ (describe) in the community *
   - b) somewhat representative of the average ______________ in the community *
   - c) selected group of users, e.g., nurses, volunteers
   - d) no description of the derivation of the cohort

### Selection of the non exposed cohort
   - a) drawn from the same community as the exposed cohort *
   - b) drawn from a different source
   - c) no description of the derivation of the non exposed cohort

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview *
   - c) written self report
   - d) no description

### Demonstration that outcome of interest was not present at start of study
   - a) yes *
   - b) no

## Comparability

### Comparability of cohorts on the basis of the design or analysis
   - a) study controls for _____________ (select the most important factor) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Outcome

### Assessment of outcome
   - a) independent blind assessment *
   - b) record linkage *
   - c) self report
   - d) no description

### Was follow-up long enough for outcomes to occur
   - a) yes (select an adequate follow up period for outcome of interest) *
   - b) no

### Adequacy of follow up of cohorts
   - a) complete follow up - all subjects accounted for *
   - b) subjects lost to follow up unlikely to introduce bias - small number lost - > ____ % (select an adequate %) follow up, or description provided of those lost) *
   - c) follow up rate < ____% (select an adequate %) and no description of those lost
   - d) no statement


# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

### Did the review address a clearly focussed issue?
- Was there enough information on:
  - The population studied
  - The intervention given
  - The outcomes considered
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the authors look for the appropriate sort of papers?
- The ‘best sort of studies’ would:
  - Address the review’s question
  - Have an appropriate study design
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## ARE THE RESULTS OF THIS REVIEW VALID?

### Do you think the important, relevant studies were included?
- Look for:
  - Which bibliographic databases were used
  - Follow up from reference lists
  - Personal contact with experts
  - Search for unpublished as well as published studies
  - Search for non-English language studies
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the review’s authors do enough to assess the quality of the included studies?
- The authors need to consider the rigour of the studies they have identified. Lack of rigour may affect the studies results.
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### If the results of the review have been combined, was it reasonable to do so?
- Consider whether:
  - The results were similar from study to study
  - The results of all the included studies are clearly displayed
  - The results of the different studies are similar
  - The reasons for any variations are discussed
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WHAT ARE THE RESULTS?

### What is the overall result of the review?
- Consider:
  - If you are clear about the review’s ‘bottom line’ results
  - What these are (numerically if appropriate)
  - How were the results expressed (NNT, odds ratio, etc)

### How precise are the results?
- Are the results presented with confidence intervals?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WILL THE RESULTS HELP LOCALLY?

### Can the results be applied to the local population?
- Consider whether:
  - The patients covered by the review could be sufficiently different from your population to cause concern
  - Your local setting is likely to differ much from that of the review
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Were all important outcomes considered?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Are the benefits worth the harms and costs?
- Even if this is not addressed by the review, what do you think?
- [ ] Yes
- [ ] Can’t tell
- [ ] No


# References


::: {#refs custom-style="Bibliography"}
:::
