---
title             : "@hutterWomenStereotypeThreat2019"
shorttitle        : "@hutterWomenStereotypeThreat2019"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h3.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

# @eppi-centreReviewGuidelinesExtracting2003 & @criticalappraisalskillsprogrammeCASPSystematicReview2018

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [x] Not applicable (whole study is focus of data extraction)  
- [ ] Specific focus of this data extraction (please specify)  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?
*Please write in authors' declaration if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Stereotype threat 
- Stereotype threat and working memory
- Stereotype threat and mere effort account  

### Do authors report how the study was funded?

- [ ] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [x] Not stated/unclear (please specify)  

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?


- Our interest lies in response to differing maths problem types when experiencing stereotype threat and particularly in the strength of the relation between experiencing stereotype threat and maths performance as a function of motivation and overproduction of prepotent responses, because motivation and prepotent overproduction are central to the mere effort account.  
- We compared the overproduction of prepotent responses (mere effort account) with the inhibition of prepotent responses (working memory inference perspective) in an effort to explain stereotype threat effects
- In Experiment 1, we examined whether activation of a negative performance self-applicable stereotype motivates participants to undermine the stereotype. Although stereotype threat motivates performance on all question types, the activated prepotent response might lead to the selection of more prepotent solve questions to answer than non-prepotent comparison questions.
- In Experiment 2, we turned to the overproduction of prepotent responding versus the inhibition of prepotent responding, following stereotype threat activation of the motivated preference goal. We tested whether participants with superior inhibition ability are better placed to inhibit prepotent solve responding when tacking comparison questions. Positive results would lend credence to the working memory inference perspective, and negative results to the mere effort account.  

### What is/are the population focus/foci of the study?

- Individuals under maths stereotype threat.  

### What is the relevant age group? 

- [ ] Not applicate (focus not learners)  
- [ ] 0 - 4  
- [ ] 5 - 10  
- [ ] 11 - 16  
- [ ] 17 - 20  
- [ ] 21 and over  
- [ ] Not stated/unclear  

### What is the sex of the population focus/foci?

- [ ] Not applicate (focus not learners)  
- [x] Female only  
- [ ] Male only  
- [ ] Mixed sex  
- [ ] Not stated/unclear  

### What is/are the educational setting(s) of the study?

- [ ] Community centre  
- [ ] Correctional institution  
- [ ] Government department  
- [x] Higher education institution  
- [ ] Home  
- [ ] Independent school  
- [ ] Local education authority  
- [ ] Nursery school  
- [ ] Other early years setting  
- [ ] Post-compulsory education institution  
- [ ] Primary school  
- [ ] Residential school  
- [ ] Secondary school  
- [ ] Special needs school  
- [ ] Workplace  
- [ ] Other educational setting  

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)  
- [ ] Not stated/unclear (please specify)  

- United Kingdom


### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

### What are the study reserach questions and/or hypotheses?
*Research questions or hypotheses operationalise the aims of the study. Please write in authors' description if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Experiment 1**:
- We hypothesized that, if stereotype threat motivates disapproval of negative stereotype, leading test takers to apply a prepotent solve approach (in accord with the mere effort account), participants would manifest a greater selection of prepotent solve questions than non-prepotent comparison questions to answer.
- Additionally, we aimed to rule out that increased motivation following stereotype threat is not task-specific, by using as a covariate the inclusion of an (indirect) measure of maths motivation.
- We did not expect indirect maths motivation to be affected following stereotype threat, if motivation were task-specific, as per the mere effort account.
- We also examined the roles of female and maths identifications, given that stereotype threat acts as a stressor in performance-based contexts, as per the working memory inference perspective.  

**Experiment 2**:  
- According to the working memory inference perspective, inhibitory ability moderates stereotype threat effects for question type. If stereotype threat-based performance reduction results from failure to inhibit prepotent responding when working on non-prepotent tasks, then superior ability in suppressing prepotent (solve) responses will protect threatened females' maths performance against unwanted solve responding when answering comparison questions. Superior inhibitors will be more able to inhibit the solve response and apply the correct comparison response, overcoming stereotype threat effects and performing to their full mathematical ability. Performance on solve questions will be unaffected by inhibitory ability, as the prepotent solve response is inappropriate for these questions 
- Furthermore, given that it is the experience of stereotype threat that potentiates prepotent responses, the above discussed pattern will not emerge in the control condition. In contrast, according to the mere effort account, performance reduction on non-prepotent tasks derives form the overproduction of prepotent responses. This implies that superior inhibition ability will not protect comparison type question performance, particularly when experiencing stereotype threat.
- Finally, we predicted that stereotype threat would lead to performance boost for solve questions (where prepotent responses are correct) and performance decrement for comparison questions (where prepotent responses are incorrect), relative to no-stereotype threat. The working memory inference perspective and mere effort account do not diverge on this last prediction: The two theoretical statements only diverge on the mechanisms likely to be involved (prepotent inhibition vs. overproduction of prepotent responses, respectively).


## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Experiment 1**:  
- number of solve questions -> b
- number of comparison questions selected on the maths question select task -> b
- maths motivation -> b
- Self-Esteem scale to measure gender identification -> b
- Maths identification -> b
- Stereotype threat manipulation -> b
- Demographic information -> a

**Experiment 2**:  
- demographic information
- Stroop task performance
- maths test performance
- "several measures"



### Study timing
*Please indicate all that apply and give further details where possible.*

*If the study examines one or more samples, but each at only one point in time it is cross-sectional.*  
*If the study examines the same samples, but as they have changed over time, it is retrospective, provided that the interest is in starting at one timepoint and looking backwards over time.*  
*If the study examines the same samples as they have changed over time and if data are collected forward over time, it is prospective provided that the interest is in starting at one timepoint and looking forward in time.*  

- [x] Cross-sectional  
- [ ] Retrospective  
- [ ] Prospective  
- [ ] Not stated/unclear (please specify)  

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?
*If at least one of the outcome variables is measured both before and after the intervention, please use the before and after category.*

- [ ] Not applicable (not an evaluation)  
- [ ] Before and after  
- [x] Only after  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  

**Experiment 1**:  
- after

**Experiment 2**:  
- before and after  


## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.
*Please give further details where possible.*

- [ ] Not applicable (not more than one group)  
- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  
- [ ] No prospective allocation but use of pre-existing differences to create comparison groups (e.g. receiving different interventions, or characterised by different levels of a variable such as social class)  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  

### How do the groups differ?

- [ ] Not applicable (not more than one group)  
- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Experiment 1**:  
- Stereotype threat vs. no stereotype threat  

**Experiment 2**:  
- 2 (Stereotype threat vs no stereotype threat) x 2 (question type: solve vs comparison).


### Number of groups
*For instance, in studies in which comparisons are made between groups, this may be the number of groups into which the dataset is divided for analysis (e.g. social class, or form size), or the number of groups allocated to, or receiving, an intervention.*

- [ ] Not applicable (not more than one group)  
- [ ] One  
- [x] Two  
- [ ] Three  
- [ ] Four or more (please specify)  
- [ ] Other/unclear (please specify)  

**Experiment 1**:  
- two

**Experiment 2**:  
- four 

### Was the assignment of participants to interventions randomised?

- [ ] Not applicable (not more than one group)  
- [ ] Not applicate (no prospective allocation)  
- [x] Random  
- [ ] Quasi-random  
- [ ] Non-random  
- [ ] Not stated/unclear (please specify)  

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?
*Bias can be introduced, consciously or otherwise, if the allocation of pupils or classes or schools to a programme or intervention is made in the knowledge of key characteristics of those allocated. For example: children with more serious reading difficulty might be seen as in greater need and might be more likely to be allocated to the 'new' programme, or the opposite might happen. Either would introduce bias.*

- [ ] Not applicable (not more than one group)  
- [ ] Not applicable (no prospective allocation)  
- [x] Yes (please specify)  
- [ ] No (please specify)  
- [ ] Not stated/unclear (please specify)  

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [x] Yes
- [ ] No
- [ ] Can’t tell

### Study design summary 
*In addition to answering the questions in this section, describe the study design in your own words. You may want to draw upon and elaborate the answers you have already given.*

**Experiment 1**:  
1. Female experimenter escorted participants individualls into the laboratory
2. Pen-and-paper non-calculator and non-assessed maths test
3. After random assignment to stereotype threat or no stereotype threat condition, participants read instructions (these included stereotype threat manipulation)
4. Participants completed as many of five questions as possible, the questions were not assessed or performance recorded, serving as a method to ensure the face validity of the question selection task to follow.
5. Maths questions
6. On completion of the maths task, participants undertook a question selection task and received instructions to choose a total of any five questions to answer (ostensibly) out of 10
7. We instructed participants how to complete the selection task
8. Following question type selection, participants completed a stereotype threat manipulation check, as well as measures of maths motivation, gender identification, and maths identification.  

**Experiment 2**:  
1. Female experimenter escorted participants individually into the laboratory
2. 5-min Stroop task
3. 5-min break
4. given maths test and asked to read carefully (here stereotype threat manipulation, similar to Experiment 1)
5. participants completed as many as possible of five 3-mark comparison questions or five 3-mark solve questions (depending on condition)
- participants were given an 18 min time constraint during the maths task
6. participants completed several measures
7. asme stereotype threat manipulation checks as in Experiment 1  



## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 
*Please write in authors' description. If authors do not specify please indicate reviewers' interpretation.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- We tested only women because our chosen stereotyep threat manipulation has been shown previously to only affect women
- Our chosen population and performance stereotype mirrored those of Jamieson and Harkins (2009) and Seitchik and Harkins (2015): women and the stereotype 'women are poorer at maths'. 

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?
*e.g. telephone directory, electoral register, postcode, school listing, etc. There may be two stages – e.g. first sampling schools and then classes or pupils within them.*

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Which methods does the study use to select people or groups of people (from the sampling frame)?
*e.g. selecting people at random, systematically - selecting for example every 5th person, purposively in order to reach a quota for a given characteristic.*

- [ ] Not applicable (no sampling frame)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Planned sample size
*If more than one group please give details for each group separately.*

- [x] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [ ] Not stated/unclear (please specify)


## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?
*e.g. letters of invitation, telephone contact, face-to-face contact.*

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- undergraduate students at a UK university


### Were any incentives provided to recruit people into the study?

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [x] Not stated/unclear (please specify)

### Was consent sought?
*Please comment on the quality of consent if relevant.*

- [ ] Not applicable (please specify)
- [ ] Participant consent sought
- [ ] Parental consent sought
- [ ] Other consent sought
- [ ] Consent not sought
- [x] Not stated/unclear (please specify)

### Are there any other details relevant to recruitment and consent?

- [ ] No
- [x] Yes (please specify)

**Experiment 1**:  
- The sample size was adequate for achieve power in the region of .80, based on an effect size ($d$ = 0.64) from related research (Davies et al., 2016; Jamieson & Harkins, 2009, Experiment 1)

**Experiment 2**:  
- We conducted a post-hoc power analysis via an online calculator (https://www.danielsoper.com/statcalc/calculator.aspx?id=9) to calculate power for our predictors and moderators, based on R2 = .06, probability level = .05, and sample size 165 (Soper, 2018). The analysis confirmed that power was adequate (observed statistical power = .77). A further calculation for our interaction variables, based on R2 = .19, probability level = .05, and sample size 165, confirmed that this sample size was sufficient (observed statistical power = .98).   

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?
*If more than one group is being compared please give numbers for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1**:  
- We tested an opportunity sample of 103 psychology female undergraduates at a UK university, ages between 18 and 22 years (M = 19.36, SD = 1.07).


**Experiment 2**:  
- We recruited an opportunity sample of 165 female undergraduates in a UK university aged from 18 to 25 years (M = 20.50, SD = 1.61)  


### What is the proportion of those selected for the study who actually participated in the study? 
*Please specify numbers and percentages if possible.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Which country/countries are the individuals in the actual sample from?
*If UK, please distinguish between England, Scotland, N. Ireland, and Wales if possible. If from different countries, please give numbers for each. If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- All participants identified as British Caucasian  



### What ages are covered by the actual sample?
*Please give the numbers of the sample that fall within each of the given categories. If necessary, refer to a page number in the report (e.g. for a useful table). If more than one group is being compared, please describe for each group. If follow-up study, age at entry to the study.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] 0 to 4
- [ ] 5 to 10
- [ ] 11 to 16
- [x] 17 to 20
- [x] 21 and over
- [ ] Not stated/unclear (please specify)

**Experiment 1**:  
- aged between 18 and 22 years (M = 19.36, SD = 1.07)  

**Experiment 2**:  
- aged between 18 to 25 years (M = 20.5, SD = 1.61)  

### What is the socio-economic status of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is the ethnicity of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- identified as British Caucasian, with English as their first language.  

### What is known about the special educational needs of individuals within the actual sample?
*e.g. specific learning, physical, emotional, behavioural, intellectual difficulties.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Is there any other useful information about the study participants?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify no/s.)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1**:  
- The sample size was adequate to achieve power in the region of .80, absed on an effect size (d = 0.64) from related research
- All participants (1) identified as British Caucasian, with English as their first language, and (2) had achieved at least a GCSE C grade Maths.  

**Experiment 2**:  
- All participants identified as British Caucasian, with English as their first language. ALso, all participants had achieved at least a GCSE C grade Maths.


### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 
*Please specify basis for your decision.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (no sampling frame)
- [x] High (please specify)
- [ ] Medium (please specify)
- [ ] Low (please specify)
- [ ] Unclear (please specify)

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?
*If the study involves more than one group, please give drop-out rates for each group separately. If necessary, refer to a page number in the report (e.g. for a useful table).*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Not applicable (no drop outs)
- [ ] Yes (please specify)
- [ ] No

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Yes (please specify)
- [ ] No

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [ ] Details

**Experiment 1**:  
- number of solve questions -> b
- number of comparison questions selected on the maths question select task -> b
- maths motivation -> b
- Self-Esteem scale to measure gender identification -> b
- Maths identification -> b
- Stereotype threat manipulation -> b
- Demographic information -> a


**Experiment 2**:  
- Stroop task -> b
- Maths task -> b
- several measures -> b
- demographic information -> a
- stereotype threat manipulation -> b


### Which methods were used to collect the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Curriculum-based assessment
- [ ] Focus group
- [ ] Group interview
- [ ] One to one interview (face to face or by phone)
- [ ] Observation
- [ ] Self-completion questionnaire
- [ ] Self-completion report or diary
- [ ] Exams
- [ ] Clinical test
- [ ] Practical test
- [ ] Psychological test
- [ ] Hypothetical scenario including vignettes
- [ ] School/college records (e.g. attendance records etc)
- [ ] Secondary data such as publicly available statistics
- [ ] Other documentation
- [ ] Not stated/unclear (please specify)

### Details of data collection methods or tool(s).
*Please provide details including names for all tools used to collect data and examples of any questions/items given. Also please state whether source is cited in the report.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1**:  
- Stereotype threat manipulation adapted from Steele & Aronson, 199)
- Questions from www.aqa.org.uk
- Schmader's (2002) adapted Self-Esteem Scale to measure gender identification
- Stereotype threat manipulation checks (Jamieson & Harkins, 2007, 2009).

**Experiment 2**:  
- Stroop task
- five 3-mark comparison or solve questions from Davies et al. (2016, Experiment 2).
- several measures and manipulation checks -> see Experiment 1



### Who collected the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Researcher
- [ ] Head teacher/Senior management
- [ ] Teaching or other staff
- [ ] Parents
- [ ] Pupils/students
- [ ] Governors
- [ ] LEA/Government officials
- [ ] Other education practitioner
- [ ] Other (please specify)
- [ ] Not stated/unclear

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?
*e.g. test-retest methods (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?
*e.g. mention previous validation of tools, published version of tools, involvement of target population in development of tools. (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?
*Not applicable – e.g. analysis of existing data, qualitative study. No – e.g. assessment of reading progress for dyslexic pupils done by teacher who provided intervention. Yes – e.g. researcher assessing pupil knowledge of drugs - unaware of pupil allocation.*

- [ ] Not applicable (please say why)
- [ ] Yes (please specify)
- [ ] No (please specify)

### Where were the data collected?
*e.g. school, home.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Unclear/not stated (please specify)

- laboratory  

### Are there other important features of data collection?
*e.g. use of video or audio tape; ethical issues such as confidentiality etc.*

- [ ] Details

## Methods - Data analysis

### Which methods were used to analyse the data?
*Please give details e.g. for in-depth interviews, how were the data handled? Details of statistical analysis can be given next.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)


### Which statistical methods, if any, were used in the analysis?

- [ ] Details

**Experiment 1**:  
*Manipulation Check*: 
- means calculation and SD
- t-test  
*Question selection*:
- we subjected maths question selection to a single-factor (condition) ANCOVA, with indirect maths motivation, gender identification, and maths identification as covariates
- Before analysis, we calculated for each participant the number of solve questions minus the number of comparison questions selected.

**Experiment 2**:  
- RT difference between congruent and incongruent accurate responses on the Stroop test as a measure of inhibitory ability
- median reaction times (RT) 
- computed a difference score by subtracting the median reaction time on congruent trails from the median reaction time on congruent trails.  
*Manipulation check*:
- see Experiment 1  
*Inhibitory ability*: 
- moderated regression to examine inhibitory ability as a potential moderator of maths score
- computed an interaction variable by contrast coding condition as -1 and +1 (stereotype threat vs. no stereotype threat)
- computed the centred continuous inhibitory ability scores for each participant
- Multiplied condition by question type, condition by inhibitory ability, question type by inhibitory ability, and condition by question type by inhibitory ability to create the interaction terms
- Entered interaction terms into a multiple regression on a second step following the insertion of condition, question type, and inhibitory ability independently at step 1, with the centred continuous maths scores for each participant as the dependent (outcome) variable. 
- We broke down the Condition x Question Type interaction by conducting a simple regressions separately for each level of condition
- We used simple regressions to break the interaction (Condition x Inhibitory Ability) down.




### What rationale do the authors give for the methods of analysis for the study?
*e.g. for their methods of sampling, data collection, or analysis.*

- [ ] Details

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.
*'Intention to intervene' means that data were analysed on the basis of the original number of participants as recruited into the different groups. 'Intervention received' means data were analysed on the basis of the number of participants actually receiving the intervention.*

- [ ] Not applicable (not an evaluation study with prospective allocation)
- [ ] 'Intention to intervene'
- [ ] 'Intervention received'
- [ ] Not stated/unclear (please specify)

### Do the authors describe any ways they have addressed the reliability of data analysis?
*e.g. using more than one researcher to analyse data, looking for negative cases.*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of data analysis?
*e.g. internal or external consistency; checking results with participants.*

- [ ] Details

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [ ] Details

### Please describe any other important features of the analysis.

- [ ] Details

### Please comment on any other analytic or statistical issues if relevant.

- [ ] Details

## Results and Conclusions

### How are the results of the study presented?
*e.g. as quotations/figures within text, in tables, appendices.*

- [ ] Details

**Experiment 1**:  
- in text
- table 

**Experiment 2**:  
- table 
- figures
- in text



### What are the results of the study as reported by authors?
*Please give details and refer to page numbers in the report(s) of the study where necessary (e.g. for key tables).*

- [ ] Details

**Experiment 1**:  
*Manipulation check*:
- Participants in the stereotype threat condition reported that gender differences existed on the test to a greater extent than those in the no-stereotype threat condition
- Participants in the stereotype threat condition reported that males performed better than females than those in the no-stereotype threat condition at a marginal level
- Participants in the stereotype threat condition were therefore aware of, but did not necessarily believe, the negative stereotype.  
*Question selection*:
- As hypothesized, stereotype threat participants chose to answer solve questions more often than no-stereotype threat participants
- As anticipated, the maths motivation covariate measure did not significantly explain the variance in question type selected
- Gender identification was not significant, whereas the effect of maths identification on question type selected was marginal
- See Table 1 for correlations and Appendix S1 for further moderators analyses: motivation, gender identity, maths identity.  

**Experiment 2**:  
*Manipulation check*:
- Participants in the stereotype threat condition reported that gender differences existed to a greater extent compared to those in the no-stereotype threat condition
- Participants in the two conditions did not differ significantly in their belief that males performed better than females at the task
- Participants in the stereotype threat condition were aware of the negative groups stereotype, but did not necessarily believe it.  
*Inhibitory ability*:
- At step 1, the condition main effect was not significant
- The question type main effect was significant: Participants performed better on the solve than comparison questions
- the inhibitory ability main effect was significant
- High (compared to low) inhibitors performed better on the maths test
- At step 2, entering the interaction terms explained a significant increase in variance in maths performance over step 1
- The Condition x Question Type interaction was significant 
- In the no-stereotype threat, we observed no effect of question type on maths performance
- In the stereotype threat, we found a significant effect of question type on maths performance
- Participants subject to stereotype threat performed better on the solve than comparison questions
- For comparison questions, participants in the stereotype threat underperformed relative to those in no-stereotype threat
- For solve questions, no significant differences in maths performance emerged across stereotype threat or no-stereotype threat
- These patterns are consistent with the mere effort account.
- The Condition x Question Type x Inhibitory Ability interaction in the main analysis was not significant
- The Condition x Question Type interaction was unmoderated by inhibitory ability, suggesting no advantage for superior inhibitory ability in attempting to inhibit prepotent solve responses in response to comparison questions, following stereotype threat
- This finding runs contrary to the working memory inference perspective
- In the Condition x Inhibitory Ability interaction was significant
- There was a significant effect of inhibitory ability on maths performance, whereas, in the non-stereotype threat condition, there was no effect of inhibitory ability on maths performance
- Stereotype threat results in low (vs. high) inhibitors under performing
- The Question type x Inhibitory Ability interaction was not significant 
- See Appendix S1 for further moderators analyses: motivation, gender identity, maths identity.


### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [x] Yes
   - [ ] No
   - [ ] Can’t tell
   
### Are there any obvious shortcomings in the reporting of the data?

- [ ] Yes (please specify)
- [x] No

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?
*This excludes variables just used to describe the sample.*

- [x] Yes (please specify)
- [ ] No

### Do the authors state where the full original data are stored?

- [ ] Yes (please specify)
- [x] No

### What do the author(s) conclude about the findings of the study?
*Please give details and refer to page numbers in the report of the study where necessary.*

- [ ] Details

**Experiment 1**:  
We found evidence for task-specific motivation to disprove a negative women's maths performance stereotype following activation of stereotype threat. According to the mere effort account, performance motivation activates fist, ahead of prepotent responding. Assuming that performance motivation is intrinsically tied to ask performance on a given task, it cannot easily be measured independently.
Therefore, stereotype threat activated and task-specific motivation is unlike other forms of motivation. Our adapted Forbes and Schmader's (2010) maths motivation task selection task allowed the investigation of mere effort account's hypothesized motivational mechanisms independently of stereotype threat effects, overcoming the task-specificity problem.   
We observed evidence of greater solve type maths question selection following stereotype threat. Also, stereotype threat did not affect an indirect measure of maths motivation for solve and comparison questions selected, indicating that motivation to disprove the negative stereotype cannot be indexed via other forms of motivational measure. Additionally, we did not find an effect of gender identification, whereas maths identification reached marginality. This finding is inconsistent with Schmader and Johns' (2003) proposal that stereotype threat as a stressor poses a threat to social identity.  
Together, the findings support (1) Jamieson and Harkins' (2007) proposition that people become motivated to undermine a negative performance stereotype when threatened by that stereotype, and (2) stereotype threat induces task-specific (as opposed to indirect) motivation.  


**Experiment 2**:  
The results were consistent with the mere effort account. Participants with low (vs. high) inhibitory ability showed greater overall test performance decrements following stereotype threat. Therefore, inhibitory ability acted as a buffer to protect high inhibitors against the detrimental consequences of stereotype threat. Superior inhibitory ability did not, however, protect threatened females’ maths performance specifically on comparison questions, as would be expected if prepotent responses were inhibited following stereotype threat (working memory interference perspective).  
The observed performance effects are broadly consistent with previous findings testing the mere effort account.  


**General Discussion**:
The results suggest that task-based motivation increases following stereotype threat, in support of the mere effort account (Jamieson & Harkins, 2007, 2009, 2012). Stereotype threat motivates test takers to perform well (on solve and comparison questions), undermining the negative performance stereotype through the facilitation of solve responding. Furthermore, the results are inconsistent with the proposition that superior inhibitory ability advantages non-prepotent question performance, a putative consequence of the working memory interference perspective (Schmader et al., 2008).




## Quality of the study - Reporting 

### Is the context of the study adequately described?
*Consider your answer to questions: Why was this study done at this point in time, in those contexts and with those people or institutions? (Section B question 2) Was the study informed by or linked to an existing body of empirical and/or theoretical research? (Section B question 3) Which of the following groups were consulted in working out the aims to be addressed in the study? (Section B question 4) Do the authors report how the study was funded? (Section B question 5) When was the study carried out? (Section B question 6)*

- [x] Yes (please specify)
- [ ] No (please specify)

### Are the aims of the study clearly reported?
*Consider your answer to questions: What are the broad aims of the study? (Section B question 1) What are the study research questions and/or hypotheses? (Section C question 10)*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?
*Consider your answer to all questions in Methods on ‘Sampling Strategy’, ‘Recruitment and Consent’, and ‘Actual Sample’.*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods used in the study to collect data?
*Consider your answer to the following questions in Section I: Which methods were used to collect the data? Details of data collection methods or tools Who collected the data? Do the authors describe the setting where the data were collected? Are there other important features of the data collection procedures?*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods of data analysis?
*Consider your answer to the following questions in Section J: Which methods were used to analyse the data? What statistical methods, if any, were used in the analysis? Who carried out the data analysis?*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is the study replicable from this report?

- [x] Yes (please specify)
- [ ] No (please specify)

### Do the authors avoid selective reporting bias?
*(e.g. do they report on all variables they aimed to study as specified in their aims/research questions?)*

- [x] Yes (please specify)
- [ ] No (please specify)

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?
*Consider consent, funding, privacy, etc.*

- [x] Yes, some concerns (please specify)
- [ ] No concerns

- No mention of consent or ethical approval or funding.  

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [ ] Yes, a lot (please specify)
- [x] Yes, a little (please specify)
- [ ] No (please specify)

### Is there sufficient justification for why the study was done the way it was?

- [x] Yes (please specify)
- [x] No (please specify)

- No explanation why the stereotype threat manipulation was not swapped out for a stronger one in experiment 2, after the researchers found that the manipulation was not strong in Experiment 1.  

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [x] Yes (please specify)
- [ ] No (please specify)

- Was based on previous research  

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?
*e.g. (1) In an evaluation, was the process by which participants were allocated to or otherwise received the factor being evaluated concealed and not predictable in advance? If not, were sufficient substitute procedures employed with adequate rigour to rule out any alternative explanations of the findings which arise as a result? e.g. (2) Was the attrition rate low and if applicable similar between different groups?*

- [ ] A lot (please specify)
- [ ] A little (please specify)
- [x] Not at all (please specify)

- Manipulation check revealed that the stereotype threat manipulation was not strong and might not have been successful. The authors address this by stating that the question could've asked for a personal believe rather than be a manipulation check, however if the manipulation did not work, the results of the study are not relevant to the topic of stereotype threat.  

### How generalisable are the study results?

- [ ] Details

- Unclear, everything was good in terms of generalisability but the fact that it's unclear whether the manipulation did indeed work, makes the results not generalisable.  

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?
*In some studies it is difficult to distinguish between the findings of the study and the conclusions. In those cases please code the trustworthiness of this combined results/conclusion.** Please remember to complete the weight of evidence questions B-D which are in your review specific data extraction guidelines. ***

- [ ] High trustworthiness (please specify)
- [ ] Medium trustworthiness (please specify)
- [x] Low trustworthiness (please specify)

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [ ] Not applicable (results and conclusions inseparable)
- [x] High trustworthiness
- [ ] Medium trustworthiness
- [ ] Low trustworthiness
    

# @wellsNewcastleottawaScaleNOS2014

## **CASE CONTROL STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Exposure categories. A maximum of two stars can be given for Comparability.

## Selection

### Is the case definition adequate?
   - a) yes, with independent validation 
   - b) yes, e.g., record linkage or based on self reports
   - c) no description

### Representativeness of the cases
   - a) consecutive or obviously representative series of cases *
   - b) potential for selection biases or not stated

### Selection of Controls
   - a) community controls *
   - b) hospital controls
   - c) no description

### Definition of Controls
   - a) no history of disease (endpoint) *
   - b) no description of source

## Comparability

### Comparability of cases and controls on the basis of the design or analysis
   - a) study controls for _______________ (Select the most important factor.) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Exposure

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview where blind to case/control status *
   - c) interview not blinded to case/control status
   - d) written self report or medical record only
   - e) no description

### Same method of ascertainment for cases and controls
   - a) yes *
   - b) no

### Non-Response rate
   - a) same rate for both groups *
   - b) non respondents described
   - c) rate different and no designation

---

## **COHORT STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Outcome categories. A maximum of two stars can be given for Comparability.

## Selection

### Representativeness of the exposed cohort
   - a) truly representative of the average _______________ (describe) in the community *
   - b) somewhat representative of the average ______________ in the community *
   - c) selected group of users, e.g., nurses, volunteers
   - d) no description of the derivation of the cohort

### Selection of the non exposed cohort
   - a) drawn from the same community as the exposed cohort *
   - b) drawn from a different source
   - c) no description of the derivation of the non exposed cohort

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview *
   - c) written self report
   - d) no description

### Demonstration that outcome of interest was not present at start of study
   - a) yes *
   - b) no

## Comparability

### Comparability of cohorts on the basis of the design or analysis
   - a) study controls for _____________ (select the most important factor) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Outcome

### Assessment of outcome
   - a) independent blind assessment *
   - b) record linkage *
   - c) self report
   - d) no description

### Was follow-up long enough for outcomes to occur
   - a) yes (select an adequate follow up period for outcome of interest) *
   - b) no

### Adequacy of follow up of cohorts
   - a) complete follow up - all subjects accounted for *
   - b) subjects lost to follow up unlikely to introduce bias - small number lost - > ____ % (select an adequate %) follow up, or description provided of those lost) *
   - c) follow up rate < ____% (select an adequate %) and no description of those lost
   - d) no statement


# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

### Did the review address a clearly focussed issue?
- Was there enough information on:
  - The population studied
  - The intervention given
  - The outcomes considered
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the authors look for the appropriate sort of papers?
- The ‘best sort of studies’ would:
  - Address the review’s question
  - Have an appropriate study design
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## ARE THE RESULTS OF THIS REVIEW VALID?

### Do you think the important, relevant studies were included?
- Look for:
  - Which bibliographic databases were used
  - Follow up from reference lists
  - Personal contact with experts
  - Search for unpublished as well as published studies
  - Search for non-English language studies
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the review’s authors do enough to assess the quality of the included studies?
- The authors need to consider the rigour of the studies they have identified. Lack of rigour may affect the studies results.
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### If the results of the review have been combined, was it reasonable to do so?
- Consider whether:
  - The results were similar from study to study
  - The results of all the included studies are clearly displayed
  - The results of the different studies are similar
  - The reasons for any variations are discussed
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WHAT ARE THE RESULTS?

### What is the overall result of the review?
- Consider:
  - If you are clear about the review’s ‘bottom line’ results
  - What these are (numerically if appropriate)
  - How were the results expressed (NNT, odds ratio, etc)

### How precise are the results?
- Are the results presented with confidence intervals?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WILL THE RESULTS HELP LOCALLY?

### Can the results be applied to the local population?
- Consider whether:
  - The patients covered by the review could be sufficiently different from your population to cause concern
  - Your local setting is likely to differ much from that of the review
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Were all important outcomes considered?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Are the benefits worth the harms and costs?
- Even if this is not addressed by the review, what do you think?
- [ ] Yes
- [ ] Can’t tell
- [ ] No


# References


::: {#refs custom-style="Bibliography"}
:::
