---
title             : "@schmaderMetacognitivePerspectiveCognitive2009"
shorttitle        : "@schmaderMetacognitivePerspectiveCognitive2009"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h3.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

# @eppi-centreReviewGuidelinesExtracting2003 & @criticalappraisalskillsprogrammeCASPSystematicReview2018

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [ ] Not applicable (whole study is focus of data extraction)  
- [x] Specific focus of this data extraction (please specify)  

- Study 1 and 2 were used
- Study 3 excluded since it did not measure working memory directly.  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?
*Please write in authors' declaration if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Stereotype threat and its effects on working memory
- affective and cognitive processes that underlie stereotype threat effects on working memory


### Do authors report how the study was funded?

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

This research was supported by National Institute of Mental Health Grant 1R01MH071749 awarded to the first author.



## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

- Negative metacognitive interpretations of anxious arousal under stereotype threat create cognitive deficits in intellectually threatening environments.  

### What is/are the population focus/foci of the study?

- minority and white undergraduates
- women under stereotype threat
- women under stereotype threat  

### What is the relevant age group? 

- [ ] Not applicate (focus not learners)  
- [ ] 0 - 4  
- [ ] 5 - 10  
- [ ] 11 - 16  
- [ ] 17 - 20  
- [ ] 21 and over  
- [x] Not stated/unclear  

### What is the sex of the population focus/foci?

- [ ] Not applicate (focus not learners)  
- [ ] Female only  
- [ ] Male only  
- [x] Mixed sex  
- [ ] Not stated/unclear  

### What is/are the educational setting(s) of the study?

- [ ] Community centre  
- [ ] Correctional institution  
- [ ] Government department  
- [ ] Higher education institution  
- [ ] Home  
- [ ] Independent school  
- [ ] Local education authority  
- [ ] Nursery school  
- [ ] Other early years setting  
- [ ] Post-compulsory education institution  
- [ ] Primary school  
- [ ] Residential school  
- [ ] Secondary school  
- [ ] Special needs school  
- [ ] Workplace  
- [ ] Other educational setting  

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)  
- [ ] Not stated/unclear (please specify)  

- United States  

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

### What are the study reserach questions and/or hypotheses?
*Research questions or hypotheses operationalise the aims of the study. Please write in authors' description if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

Three studies tested the hypothesis that negative metacognitive interpretations of anxious arousal under stereotype threat create cognitive deficits in intellectually threatening environments

**Study 1**:  
We expected primed thoughts of confidence or doubt to interact with participants' initial experience of anxiety in the situation to predict working memory.  
When primed with doubt, anxiety should predict lower working memory, but when primed with confidence, this relationship should be mitigated.  


**Study 2**:  
We hypothesized that when the situation was described as a diagnostic test, women primed with thoughts of doubt would show a negative relationship between their anxiety levels and working memory.  
However, priming women with thoughts of confidence was expected to attenuate if not reverse this pattern.  
In contrast, when the primary task was described as a simple problem-solving exercise, we expected our manipulation of confidence and doubt to have little effect on working memory, either direcly or in interaction with initial anxiety levels.  



## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Study 1 and 2**:  
- Working memory
- Anxiety


### Study timing
*Please indicate all that apply and give further details where possible.*

*If the study examines one or more samples, but each at only one point in time it is cross-sectional.*  
*If the study examines the same samples, but as they have changed over time, it is retrospective, provided that the interest is in starting at one timepoint and looking backwards over time.*  
*If the study examines the same samples as they have changed over time and if data are collected forward over time, it is prospective provided that the interest is in starting at one timepoint and looking forward in time.*  

- [x] Cross-sectional  
- [ ] Retrospective  
- [ ] Prospective  
- [ ] Not stated/unclear (please specify)  

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?
*If at least one of the outcome variables is measured both before and after the intervention, please use the before and after category.*

- [ ] Not applicable (not an evaluation)  
- [ ] Before and after  
- [ ] Only after  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  


## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.
*Please give further details where possible.*

- [ ] Not applicable (not more than one group)  
- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  
- [ ] No prospective allocation but use of pre-existing differences to create comparison groups (e.g. receiving different interventions, or characterised by different levels of a variable such as social class)  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  

### How do the groups differ?

- [ ] Not applicable (not more than one group)  
- [x] Explicityly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Study 1**:  
- 2 (prime: confidence vs. doubt) x 2 (ehtnicity: White vs minority)  

**Study 2**:  
- 2 (task frame: diagnostic vs. neutral) x 2 (prime: confidence vs doubt).  

### Number of groups
*For instance, in studies in which comparisons are made between groups, this may be the number of groups into which the dataset is divided for analysis (e.g. social class, or form size), or the number of groups allocated to, or receiving, an intervention.*

- [ ] Not applicable (not more than one group)  
- [ ] One  
- [ ] Two  
- [ ] Three  
- [x] Four or more (please specify)  
- [ ] Other/unclear (please specify)  

### Was the assignment of participants to interventions randomised?

- [ ] Not applicable (not more than one group)  
- [ ] Not applicate (no prospective allocation)  
- [x] Random  
- [ ] Quasi-random  
- [ ] Non-random  
- [ ] Not stated/unclear (please specify)  

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?
*Bias can be introduced, consciously or otherwise, if the allocation of pupils or classes or schools to a programme or intervention is made in the knowledge of key characteristics of those allocated. For example: children with more serious reading difficulty might be seen as in greater need and might be more likely to be allocated to the 'new' programme, or the opposite might happen. Either would introduce bias.*

- [ ] Not applicable (not more than one group)  
- [ ] Not applicable (no prospective allocation)  
- [x] Yes (please specify)  
- [ ] No (please specify)  
- [ ] Not stated/unclear (please specify)  

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [x] Yes
- [ ] No
- [ ] Can’t tell

### Study design summary 
*In addition to answering the questions in this section, describe the study design in your own words. You may want to draw upon and elaborate the answers you have already given.*

**Study 1**:  
1. participants were told that they would be completing several computerized tasks, including an initial verbal analogy test, other basic memory and categorization tasks, including an initial verbal analogy test, other basic memory and categorization tasks, and finally a second verbal analogy test.
2. All participants were told that the verbal analogy tests were highly predictive of performance on a variety of intelligence tests and that some people are better able to perform these tasks than others (instructions designed to elicit stereotype threat for minorities)
3. Demographic questions, including item about their ethnicity
4. five moderately difficult verbal analogy items that were taken from the GRE and were then asked to report the level of anxiety they were experiencing at the time
5. Participants completed a modified working memory task that contained sentences designed to prime either confidence or doubt
6. followed by a questionnaire that included a manipulation check of stereotype threat
7. were informed that they were not completing the second part of the verbal analogy test
8. debriefing  

**Study 2**:  
- same as Study 1, except that the central task in this study was either described as a maths test or a problem-solving task  

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 
*Please write in authors' description. If authors do not specify please indicate reviewers' interpretation.*

- [ ] Explicitly stated (please specify)
- [x] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
- minorities under stereotype threat  

**Study 2**:  
- women under maths stereotype threat.  

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?
*e.g. telephone directory, electoral register, postcode, school listing, etc. There may be two stages – e.g. first sampling schools and then classes or pupils within them.*

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
- participants were considered eligible for the study if they reported on a pretest having knowledge of the stereotype that Whites are perceived to be more intelligent than stigmatized minorities in society.


### Which methods does the study use to select people or groups of people (from the sampling frame)?
*e.g. selecting people at random, systematically - selecting for example every 5th person, purposively in order to reach a quota for a given characteristic.*

- [ ] Not applicable (no sampling frame)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

### Planned sample size
*If more than one group please give details for each group separately.*

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [x] Not stated/unclear (please specify)

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?
*e.g. letters of invitation, telephone contact, face-to-face contact.*

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- University  

### Were any incentives provided to recruit people into the study?

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
- course creit or $10  

**Study 2**:  
- all participants received course credit  

### Was consent sought?
*Please comment on the quality of consent if relevant.*

- [ ] Not applicable (please specify)
- [ ] Participant consent sought
- [ ] Parental consent sought
- [ ] Other consent sought
- [ ] Consent not sought
- [x] Not stated/unclear (please specify)

### Are there any other details relevant to recruitment and consent?

- [x] No
- [ ] Yes (please specify)

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?
*If more than one group is being compared please give numbers for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
- Participants were 78 undergraduates who self-identified as White American, Hispanic American, African American, or American Indian.
- One participant was excluded for not following instructions on the working memory task 
- The final sample consisted of 37 academically stigmatized minorities (17 Hispanics, 16 African Americans, and 4 American Indian) and 40 Whites.

**Study 2**:  
- 116 female undergraduates who self-identified as American.  
- Final sample consisted of 111 females (79 White, 10 Hispanic, 7 African American, 7 Asian American, 1 American Indian, and 7 unidentified)


-### What is the proportion of those selected for the study who actually participated in the study? 
*Please specify numbers and percentages if possible.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
- one was excluded for not following instructions on the working memory task  
- 77 out of 78  

**Study 2**:  
- Three participants were excluded for not following instructions on the working memory task
- Two additional participants with working memory scores over 3 SD above the mean were also excluded
- 111 out of 116  

### Which country/countries are the individuals in the actual sample from?
*If UK, please distinguish between England, Scotland, N. Ireland, and Wales if possible. If from different countries, please give numbers for each. If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [x] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
- US 

**Study 2**:  
- US 

### What ages are covered by the actual sample?
*Please give the numbers of the sample that fall within each of the given categories. If necessary, refer to a page number in the report (e.g. for a useful table). If more than one group is being compared, please describe for each group. If follow-up study, age at entry to the study.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] 0 to 4
- [ ] 5 to 10
- [ ] 11 to 16
- [ ] 17 to 20
- [ ] 21 and over
- [x] Not stated/unclear (please specify)

### What is the socio-economic status of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is the ethnicity of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
- 17 Hispanics, 16 African Americans, 4 American Indian, 40 Whites  

**Study 2**:   
- 79 White, 10 Hispanic, 7 African American, 7 Asian American, 1 American Indian, 7 unidentified  

### What is known about the special educational needs of individuals within the actual sample?
*e.g. specific learning, physical, emotional, behavioural, intellectual difficulties.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Is there any other useful information about the study participants?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify no/s.)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 
*Please specify basis for your decision.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (no sampling frame)
- [ ] High (please specify)
- [x] Medium (please specify)
- [ ] Low (please specify)
- [ ] Unclear (please specify)

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?
*If the study involves more than one group, please give drop-out rates for each group separately. If necessary, refer to a page number in the report (e.g. for a useful table).*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Not applicable (no drop outs)
- [ ] Yes (please specify)
- [ ] No

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Yes (please specify)
- [ ] No

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [ ] Details

**Study 1**:  
- demographics  -> a and b
- working memory test -> b
- anxiety measure -> b  

**Study 2**:  
- see study 1



### Which methods were used to collect the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Curriculum-based assessment
- [ ] Focus group
- [ ] Group interview
- [ ] One to one interview (face to face or by phone)
- [ ] Observation
- [ ] Self-completion questionnaire
- [ ] Self-completion report or diary
- [ ] Exams
- [ ] Clinical test
- [ ] Practical test
- [ ] Psychological test
- [ ] Hypothetical scenario including vignettes
- [ ] School/college records (e.g. attendance records etc)
- [ ] Secondary data such as publicly available statistics
- [ ] Other documentation
- [ ] Not stated/unclear (please specify)

### Details of data collection methods or tool(s).
*Please provide details including names for all tools used to collect data and examples of any questions/items given. Also please state whether source is cited in the report.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
*Anxiety*:
- rated the extent to which they felt agitated, anxious, nervous, uneasy, and worried after completing the initial five verbal analogy items 
- 7 point scale

*Working memory*:
- Adapted from the Reading Span Test (Daneman & Carpenter, 1980)
- Modified so that one sentence in each of hte 12 sets contained either a confidence- or doubt-related word (e.g., "I am very confident/doubtful that our team will win the big game tonight")

*Manipulation check for stereotype threat*:
- rated their agreement on a 7-point scale with the two statements:
- "Thoughts of my ethnic group occurred frequently on my mind when I was working on the verbal IQ test"
- "I am concerned that the researcher will judge people of my race/ethnicity based on my performance if I did not do well on today's IQ test."

**Study 2**:  
- see study 1


### Who collected the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Researcher
- [ ] Head teacher/Senior management
- [ ] Teaching or other staff
- [ ] Parents
- [ ] Pupils/students
- [ ] Governors
- [ ] LEA/Government officials
- [ ] Other education practitioner
- [ ] Other (please specify)
- [ ] Not stated/unclear

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?
*e.g. test-retest methods (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?
*e.g. mention previous validation of tools, published version of tools, involvement of target population in development of tools. (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?
*Not applicable – e.g. analysis of existing data, qualitative study. No – e.g. assessment of reading progress for dyslexic pupils done by teacher who provided intervention. Yes – e.g. researcher assessing pupil knowledge of drugs - unaware of pupil allocation.*

- [ ] Not applicable (please say why)
- [ ] Yes (please specify)
- [ ] No (please specify)

### Where were the data collected?
*e.g. school, home.*

- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Unclear/not stated (please specify)

### Are there other important features of data collection?
*e.g. use of video or audio tape; ethical issues such as confidentiality etc.*

- [ ] Details

## Methods - Data analysis

### Which methods were used to analyse the data?
*Please give details e.g. for in-depth interviews, how were the data handled? Details of statistical analysis can be given next.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Study 1**:  
*Manipulation check for stereotype threat*:
- Responses to the two items were averaged to create an index of ethnicity-based evaluation concern. 
- 2 (prime) x 2 (ethnicity) ANOVA was conducted on our measure of ethnicity-based evaluation concerns  
*Anxiety*:
- 2 (prime) x 2 (ethnicity) ANOVA was performed on the self-reported anxiety scores  
*Working memory*:
Sentence reading time:
   - 2 (ethnicity) x 2 (prime condition) x 2 (sentence type: prime vs neutral) ANOVA (with sentence type as a within-subjects factor)  
Word recall:  
   - series of hierarchical regression analyses (Aiken & West, 1991)
   - The ethnicity of the participants, the type of prime they received, and the centred anxiety variable were entered in the first step of the model
   - The two-way interaction variables (e.g. Anxiety x Prime) were entered in the second step of the model, and the three-way interaction variable was entered in the last step.  
   

**Study 2**:  
*Manipulation check for stereotype threat*:
- 2 (prime) x (task frame) ANOVA was conducted on participants' rating of concern that the researcher would judge women's abilities based on their personal performance  
*Anxiety Ratings*:
- 2 (prime) x 2 (task frame) ANOVA was conducted on participants' self-reported anxiety scores  
- simple effects tests  
*Working memory*:  
Time spent reading sentences:
   - 2 (task frame) x 2 (prime) x 2 (sentence type) ANOVA (with sentence type as a within subjects factor) was conducted on the average time participants spent reading aloud confidence/doubt versus sentences in the working memory task  
Word recall:
   - Hierarchical regression analysis
   - Working memory scores were regressed on task frame, prime, and the entered anxiety variable on Step 1, the two-way interactions between these predictions on Step 2, and the three-way interaction variable on Step 3.
   - simple interaction analyses
   - simple slope analyses  


   

### Which statistical methods, if any, were used in the analysis?

- [ ] Details

### What rationale do the authors give for the methods of analysis for the study?
*e.g. for their methods of sampling, data collection, or analysis.*

- [ ] Details

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.
*'Intention to intervene' means that data were analysed on the basis of the original number of participants as recruited into the different groups. 'Intervention received' means data were analysed on the basis of the number of participants actually receiving the intervention.*

- [ ] Not applicable (not an evaluation study with prospective allocation)
- [ ] 'Intention to intervene'
- [ ] 'Intervention received'
- [ ] Not stated/unclear (please specify)

### Do the authors describe any ways they have addressed the reliability of data analysis?
*e.g. using more than one researcher to analyse data, looking for negative cases.*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of data analysis?
*e.g. internal or external consistency; checking results with participants.*

- [ ] Details

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [ ] Details

### Please describe any other important features of the analysis.

- [ ] Details

### Please comment on any other analytic or statistical issues if relevant.

- [ ] Details

## Results and Conclusions

### How are the results of the study presented?
*e.g. as quotations/figures within text, in tables, appendices.*

- [ ] Details

**Study 1 and 2**:  
- figure
- in text


### What are the results of the study as reported by authors?
*Please give details and refer to page numbers in the report(s) of the study where necessary (e.g. for key tables).*

- [ ] Details

**Study 1**:  
*Manipulation Check of Stereotype Threat*:  
- As predicted, minority students were more concerned about their performance reflecting on their group than were Whites.  
*Anxiety*:
- ANOVa yielded no main effect for prime or a Prime x Ethnicity interaction
- There was, however, a marginal main effect for ethnicity
- Minorities reported marginally higher levels of anxiety compared to Whites 
- Thus, the stereotype threat manipulation engendered some feelings of anxiety among minority participants.  
*Working memory*:  
Sentence reading time:
   - ANOVA yielded no main effects or interactions
   - Thus, participants read the neutral sentences at the same pace as the prime sentences  
Word recall:
   - main effect for anxiety
   - main effect was qualified by the predicted two-way interaction between anxiety and the type of prime
   - Anxiety predicted lower working memory scores in the doubt condition but not in the confidence condition
   - at 1 SD above mean of anxiety, those primed with doubt had significantly lower working memory scores than those primed with confidence
   - Pattern was reversed at 1 SD below the mean of anxiety
   - No other effects were significant including the three-way interaction among ethnicity, prime type, and anxiety
   - Lack of prime main effect suggests that thoughts of doubt (vs. confidence) did not promote cognitive interference overall and that the lack of a significant three-way interaction with ethnicity reveals that the moderated pattern observed was not significantly different between White and minority participants.  
   

**Study 2**:  
*Manipulation Check of Stereotype Threat*:  
- Women led to believe that they would be taking a diagnostic maths test reported more concern about how their gender would be evaluated compared with women in the neutral condition
- No other effects were significant
- Manipulation of stereotype threat was effective in eliciting group-based performance concerns  
*Anxiety Ratings*:  
- ANOVA produced an unexpected interaction
- Although the simple effects tests were not significant, women subsequently assigned to the doubt prime condition reported somewhat more anxiety in the diagnostic condition compared to the neutral condition
- Anxiety ratings were reversed between the diagnostic and neutral conditions among women subsequently assigned to receive confidence primes
- As our primary hypothesis concerns the relationship that these anxiety ratings have with working memory, rather than simple mean differences in working memory between the four conditions, these initial condition differences in anxiety are partialed out of our analysis of working memory, minimizing any effect they could have.  
*Working memory*:  
Time spent reading sentences:  
   - ANOVA revealed no significant main effect or interactions  
Word recall:  
   - Analysis revealed no significant main effects or two-way interactions
   - the predicted three-way interaction among task frame, prime, and anxiety level was significant
   - Simple interaction analyses revealed that the Anxiety x Prime interaction observed in Study 1 was only significant in the diagnostic task frame condition and was not significant in the neutral task frame condition
   - Simple slope analyses within the diagnostic task frame condition further revealed that at 1 SD above the mean of anxiety, women primed with doubt had significantly lower working memory scores compared with women primed with confidence.
   - At 1 SD below the mean of anxiety, the prime manipulation had no effect on working memory
   - In addition, within the diagnostic task frame condition, women primed with doubt who reported higher levels of anxiety tended to have lower working memory scores compared with women who reported lower levels of anxiety
   - This pattern was reversed but was not significant among women who received confidence primes
   - Thus, consistent with our hypothesis, primed thoughts of doubt significantly altered the relationship between anxiety and working memory, but only among women expecting to take a diagnostic maths test.
   
   
   
   
   
   

### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [ ] Yes
   - [x] No
   - [ ] Can’t tell
   
### Are there any obvious shortcomings in the reporting of the data?

- [ ] Yes (please specify)
- [x] No

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?
*This excludes variables just used to describe the sample.*

- [x] Yes (please specify)
- [ ] No

### Do the authors state where the full original data are stored?

- [ ] Yes (please specify)
- [x] No

### What do the author(s) conclude about the findings of the study?
*Please give details and refer to page numbers in the report of the study where necessary.*

- [ ] Details

**Study 1**:  
Results supported our hypothesis that although individuals vary in the degree to which they experience anxiety in an intellectually threatening environment, the valence of their thoughts can alter whether that anxiety predicts cognitive impairments
- When individuals experience heightened anxiety in an intellectual performance situation, they subsequently exhibit lower working memory but only when primed with thoughts of doubt 
- By comparison, anxiety did not predict lower working memory when participants had been primed with thoughts of confidence
- This occurred regardless of ethnicity of participant, suggesting that metacognitive processes might play a general role in self-relevant performance situations, such as high-stakes intellectual testing


**Study 2**:  
Results replicated findings in Study 1 with a different stigmatized group.
Primed thoughts of confidence or doubt moderated the relationships that anxiety had with women's working memory only when women were placed in a stereotype-threatening environment.
Specifically, women who experienced higher levels of anxiety under stereotype threat exhibited somewhat lower working memory when they were primed with doubt.
Conversely, priming women with confidence buffered them from this relationship under stereotype threat.
However, when the situation was framed in a less self-relevant way, anxiety did not predict women's working memory.
Presumably, this less threatening frame did not promote the level of self-evaluation required to elicit metacognitive interpretation of anxiety in light of primed thoguhts of doubt.  


## Quality of the study - Reporting 

### Is the context of the study adequately described?
*Consider your answer to questions: Why was this study done at this point in time, in those contexts and with those people or institutions? (Section B question 2) Was the study informed by or linked to an existing body of empirical and/or theoretical research? (Section B question 3) Which of the following groups were consulted in working out the aims to be addressed in the study? (Section B question 4) Do the authors report how the study was funded? (Section B question 5) When was the study carried out? (Section B question 6)*

- [x] Yes (please specify)
- [ ] No (please specify)

### Are the aims of the study clearly reported?
*Consider your answer to questions: What are the broad aims of the study? (Section B question 1) What are the study research questions and/or hypotheses? (Section C question 10)*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?
*Consider your answer to all questions in Methods on ‘Sampling Strategy’, ‘Recruitment and Consent’, and ‘Actual Sample’.*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods used in the study to collect data?
*Consider your answer to the following questions in Section I: Which methods were used to collect the data? Details of data collection methods or tools Who collected the data? Do the authors describe the setting where the data were collected? Are there other important features of the data collection procedures?*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods of data analysis?
*Consider your answer to the following questions in Section J: Which methods were used to analyse the data? What statistical methods, if any, were used in the analysis? Who carried out the data analysis?*

- [x] Yes (please specify)
- [ ] No (please specify)

### Is the study replicable from this report?

- [x] Yes (please specify)
- [ ] No (please specify)

### Do the authors avoid selective reporting bias?
*(e.g. do they report on all variables they aimed to study as specified in their aims/research questions?)*

- [x] Yes (please specify)
- [ ] No (please specify)

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?
*Consider consent, funding, privacy, etc.*

- [x] Yes, some concerns (please specify)
- [ ] No concerns

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [ ] Yes, a lot (please specify)
- [x] Yes, a little (please specify)
- [ ] No (please specify)

### Is there sufficient justification for why the study was done the way it was?

- [x] Yes (please specify)
- [ ] No (please specify)

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [x] Yes (please specify)
- [ ] No (please specify)

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?
*e.g. (1) In an evaluation, was the process by which participants were allocated to or otherwise received the factor being evaluated concealed and not predictable in advance? If not, were sufficient substitute procedures employed with adequate rigour to rule out any alternative explanations of the findings which arise as a result? e.g. (2) Was the attrition rate low and if applicable similar between different groups?*

- [ ] A lot (please specify)
- [x] A little (please specify)
- [ ] Not at all (please specify)

### How generalisable are the study results?

- [ ] Details

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?
*In some studies it is difficult to distinguish between the findings of the study and the conclusions. In those cases please code the trustworthiness of this combined results/conclusion.** Please remember to complete the weight of evidence questions B-D which are in your review specific data extraction guidelines. ***

- [ ] High trustworthiness (please specify)
- [x] Medium trustworthiness (please specify)
- [ ] Low trustworthiness (please specify)

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [ ] Not applicable (results and conclusions inseparable)
- [ ] High trustworthiness
- [x] Medium trustworthiness
- [ ] Low trustworthiness
    

# @wellsNewcastleottawaScaleNOS2014

## **CASE CONTROL STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Exposure categories. A maximum of two stars can be given for Comparability.

## Selection

### Is the case definition adequate?
   - a) yes, with independent validation 
   - b) yes, e.g., record linkage or based on self reports
   - c) no description

### Representativeness of the cases
   - a) consecutive or obviously representative series of cases *
   - b) potential for selection biases or not stated

### Selection of Controls
   - a) community controls *
   - b) hospital controls
   - c) no description

### Definition of Controls
   - a) no history of disease (endpoint) *
   - b) no description of source

## Comparability

### Comparability of cases and controls on the basis of the design or analysis
   - a) study controls for _______________ (Select the most important factor.) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Exposure

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview where blind to case/control status *
   - c) interview not blinded to case/control status
   - d) written self report or medical record only
   - e) no description

### Same method of ascertainment for cases and controls
   - a) yes *
   - b) no

### Non-Response rate
   - a) same rate for both groups *
   - b) non respondents described
   - c) rate different and no designation

---

## **COHORT STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Outcome categories. A maximum of two stars can be given for Comparability.

## Selection

### Representativeness of the exposed cohort
   - a) truly representative of the average _______________ (describe) in the community *
   - b) somewhat representative of the average ______________ in the community *
   - c) selected group of users, e.g., nurses, volunteers
   - d) no description of the derivation of the cohort

### Selection of the non exposed cohort
   - a) drawn from the same community as the exposed cohort *
   - b) drawn from a different source
   - c) no description of the derivation of the non exposed cohort

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview *
   - c) written self report
   - d) no description

### Demonstration that outcome of interest was not present at start of study
   - a) yes *
   - b) no

## Comparability

### Comparability of cohorts on the basis of the design or analysis
   - a) study controls for _____________ (select the most important factor) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Outcome

### Assessment of outcome
   - a) independent blind assessment *
   - b) record linkage *
   - c) self report
   - d) no description

### Was follow-up long enough for outcomes to occur
   - a) yes (select an adequate follow up period for outcome of interest) *
   - b) no

### Adequacy of follow up of cohorts
   - a) complete follow up - all subjects accounted for *
   - b) subjects lost to follow up unlikely to introduce bias - small number lost - > ____ % (select an adequate %) follow up, or description provided of those lost) *
   - c) follow up rate < ____% (select an adequate %) and no description of those lost
   - d) no statement


# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

### Did the review address a clearly focussed issue?
- Was there enough information on:
  - The population studied
  - The intervention given
  - The outcomes considered
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the authors look for the appropriate sort of papers?
- The ‘best sort of studies’ would:
  - Address the review’s question
  - Have an appropriate study design
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## ARE THE RESULTS OF THIS REVIEW VALID?

### Do you think the important, relevant studies were included?
- Look for:
  - Which bibliographic databases were used
  - Follow up from reference lists
  - Personal contact with experts
  - Search for unpublished as well as published studies
  - Search for non-English language studies
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the review’s authors do enough to assess the quality of the included studies?
- The authors need to consider the rigour of the studies they have identified. Lack of rigour may affect the studies results.
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### If the results of the review have been combined, was it reasonable to do so?
- Consider whether:
  - The results were similar from study to study
  - The results of all the included studies are clearly displayed
  - The results of the different studies are similar
  - The reasons for any variations are discussed
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WHAT ARE THE RESULTS?

### What is the overall result of the review?
- Consider:
  - If you are clear about the review’s ‘bottom line’ results
  - What these are (numerically if appropriate)
  - How were the results expressed (NNT, odds ratio, etc)

### How precise are the results?
- Are the results presented with confidence intervals?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WILL THE RESULTS HELP LOCALLY?

### Can the results be applied to the local population?
- Consider whether:
  - The patients covered by the review could be sufficiently different from your population to cause concern
  - Your local setting is likely to differ much from that of the review
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Were all important outcomes considered?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Are the benefits worth the harms and costs?
- Even if this is not addressed by the review, what do you think?
- [ ] Yes
- [ ] Can’t tell
- [ ] No


# References


::: {#refs custom-style="Bibliography"}
:::
