---
title             : "@wulandariTrustYourAbilities2020"
shorttitle        : "@wulandariTrustYourAbilities2020"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h2.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [x] Not applicable (whole study is focus of data extraction)

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?

- [x] Explicitly stated (please specify)  

The study was informed by existing research on gender stereotype threat, particularly its effects on cognitive tasks favoring women like verbal fluency. It cites previous studies on stereotype threat in math and spatial tasks, as well as the limited research on female-stereotyped tasks.

### Do authors report how the study was funded?

- [x] Not stated/unclear (please specify)  

The authors do not report how the study was funded.

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

The study focuses on the effects of gender stereotype threat on letter fluency performance, including overall performance and underlying cognitive processes (clustering and switching).

### What is/are the population focus/foci of the study?

The population focus is undergraduate students in Indonesia.

### What is the relevant age group? 

- [x] 17 - 20  
- [x] 21 and over  

The study included undergraduate students, likely spanning ages 17-23+.

### What is the sex of the population focus/foci?

- [x] Mixed sex  

The study included both male and female participants.

### What is/are the educational setting(s) of the study?

- [x] Higher education institution  

The study was conducted with undergraduate students at a state university in Indonesia.

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)  

The study was carried out in Indonesia.

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

The study examined how different gender stereotype threat activation cues and task difficulty levels affected letter fluency performance in male and female university students. It looked at overall performance (correct words, errors) as well as underlying cognitive processes (clustering, switching).

### What are the study reserach questions and/or hypotheses?

- [x] Explicitly stated (please specify)  

The study hypothesized that different types of gender stereotype activation cues would affect male and female performance differently, and increasing difficulty levels would decrease letter fluency performance.

## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)  

The study aimed to measure:
- Letter fluency performance (correct words, errors)
- Clustering and switching in letter fluency
- Effects of stereotype threat activation cues
- Effects of task difficulty level
- Gender differences
- Beliefs about gender stereotypes in letter fluency

### Study timing

- [x] Cross-sectional  

The study collected data from participants at a single time point.

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?

- [x] Only after  

Measurements were taken only after the stereotype threat manipulation and during/after the letter fluency task.

## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.

- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  

Participants were randomly assigned to four stereotype threat activation groups.

### How do the groups differ?

- [x] Explicityly stated (please specify)  

The groups differed in the type of stereotype threat activation cue they received: blatant, moderately explicit, subtle, or no activation (control).

### Number of groups

- [x] Four or more (please specify)  

There were four groups: blatant, moderately explicit, subtle, and control.

### Was the assignment of participants to interventions randomised?

- [x] Random  

Participants were randomly assigned to the four stereotype threat activation groups.

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?

- [x] Yes (please specify)  

The study was described as single-blind, indicating allocation was concealed from participants.

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [x] Yes

All groups completed the same letter fluency task with three difficulty levels.

### Study design summary 

This was a single-blind, randomized controlled experiment. Participants were randomly assigned to four stereotype threat activation groups and completed a letter fluency task with three difficulty levels. The study examined effects on overall performance and underlying cognitive processes.

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 

- [x] Implicit (please specify)  

The authors seem to be aiming for findings representative of Indonesian university students, though this is not explicitly stated.

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?

- [x] Explicitly stated (please specify)  

The study recruited undergraduate students from a state university in Depok, Indonesia.

### Which methods does the study use to select people or groups of people (from the sampling frame)?

- [x] Not stated/unclear (please specify)  

The specific method of selecting students from the university is not stated.

### Planned sample size

- [x] Explicitly stated (please specify)  

The planned sample size was 168 participants (91 female).

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?

- [x] Not stated/unclear (please specify)  

The specific recruitment methods are not described.

### Were any incentives provided to recruit people into the study?

- [x] Not stated/unclear (please specify)  

The use of incentives is not mentioned.

### Was consent sought?

- [x] Participant consent sought

The paper states "Informed consent was obtained from all participants."

### Are there any other details relevant to recruitment and consent?

- [x] No

No other details about recruitment or consent are provided.

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?

- [x] Explicitly stated (please specify)  

The actual sample was 168 undergraduate students (91 female).

### What is the proportion of those selected for the study who actually participated in the study? 

- [x] Not stated/unclear (please specify)  

The proportion of those selected who participated is not reported.

### Which country/countries are the individuals in the actual sample from?

- [x] Explicitly stated (please specify)  

The participants were from Indonesia.

### What ages are covered by the actual sample?

- [x] Not stated/unclear (please specify)  

The exact age range is not specified, but participants were undergraduate students.

### What is the socio-economic status of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)  

The socio-economic status of participants is not reported.

### What is the ethnicity of the individuals within the actual sample?

- [x] Not stated/unclear (please specify)  

The ethnicity of participants is not reported.

### What is known about the special educational needs of individuals within the actual sample?

- [x] Not stated/unclear (please specify)  

No information is provided about special educational needs.

### Is there any other useful information about the study participants?

- [x] Explicitly stated (please specify no/s.)

Participants were excluded if they: did not speak Bahasa as their first language, had a history of brain trauma/surgery, had neurological/psychiatric disorders, had substance/alcohol abuse history, or were left-handed/ambidextrous.

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 

- [x] Unclear (please specify)

The representativeness of the sample is unclear, as details about the broader student population are not provided.

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?

- [x] Not applicable (not following samples prospectively over time)

This was a cross-sectional study without follow-up.

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [x] Not applicable (not following samples prospectively over time)

This was a cross-sectional study without follow-up.

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [x] Not applicable (not following samples prospectively over time)

This was a cross-sectional study without follow-up.

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [x] Details

The main types of data collected were:
(a) To define the sample: demographic information, language background, neurological history
(b) As findings: letter fluency test scores (correct words, errors, clustering, switching), gender stereotype questionnaire responses, self-rating scores

### Which methods were used to collect the data?

- [x] Self-completion questionnaire
- [x] Psychological test

The study used a letter fluency test, gender stereotype questionnaire, and self-rating questionnaire.

### Details of data collection methods or tool(s).

- [x] Explicitly stated (please specify)

The study used:
- Pre-recorded instructions for stereotype threat activation
- Letter fluency test with letters K, R, W
- Gender stereotype questionnaire adapted from Hausmann et al. (2009)
- Self-rating questionnaire adapted from Hausmann et al. (2009)
- Manipulation check questionnaire

### Who collected the data?

- [x] Researcher

The paper mentions an "experimenter" who administered the tasks.

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?

- [x] Details

The authors do not explicitly discuss reliability of data collection methods.

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?

- [x] Details

The authors mention adapting and translating questionnaires from previous research, but do not explicitly discuss validation.

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?

- [x] Yes (please specify)

The study was described as single-blind, indicating outcome assessors were likely blinded to group allocation.

### Where were the data collected?

- [x] Unclear/not stated (please specify)

The specific location of data collection is not stated.

### Are there other important features of data collection?

- [x] Details

Pre-recorded instructions were used to ensure consistency in stereotype threat activation and task instructions.

## Methods - Data analysis

### Which methods were used to analyse the data?

- [x] Explicitly stated (please specify)

The study used ANOVA, t-tests, and correlation analyses.

### Which statistical methods, if any, were used in the analysis?

- [x] Details

The study used Kruskal-Wallis Test, Kolmogorov-Smirnov Test, mixed ANOVA, one-way ANOVA, one-sample t-tests, and Pearson correlations.

### What rationale do the authors give for the methods of analysis for the study?

- [x] Details

The authors do not provide an explicit rationale for their choice of analysis methods.

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.

- [x] Not applicable (not an evaluation study with prospective allocation)

This was not an evaluation study with prospective allocation.

### Do the authors describe any ways they have addressed the reliability of data analysis?

- [x] Details

The authors do not explicitly discuss reliability of data analysis.

### Do the authors describe any ways they have addressed the validity of data analysis?

- [x] Details

The authors do not explicitly discuss validity of data analysis.

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [x] Details

The authors mention controlling for demographic and ability-related variables by ensuring a homogeneous sample in terms of education level, language background, and neurological health.

### Please describe any other important features of the analysis.

- [x] Details

The authors analyzed both overall performance (correct words, errors) and underlying cognitive processes (clustering, switching) in letter fluency.

### Please comment on any other analytic or statistical issues if relevant.

- [x] Details

No other notable analytic or statistical issues.

## Results and Conclusions

### How are the results of the study presented?

- [x] Details

Results are presented in text, tables, and figures, including descriptive statistics, ANOVA results, and correlation analyses.

### What are the results of the study as reported by authors?

- [x] Details

Key results include:
- Stereotype threat activation and gender did not significantly affect letter fluency performance
- Task difficulty affected number of correct words but not errors
- Men produced larger cluster sizes than women
- Self-rating scores correlated with actual performance
- Participants held beliefs about women's superiority in letter fluency

### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [x] No

The study did not report confidence intervals for effect estimates.

### Are there any obvious shortcomings in the reporting of the data?

- [x] No

The data reporting appears adequate for the analyses conducted.

### Do the authors report on all variables they aimed to study as specified in their aims/research questions?

- [x] Yes (please specify)

The authors report on all main variables mentioned in their aims and hypotheses.

### Do the authors state where the full original data are stored?

- [x] No

The authors do not state where the original data are stored.

### What do the author(s) conclude about the findings of the study?

- [x] Details

The authors conclude that:
- Stereotype threat activation did not affect letter fluency performance
- Task difficulty affected performance but did not interact with stereotype threat
- Self-efficacy, educational level, and individual susceptibility factors may explain the lack of stereotype threat effects
- Participants' self-ratings better predicted performance than stereotype beliefs

## Quality of the study - Reporting 

### Is the context of the study adequately described?

- [x] Yes (please specify)

The study context is well-described, including background on stereotype threat research and letter fluency tasks.

### Are the aims of the study clearly reported?

- [x] Yes (please specify)

The study aims and hypotheses are clearly stated.

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?

- [x] Yes (please specify)

The sample characteristics and inclusion/exclusion criteria are adequately described, though recruitment methods could be clearer.

### Is there an adequate description of the methods used in the study to collect data?

- [x] Yes (please specify)

The data collection methods, including tasks and questionnaires, are adequately described.

### Is there an adequate description of the methods of data analysis?

- [x] Yes (please specify)

The data analysis methods are adequately described, though more rationale could be provided.

### Is the study replicable from this report?

- [x] Yes (please specify)

The methods are described in sufficient detail to allow replication.

### Do the authors avoid selective reporting bias?

- [x] Yes (please specify)

The authors report on all main variables and analyses mentioned in their aims and methods.

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?

- [x] No concerns

The study obtained informed consent and does not raise obvious ethical concerns.

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [x] No (please specify)

There is no mention of student or parent involvement in study design or conduct.

### Is there sufficient justification for why the study was done the way it was?

- [x] Yes (please specify)

The authors provide adequate justification for their study design based on gaps in previous research.

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [x] Yes (please specify)

The randomized experimental design was appropriate for examining stereotype threat effects.

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?

- [x] A little (please specify)

The randomized design helps control for some biases, but individual differences in stereotype susceptibility may remain a source of error.

### How generalisable are the study results?

- [x] Details

The results may generalize to Indonesian university students, but generalizability to other populations is limited.

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?

- [x] Medium trustworthiness (please specify)

The study has a sound design and methods, but some limitations in sample representativeness and analysis rationale reduce trustworthiness.

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [x] Medium trustworthiness

The authors provide reasonable justifications for their conclusions, discussing potential explanations for their findings and acknowledging limitations. However, some conclusions could be more cautiously stated given the null results.

# @wellsNewcastleottawaScaleNOS2014

## **CASE CONTROL STUDIES**

This section is not applicable as the study is not a case-control design.

## **COHORT STUDIES**

This section is not applicable as the study is not a cohort design.

# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

This section is not applicable as this is a primary study, not a systematic review.

## ARE THE RESULTS OF THIS REVIEW VALID?

This section is not applicable as this is a primary study, not a systematic review.

## WHAT ARE THE RESULTS?

This section is not applicable as this is a primary study, not a systematic review.

## WILL THE RESULTS HELP LOCALLY?

This section is not applicable as this is a primary study, not a systematic review.

# References


::: {#refs custom-style="Bibliography"}
:::