---
title             : "@jordanoPrimingPerformancerelatedConcerns2017"
shorttitle        : "@jordanoPrimingPerformancerelatedConcerns2017"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h2.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

# @eppi-centreReviewGuidelinesExtracting2003 & @criticalappraisalskillsprogrammeCASPSystematicReview2018

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [x] Not applicable (whole study is focus of data extraction)  
- [ ] Specific focus of this data extraction (please specify)  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?
*Please write in authors' declaration if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Mind-wandering
- Executive Control
- Mind-wandering and executive control: relationship
- Stereotype threat

### Do authors report how the study was funded?

- [ ] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [x] Not stated/unclear (please specify)  

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

- In the current studies, we provide a direct test of the "control failure x current concerns" framework by priming performance-related concerns in younger adults and assessing the impact on probe-caught off-task thoughts regarding the task (TRI). More specifically, we prime current, performance-related concerns in these younger adults using a stereotype threat intervention.  
- The current studies examine the effect of priming personal, performance-related concerns on midn-wandering by using a stereotype threat manipulation.   

### What is/are the population focus/foci of the study?

- younger adults  

### What is the relevant age group? 

- [ ] Not applicate (focus not learners)  
- [ ] 0 - 4  
- [ ] 5 - 10  
- [ ] 11 - 16  
- [ ] 17 - 20  
- [ ] 21 and over  
- [x] Not stated/unclear  

### What is the sex of the population focus/foci?

- [ ] Not applicate (focus not learners)  
- [ ] Female only  
- [ ] Male only  
- [ ] Mixed sex  
- [x] Not stated/unclear  

### What is/are the educational setting(s) of the study?

- [ ] Community centre  
- [ ] Correctional institution  
- [ ] Government department  
- [ ] Higher education institution  
- [ ] Home  
- [ ] Independent school  
- [ ] Local education authority  
- [ ] Nursery school  
- [ ] Other early years setting  
- [ ] Post-compulsory education institution  
- [ ] Primary school  
- [ ] Residential school  
- [ ] Secondary school  
- [ ] Special needs school  
- [ ] Workplace  
- [ ] Other educational setting  

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)  
- [ ] Not stated/unclear (please specify)  

- United States of America  

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

### What are the study reserach questions and/or hypotheses?
*Research questions or hypotheses operationalise the aims of the study. Please write in authors' description if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Two experiments tested the hypothesis that priming of performance-related concerns would (1) increase the frequency of task-related mind-wandering (i.e., task-related interference; TRI) and (2) decrease task performance.  

## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [ ] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Mind-wandering
- Stereotype threat
- OSPAN task
- IAT
- 

### Study timing
*Please indicate all that apply and give further details where possible.*

*If the study examines one or more samples, but each at only one point in time it is cross-sectional.*  
*If the study examines the same samples, but as they have changed over time, it is retrospective, provided that the interest is in starting at one timepoint and looking backwards over time.*  
*If the study examines the same samples as they have changed over time and if data are collected forward over time, it is prospective provided that the interest is in starting at one timepoint and looking forward in time.*  

- [x] Cross-sectional  
- [ ] Retrospective  
- [ ] Prospective  
- [ ] Not stated/unclear (please specify)  

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?
*If at least one of the outcome variables is measured both before and after the intervention, please use the before and after category.*

- [ ] Not applicable (not an evaluation)  
- [ ] Before and after  
- [ ] Only after  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  


## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.
*Please give further details where possible.*

- [ ] Not applicable (not more than one group)  
- [x] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  
- [ ] No prospective allocation but use of pre-existing differences to create comparison groups (e.g. receiving different interventions, or characterised by different levels of a variable such as social class)  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  

### How do the groups differ?

- [ ] Not applicable (not more than one group)  
- [x] Explicityly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  


- stereotype threat vs no stereotype threat  


### Number of groups
*For instance, in studies in which comparisons are made between groups, this may be the number of groups into which the dataset is divided for analysis (e.g. social class, or form size), or the number of groups allocated to, or receiving, an intervention.*

- [ ] Not applicable (not more than one group)  
- [ ] One  
- [x] Two  
- [ ] Three  
- [ ] Four or more (please specify)  
- [ ] Other/unclear (please specify)  

- two

### Was the assignment of participants to interventions randomised?

- [ ] Not applicable (not more than one group)  
- [ ] Not applicate (no prospective allocation)  
- [x] Random  
- [ ] Quasi-random  
- [ ] Non-random  
- [ ] Not stated/unclear (please specify)  

### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?
*Bias can be introduced, consciously or otherwise, if the allocation of pupils or classes or schools to a programme or intervention is made in the knowledge of key characteristics of those allocated. For example: children with more serious reading difficulty might be seen as in greater need and might be more likely to be allocated to the 'new' programme, or the opposite might happen. Either would introduce bias.*

- [ ] Not applicable (not more than one group)  
- [ ] Not applicable (no prospective allocation)  
- [x] Yes (please specify)  
- [ ] No (please specify)  
- [ ] Not stated/unclear (please specify)  

- The researchers also recruited male participants, to disguise that the study was about stereotype threat and gender differences in cognition. Male participants were tested in both the control and stereotype threat conditions together with the female participants, but only the data of the female participants were included in the analysis

### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [x] Yes
- [ ] No
- [ ] Can’t tell

### Study design summary 
*In addition to answering the questions in this section, describe the study design in your own words. You may want to draw upon and elaborate the answers you have already given.*

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 
*Please write in authors' description. If authors do not specify please indicate reviewers' interpretation.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- Females under stereotype threat  

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?
*e.g. telephone directory, electoral register, postcode, school listing, etc. There may be two stages – e.g. first sampling schools and then classes or pupils within them.*

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- Gender (only females are included in the data analysis)  

### Which methods does the study use to select people or groups of people (from the sampling frame)?
*e.g. selecting people at random, systematically - selecting for example every 5th person, purposively in order to reach a quota for a given characteristic.*

- [ ] Not applicable (no sampling frame)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- Gender, see above

### Planned sample size
*If more than one group please give details for each group separately.*

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [x] Not stated/unclear (please specify)

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?
*e.g. letters of invitation, telephone contact, face-to-face contact.*

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- Undergraduate students from the University of North Carolina at Greensboro participated in exchange for course credit.  

### Were any incentives provided to recruit people into the study?

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1**:
- Course credit


### Was consent sought?
*Please comment on the quality of consent if relevant.*

- [ ] Not applicable (please specify)
- [ ] Participant consent sought
- [ ] Parental consent sought
- [ ] Other consent sought
- [ ] Consent not sought
- [x] Not stated/unclear (please specify)

### Are there any other details relevant to recruitment and consent?

- [ ] No
- [x] Yes (please specify)

**Experiment 1**:
- there were no exclusions.

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?
*If more than one group is being compared please give numbers for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1**:
- Sixty female undergraduate students from the University of North Carolina at Greensboro participated in exchange for course credit ($M_{age}$ = 19.10, SD = 1.24). Half of the participants were tested in the stereotype threat condition, and the other half in the control condition. All of these participants were included in the analyses described below.

**Experiment 2**:
- Sixty female undergraduate students from the University of North Carolina at Greensboro participated in exchange for course credit ($M_{age}$ = 19.25, SD = 1.12). All of these participants were included in the analyses.

### What is the proportion of those selected for the study who actually participated in the study? 
*Please specify numbers and percentages if possible.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- all of them 100%

### Which country/countries are the individuals in the actual sample from?
*If UK, please distinguish between England, Scotland, N. Ireland, and Wales if possible. If from different countries, please give numbers for each. If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

- not stated. 

### What ages are covered by the actual sample?
*Please give the numbers of the sample that fall within each of the given categories. If necessary, refer to a page number in the report (e.g. for a useful table). If more than one group is being compared, please describe for each group. If follow-up study, age at entry to the study.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] 0 to 4
- [ ] 5 to 10
- [ ] 11 to 16
- [x] 17 to 20
- [ ] 21 and over
- [ ] Not stated/unclear (please specify)

**Experiment 1**:
- Mean age = 19.10, SD = 1.24

**Experiment 2**:
- Mean age = 19.25, SD = 1.12  


### What is the socio-economic status of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is the ethnicity of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is known about the special educational needs of individuals within the actual sample?
*e.g. specific learning, physical, emotional, behavioural, intellectual difficulties.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Is there any other useful information about the study participants?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify no/s.)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 
*Please specify basis for your decision.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (no sampling frame)
- [ ] High (please specify)
- [x] Medium (please specify)
- [ ] Low (please specify)
- [ ] Unclear (please specify)

- there were talking about "young adults", now we only have females. -> low to medium 

### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?
*If the study involves more than one group, please give drop-out rates for each group separately. If necessary, refer to a page number in the report (e.g. for a useful table).*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Not applicable (no drop outs)
- [ ] Yes (please specify)
- [ ] No

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Yes (please specify)
- [ ] No

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [ ] Details

**Experiment 1**:
- age -> a
- gender -> a
- OSPAN task (Operation Span Task) -> b
- Stereotype threat priming -> b
- Gender-Science Implicit Associations Task (IAT)
- manipulation check
- working memory capacity (OSPAN)
- response to 10 thought probes (appeared at quasi-random intervals - spacing was proximately every 2 min)
- TUT, TRI, on-task thoughts
- Dundee Stress State Questionnaire (DSSQ)
- Positive and Negative Affect Schedule (PANAS)
- Questionnaire (post task, about e.g. task difficulty, perceived fatigue during OSPAN, perceived stress duing the OSPAN)  

**Experiment 2**:
- Almost completely the same
- this time 9 thought probes
- OSPAN tasks were more challenigng  

### Which methods were used to collect the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Curriculum-based assessment
- [ ] Focus group
- [ ] Group interview
- [ ] One to one interview (face to face or by phone)
- [ ] Observation
- [x] Self-completion questionnaire
- [ ] Self-completion report or diary
- [x] Exams
- [ ] Clinical test
- [ ] Practical test
- [x] Psychological test
- [ ] Hypothetical scenario including vignettes
- [ ] School/college records (e.g. attendance records etc)
- [ ] Secondary data such as publicly available statistics
- [ ] Other documentation
- [ ] Not stated/unclear (please specify)

### Details of data collection methods or tool(s).
*Please provide details including names for all tools used to collect data and examples of any questions/items given. Also please state whether source is cited in the report.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- see above

### Who collected the data?
*Please indicate all that apply and give further detail where possible.*

- [x] Researcher
- [ ] Head teacher/Senior management
- [ ] Teaching or other staff
- [ ] Parents
- [ ] Pupils/students
- [ ] Governors
- [ ] LEA/Government officials
- [ ] Other education practitioner
- [ ] Other (please specify)
- [ ] Not stated/unclear

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?
*e.g. test-retest methods (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?
*e.g. mention previous validation of tools, published version of tools, involvement of target population in development of tools. (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?
*Not applicable – e.g. analysis of existing data, qualitative study. No – e.g. assessment of reading progress for dyslexic pupils done by teacher who provided intervention. Yes – e.g. researcher assessing pupil knowledge of drugs - unaware of pupil allocation.*

- [ ] Not applicable (please say why)
- [ ] Yes (please specify)
- [ ] No (please specify)

### Where were the data collected?
*e.g. school, home.*

- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Unclear/not stated (please specify)

### Are there other important features of data collection?
*e.g. use of video or audio tape; ethical issues such as confidentiality etc.*

- [ ] Details

## Methods - Data analysis

### Which methods were used to analyse the data?
*Please give details e.g. for in-depth interviews, how were the data handled? Details of statistical analysis can be given next.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- Questionnaires


### Which statistical methods, if any, were used in the analysis?

- [ ] Details

- Mean scores and SE (standard error)
- ANOVA

### What rationale do the authors give for the methods of analysis for the study?
*e.g. for their methods of sampling, data collection, or analysis.*

- [ ] Details

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.
*'Intention to intervene' means that data were analysed on the basis of the original number of participants as recruited into the different groups. 'Intervention received' means data were analysed on the basis of the number of participants actually receiving the intervention.*

- [ ] Not applicable (not an evaluation study with prospective allocation)
- [ ] 'Intention to intervene'
- [ ] 'Intervention received'
- [ ] Not stated/unclear (please specify)

### Do the authors describe any ways they have addressed the reliability of data analysis?
*e.g. using more than one researcher to analyse data, looking for negative cases.*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of data analysis?
*e.g. internal or external consistency; checking results with participants.*

- [ ] Details

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [ ] Details

### Please describe any other important features of the analysis.

- [ ] Details

### Please comment on any other analytic or statistical issues if relevant.

- [ ] Details

## Results and Conclusions

### How are the results of the study presented?
*e.g. as quotations/figures within text, in tables, appendices.*

- [ ] Details

- tables
- figures
- in text


### What are the results of the study as reported by authors?
*Please give details and refer to page numbers in the report(s) of the study where necessary (e.g. for key tables).*

- [ ] Details

**Experiment 1**:
- The proportion of probe-caught TRI was higher in stereotype threat primed participants than in control participants
- Participants primed for stereotype threat reported more intrusive off-task thoughts about task performance and task strategy than participants who were not primed for threat.
- Participants in the control condition were more likely to indicate being on-task than participants primed for stereotype threat, although this difference did not reach statistical significance.
- We expected that individuals could engage in TRI regarding task strategy ("proactive TRI") or TRI regarding evaluating one's task performance ("reactive TRI").
- Participants primed for stereotype threat engaged in both of these subtypes of TRI
- Primed participants reported higher proportion of TRI regarding task evaluation, compared to the control group, although this difference was not statistically significant.
- Primed participants also reported a significantly higher proportion of TRI regarding task approach or task strategy than control participants.


**Experiment 2**:
- Study 2 replicated the mind-wandering findings of Study 1 using a more challenging experimental task
- Probe-caught TRI was higher in the stereotype threat primed participants than in the control participants
- Control participants were more likely to indicate being on-task than stereotype threat primed participants
- Although the stereotype threat participants reported more TRI than controls, the groups did not differ in reported TUTs
- The group differences in mean proportion of on-task thoughts were driven by group differences in TRIs rather than TUTs
- Participants reported both subtypes of TRI
- Group differenes were not statistically significant, primed participants reported numerically more TRI regarding task evaluation compared to control participants
- Although this difference did not reach statistical significance it is possible that those under threat reflect more upon their task performance.
- Those under threat may have been more likely to think about way to imporve task performance.
- Engaging in proactive TRi did not seem to improve performance
- Probe-caught proactive TRI was not positively related with task performance in either condition.

### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [ ] Yes
   - [x] No
   - [ ] Can’t tell

### Are there any obvious shortcomings in the reporting of the data?

- [ ] Yes (please specify)
- [x] No


### Do the authors report on all variables they aimed to study as specified in their aims/research questions?
*This excludes variables just used to describe the sample.*

- [x] Yes (please specify)
- [ ] No

### Do the authors state where the full original data are stored?

- [ ] Yes (please specify)
- [x] No

### What do the author(s) conclude about the findings of the study?
*Please give details and refer to page numbers in the report of the study where necessary.*

- [ ] Details

**Experiment 1**:
- These results suggest that not only do those under threat potentially reflect more upon their task performance, but they may also think more about ways to improve task performance than those who do not experience threat.
- Although we had thought that proactive TRI might be beneficial for task performance, proactive TRI was *not* positively correlated with math verification accuracy in either the control condition or the stereotype threat primed condition.
- We found using online thought probes that stereotype threat primed and control participants did not differ in terms of probe-caught TUTs
- Primed participants were off-task more than control participants, but group differences in mind- wandering were driven by differences in TRI rather than TUTs
- Although we found that stereotype primed participants reported increased TRI and decrease on-task thoughts compared to control, we did not replicate the standard stereotype threat effect on task performance. 
- Contrary to our initial hypothesis, threat participants did *not* have worse math verification accuracy than control participants. 
- Letter recall accuracy also did not differ between the two conditions.

- Study 1 addressed the impact of priming personal, performance-related concerns on mind-wandering and task performance using a stereotype threat manipulation. As predicted, priming stereotype threat resulted in increased mind-wandering, particularly TRI. While participants primed for threat reported more TRI in general, participants in both conditions reported mind-wandering about task evaluation as well as task strategy. Although participants primed for threat reported fewer on-task thoughts than controls, they did not report more TUTs. The stereotype threat manipulation cued performance-related concerns, but did not increase concerns about things unrelated to the experimental task. This pattern of results is consistent with the “control failures × current concerns” framework of mind-wandering (2010).  


**Experiment 2**:
- Using a more challenging OSPAN task, we replicated the standard stereotype threat effect on task performance.
- Participants primed for math-gender stereotype threat had worse math verification accuracy than control participants
- There were no group differences in letter recall accuracy
- As in Study 1, we found no effect of stereotype threat priming on retrospective TUTs and TRI as measured by the DSSQ
- As in Study 1, we did not find that scores on the TRI subscale of the DSSQ correlated with probe-caught TRI in the control participants
- DSSQ TRI scores did correlate with probe-caught TRI in the stereotype threat primed participants
- We found no condition differences for the post-task questions regarding perceived stress, perceived fatigue, positive affect, and negative affect
- The two conditions did not differ in terms of reported motivation to do the task and perceived difficulty of the math verification portion of the OSPAN 


**General discussion**
The present studies demonstrate that priming of personal, performance-related current concerns can increase mind-wandering, particularly mind-wandering regarding task strategy and task evaluation (TRI). 
In Study 1, female undergraduates primed for math-gender stereotype threat reported more TRI than female undergraduate controls.
In Study 2, which employed a more challenging task, female undergraduates primed for math-gender stereotype threat reported more TRI than female undergraduate controls and also had worse performance on the mathematical component of the experimental task.  
In addition to supporting the "control failures x current concerns" framework of mind-wandering, these studies support current theories of stereotype threat.
The Study 2 findings are consistent with an explanations that stereotype threat undermines task performance through increases in metacognitive thoughts, which can result in teh depletion of executive control resources.
While past work has suggested that stereotype threat may decouple one's attention from the current task in a way that leads to increases in task-unrelated thoughts, the present studies find that stereotype threat increases thoughts related to the current task.

In the current studies, participants primed for stereotype threat did not report increased stress and increased negative mood compared to controls, which are proposed mechanisms by which stereotype threat leads to increased off-task thoughts and worse performance on the stereotyped task. In addition to work in the stereotype threat literature suggesting that increases in anxiety and suppression of worry-laden thoughts impair task performance, work within the mind-wandering literature also suggests that valence predicts whether off-task thoughts will disrupt performance.  
It is also worth noting that in the current studies, it remains unclear whether our stereotype type threat manipulation influences participants’ thought content by specifically increasing worry-laden thoughts or by increasing task diligence in those under threat.   


Overall, the current studies provide a test with replication of the “control failures x current concerns” framework of mind-wandering.
In addition to demonstrating that priming personal, performance-related concerns in younger adults leads to increased TRI, the current studies can provide insight into why older adults consistently report less overall mind-wandering but more TRI than younger adults.


## Quality of the study - Reporting 

### Is the context of the study adequately described?
*Consider your answer to questions: Why was this study done at this point in time, in those contexts and with those people or institutions? (Section B question 2) Was the study informed by or linked to an existing body of empirical and/or theoretical research? (Section B question 3) Which of the following groups were consulted in working out the aims to be addressed in the study? (Section B question 4) Do the authors report how the study was funded? (Section B question 5) When was the study carried out? (Section B question 6)*

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yes

### Are the aims of the study clearly reported?
*Consider your answer to questions: What are the broad aims of the study? (Section B question 1) What are the study research questions and/or hypotheses? (Section C question 10)*

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yes

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?
*Consider your answer to all questions in Methods on ‘Sampling Strategy’, ‘Recruitment and Consent’, and ‘Actual Sample’.*

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yes

### Is there an adequate description of the methods used in the study to collect data?
*Consider your answer to the following questions in Section I: Which methods were used to collect the data? Details of data collection methods or tools Who collected the data? Do the authors describe the setting where the data were collected? Are there other important features of the data collection procedures?*

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yes

### Is there an adequate description of the methods of data analysis?
*Consider your answer to the following questions in Section J: Which methods were used to analyse the data? What statistical methods, if any, were used in the analysis? Who carried out the data analysis?*

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yea

### Is the study replicable from this report?

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yes

### Do the authors avoid selective reporting bias?
*(e.g. do they report on all variables they aimed to study as specified in their aims/research questions?)*

- [ ] Yes (please specify)
- [ ] No (please specify)

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?
*Consider consent, funding, privacy, etc.*

- [ ] Yes, some concerns (please specify)
- [ ] No concerns

- neither consent nor funding was mentioned anywhere in their paper


### Were students and/or parents appropriately involved in the design or conduct of the study?

- [ ] Yes, a lot (please specify)
- [ ] Yes, a little (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yes

### Is there sufficient justification for why the study was done the way it was?

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- yes

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [ ] Yes (please specify)
- [ ] No (please specify)

**Experiment 1**:
- maybe, self-report questionnaires for mind wandering might not be the best choice but a good enough one considering cost and time etc 


### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?
*e.g. (1) In an evaluation, was the process by which participants were allocated to or otherwise received the factor being evaluated concealed and not predictable in advance? If not, were sufficient substitute procedures employed with adequate rigour to rule out any alternative explanations of the findings which arise as a result? e.g. (2) Was the attrition rate low and if applicable similar between different groups?*

- [ ] A lot (please specify)
- [ ] A little (please specify)
- [ ] Not at all (please specify)

### How generalisable are the study results?

- [ ] Details

**Experiment 1**:
- only towards female under math stereotype threat   

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?
*In some studies it is difficult to distinguish between the findings of the study and the conclusions. In those cases please code the trustworthiness of this combined results/conclusion.** Please remember to complete the weight of evidence questions B-D which are in your review specific data extraction guidelines. ***

- [ ] High trustworthiness (please specify)
- [ ] Medium trustworthiness (please specify)
- [ ] Low trustworthiness (please specify)

**Experiment 1**:
- medium

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [ ] Not applicable (results and conclusions inseparable)
- [ ] High trustworthiness
- [ ] Medium trustworthiness
- [ ] Low trustworthiness

**Experiment 1**:
- not applicable
    

# @wellsNewcastleottawaScaleNOS2014

## **CASE CONTROL STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Exposure categories. A maximum of two stars can be given for Comparability.

## Selection

### Is the case definition adequate?
   - a) yes, with independent validation 
   - b) yes, e.g., record linkage or based on self reports
   - c) no description

### Representativeness of the cases
   - a) consecutive or obviously representative series of cases *
   - b) potential for selection biases or not stated

### Selection of Controls
   - a) community controls *
   - b) hospital controls
   - c) no description

### Definition of Controls
   - a) no history of disease (endpoint) *
   - b) no description of source

## Comparability

### Comparability of cases and controls on the basis of the design or analysis
   - a) study controls for _______________ (Select the most important factor.) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Exposure

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview where blind to case/control status *
   - c) interview not blinded to case/control status
   - d) written self report or medical record only
   - e) no description

### Same method of ascertainment for cases and controls
   - a) yes *
   - b) no

### Non-Response rate
   - a) same rate for both groups *
   - b) non respondents described
   - c) rate different and no designation

---

## **COHORT STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Outcome categories. A maximum of two stars can be given for Comparability.

## Selection

### Representativeness of the exposed cohort
   - a) truly representative of the average _______________ (describe) in the community *
   - b) somewhat representative of the average ______________ in the community *
   - c) selected group of users, e.g., nurses, volunteers
   - d) no description of the derivation of the cohort

### Selection of the non exposed cohort
   - a) drawn from the same community as the exposed cohort *
   - b) drawn from a different source
   - c) no description of the derivation of the non exposed cohort

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview *
   - c) written self report
   - d) no description

### Demonstration that outcome of interest was not present at start of study
   - a) yes *
   - b) no

## Comparability

### Comparability of cohorts on the basis of the design or analysis
   - a) study controls for _____________ (select the most important factor) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Outcome

### Assessment of outcome
   - a) independent blind assessment *
   - b) record linkage *
   - c) self report
   - d) no description

### Was follow-up long enough for outcomes to occur
   - a) yes (select an adequate follow up period for outcome of interest) *
   - b) no

### Adequacy of follow up of cohorts
   - a) complete follow up - all subjects accounted for *
   - b) subjects lost to follow up unlikely to introduce bias - small number lost - > ____ % (select an adequate %) follow up, or description provided of those lost) *
   - c) follow up rate < ____% (select an adequate %) and no description of those lost
   - d) no statement


# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

### Did the review address a clearly focussed issue?
- Was there enough information on:
  - The population studied
  - The intervention given
  - The outcomes considered
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the authors look for the appropriate sort of papers?
- The ‘best sort of studies’ would:
  - Address the review’s question
  - Have an appropriate study design
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## ARE THE RESULTS OF THIS REVIEW VALID?

### Do you think the important, relevant studies were included?
- Look for:
  - Which bibliographic databases were used
  - Follow up from reference lists
  - Personal contact with experts
  - Search for unpublished as well as published studies
  - Search for non-English language studies
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the review’s authors do enough to assess the quality of the included studies?
- The authors need to consider the rigour of the studies they have identified. Lack of rigour may affect the studies results.
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### If the results of the review have been combined, was it reasonable to do so?
- Consider whether:
  - The results were similar from study to study
  - The results of all the included studies are clearly displayed
  - The results of the different studies are similar
  - The reasons for any variations are discussed
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WHAT ARE THE RESULTS?

### What is the overall result of the review?
- Consider:
  - If you are clear about the review’s ‘bottom line’ results
  - What these are (numerically if appropriate)
  - How were the results expressed (NNT, odds ratio, etc)

### How precise are the results?
- Are the results presented with confidence intervals?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WILL THE RESULTS HELP LOCALLY?

### Can the results be applied to the local population?
- Consider whether:
  - The patients covered by the review could be sufficiently different from your population to cause concern
  - Your local setting is likely to differ much from that of the review
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Were all important outcomes considered?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Are the benefits worth the harms and costs?
- Even if this is not addressed by the review, what do you think?
- [ ] Yes
- [ ] Can’t tell
- [ ] No


# References


::: {#refs custom-style="Bibliography"}
:::
