---
title             : "@stahlRolePreventionFocus2012a"
shorttitle        : "@stahlRolePreventionFocus2012a"


keywords          : "keywords"
wordcount         : "X"

bibliography      : ["../files/Describing_studies.bib", "h2.bib"]

floatsintext      : no
linenumbers       : no 
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

header-includes:
  - |
    \makeatletter
    \renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-1em}%
      {\normalfont\normalsize\bfseries\typesectitle}}
    
    \renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
      {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
      {-\z@\relax}%
      {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
    \makeatother

csl               : "`r system.file('rmd', 'apa7.csl', package = 'papaja')`"
documentclass     : "apa7"
classoption       : "doc, a4paper"
output            : papaja::apa6_pdf

---

```{r setup, include = FALSE}
library("papaja")
library(RefManageR)
library(kableExtra)
r_refs("r-references.bib")
```

# @eppi-centreReviewGuidelinesExtracting2003 & @criticalappraisalskillsprogrammeCASPSystematicReview2018

### If the study has a broad focus and this data extraction focuses on just one component of the study, please specify this here
 
- [x] Not applicable (whole study is focus of data extraction)  
- [ ] Specific focus of this data extraction (please specify)  

## Study aim(s) and rationale

### Was the study informed by, or linked to, an existing body of empirical and/or theoretical research?
*Please write in authors' declaration if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Stereotype threat
- Stereotype threat effect on cognitive performance
- Prevention focus
- regulatory focus theory  

### Do authors report how the study was funded?

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- The research reported in this article was funded by a VIDI-grant from the Dutch National Science Foundation (NWO) awarded to Colette Van Laar. We are very grateful to Nils Jostmann for providing us with the Stroop task and to Joost Leunissen, Vincent van Dam, and Caroline Heymans for assistance in data collection.  

## Study research question(s) and its policy or practice focus

### What is/are the topic focus/foci of the study?

- We propose that individuals generally respond to stereotype threat by adopting a prevention focus, which in turn leads to immediate recruitment of additional cognitive control resources in an attempt to avoid failure. 
- We are that this response is adaptive to tackle instant threats but that the additional cognitive demands associated with working under threat eventually should deplete the individual's limited cognitive resources.
- Therefore we expect that stereotype threat should lead to initial benefits for cognitive control and performance on demanding cognitive tasks. Over time, however, stereotype threat should lead to cognitive control impairments.
- Finally, because both of these consequences of stereotype threat are attributable to the operation of the prevention focus, stereotype threat should have little effect on cognitive control and performance under a promotion focus. 

### What is/are the population focus/foci of the study?

- individuals under stereotype threat  

### What is the relevant age group? 

- [ ] Not applicate (focus not learners)  
- [ ] 0 - 4  
- [ ] 5 - 10  
- [ ] 11 - 16  
- [ ] 17 - 20  
- [ ] 21 and over  
- [x] Not stated/unclear  

### What is the sex of the population focus/foci?

- [ ] Not applicate (focus not learners)  
- [ ] Female only  
- [ ] Male only  
- [ ] Mixed sex  
- [x] Not stated/unclear  

### What is/are the educational setting(s) of the study?

- [ ] Community centre  
- [ ] Correctional institution  
- [ ] Government department  
- [ ] Higher education institution  
- [ ] Home  
- [ ] Independent school  
- [ ] Local education authority  
- [ ] Nursery school  
- [ ] Other early years setting  
- [ ] Post-compulsory education institution  
- [ ] Primary school  
- [ ] Residential school  
- [ ] Secondary school  
- [ ] Special needs school  
- [ ] Workplace  
- [ ] Other educational setting  

### In Which country or cuntries was the study carried out?

- [x] Explicitly stated (please specify)  
- [ ] Not stated/unclear (please specify)  

- Netherlands

### Please describe in more detail the specific phenomena, factors, services, or interventions with which the study is concerned

### What are the study reserach questions and/or hypotheses?
*Research questions or hypotheses operationalise the aims of the study. Please write in authors' description if there is one. Elaborate if necessary, but indicate which aspects are reviewers' interpretation.*

- [ ] Explicitly stated (please specify)  
- [x] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

- Stereotype threat will facilitate immediate cognitive control compared to a control condition, due to adoption of a prevention focus.
- This effect will occur under a prevention focus but not under a promotion focus.
 -Under a prevention focus, stereotype threat will:
   - Improve maths performance in the short-term due to recruitment of cognitive resources
   - Impair math performance over time due to depletion of cognitive resources
- Under a promotion focus, stereotype threat will not affect math performance.

## Methods - Design

### Which variables or concepts, if any, does the study aim to measure or examine?

- [x] Explicitly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)  

**Experiment 1**:
- Stereotype threat
- cognitive control
- test performance


**Experiment 2**:
- stereotype threat
- regulatory focus
- test performance
- cognitive control
- stereotype threat manipulation check


**Experiment 3**:
- stereotype threat 
- regulatory focus
- task order
- cognitive control
- test performance




### Study timing
*Please indicate all that apply and give further details where possible.*

*If the study examines one or more samples, but each at only one point in time it is cross-sectional.*  
*If the study examines the same samples, but as they have changed over time, it is retrospective, provided that the interest is in starting at one timepoint and looking backwards over time.*  
*If the study examines the same samples as they have changed over time and if data are collected forward over time, it is prospective provided that the interest is in starting at one timepoint and looking forward in time.*  

- [x] Cross-sectional  
- [ ] Retrospective  
- [ ] Prospective  
- [ ] Not stated/unclear (please specify)  

### If the study is an evaluation, when were measurements of the variable(s) used for outcome made, in relation to the intervention?
*If at least one of the outcome variables is measured both before and after the intervention, please use the before and after category.*

- [ ] Not applicable (not an evaluation)  
- [ ] Before and after  
- [x] Only after  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  



## Methods - Groups

### If comparisons are being made between two or more groups, please specify the basis of any divisions made for making these comparisons.
*Please give further details where possible.*

- [ ] Not applicable (not more than one group)  
- [ ] Prospecitive allocation into more than one group (e.g. allocation to different interventions, or allocation to intervention and control groups)  
- [ ] No prospective allocation but use of pre-existing differences to create comparison groups (e.g. receiving different interventions, or characterised by different levels of a variable such as social class)  
- [ ] Other (please specify)  
- [ ] Not stated/unclear (please specify)  

**Experiment 1**:
- prospective

**Experiment 2**:
- prospective



### How do the groups differ?

- [ ] Not applicable (not more than one group)  
- [x] Explicityly stated (please specify)  
- [ ] Implicit (please specify)  
- [ ] Not stated/unclear (please specify)

**Experiment 1**:
- stereotype threat vs no threat  

**Experiment 2**:
- stereotype threat vs no threat
- regulatory focus: prevention focus vs. promotion focus vs. no focus

**Experiment 3**:
- stereotype threat vs no threat
- regulatory focus: promotion vs. prevention
- task order: math task first vs. math task last


### Number of groups
*For instance, in studies in which comparisons are made between groups, this may be the number of groups into which the dataset is divided for analysis (e.g. social class, or form size), or the number of groups allocated to, or receiving, an intervention.*

- [ ] Not applicable (not more than one group)  
- [ ] One  
- [x] Two  
- [ ] Three  
- [ ] Four or more (please specify)  
- [ ] Other/unclear (please specify) 

**Experiment 1**:
- two

**Experiment 2**:
- six (2 x 3)

**Experiment 3**:
- eight (2 x 2 x 2)


### Was the assignment of participants to interventions randomised?

- [ ] Not applicable (not more than one group)  
- [ ] Not applicate (no prospective allocation)  
- [x] Random  
- [ ] Quasi-random  
- [ ] Non-random  
- [ ] Not stated/unclear (please specify)  


- random


### Where there was prospective allocation to more than one group, was the allocation sequence concealed from participants and those enrolling them until after enrolment?
*Bias can be introduced, consciously or otherwise, if the allocation of pupils or classes or schools to a programme or intervention is made in the knowledge of key characteristics of those allocated. For example: children with more serious reading difficulty might be seen as in greater need and might be more likely to be allocated to the 'new' programme, or the opposite might happen. Either would introduce bias.*

- [ ] Not applicable (not more than one group)  
- [ ] Not applicable (no prospective allocation)  
- [x] Yes (please specify)  
- [ ] No (please specify)  
- [ ] Not stated/unclear (please specify)  


### Apart from the experimental intervention, did each study group receive the same level of care (that is, were they treated equally)?

- [x] Yes
- [ ] No
- [ ] Can’t tell

### Study design summary 
*In addition to answering the questions in this section, describe the study design in your own words. You may want to draw upon and elaborate the answers you have already given.*

## Methods - Sampling strategy

### Are the authors trying to produce findings that are representative of a given population? 
*Please write in authors' description. If authors do not specify please indicate reviewers' interpretation.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)


- individuals under stereotype threat 

### Which methods does the study use to identify people or groups of people to sample from and what is the sampling frame?
*e.g. telephone directory, electoral register, postcode, school listing, etc. There may be two stages – e.g. first sampling schools and then classes or pupils within them.*

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

- University students  


### Which methods does the study use to select people or groups of people (from the sampling frame)?
*e.g. selecting people at random, systematically - selecting for example every 5th person, purposively in order to reach a quota for a given characteristic.*

- [ ] Not applicable (no sampling frame)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

### Planned sample size
*If more than one group please give details for each group separately.*

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [ ] Not stated/unclear (please specify)

## Methods - Recruitment and consent

### Which methods are used to recruit people into the study?
*e.g. letters of invitation, telephone contact, face-to-face contact.*

- [ ] Not applicable (please specify)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

### Were any incentives provided to recruit people into the study?

- [ ] Not applicable (please specify)
- [x] Explicitly stated (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1** + **Experiment 2**:
- €2 (about $3 U.S.) or course credit for their time in the laboratory 

**Experiment 3**:
- no incentives mentioned  

### Was consent sought?
*Please comment on the quality of consent if relevant.*

- [ ] Not applicable (please specify)
- [ ] Participant consent sought
- [ ] Parental consent sought
- [ ] Other consent sought
- [ ] Consent not sought
- [x] Not stated/unclear (please specify)

### Are there any other details relevant to recruitment and consent?

- [ ] No
- [ ] Yes (please specify)

## Methods - Actual sample

### What was the total number of participants in the study (the actual sample)?
*If more than one group is being compared please give numbers for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1**:
- Sixty-three (N = 63) social science students at Leiden University, the Netherlands (50 women, 13 men, $M_{age}$ = 22 years) were randomly assigned to a stereotype threat condition or to a control condition. The study lasted approximately 20 min, and participants received €2 (about $3 U.S.) or course credits for their time in the laboratory.  

**Experiment 2**:
- One hundred eight (N = 108) social science students at Leiden University (82 women, 26 men, $M_{age}$ = 19 years) were randomly assigned to conditions in a 2 (stereotype threat: threat/control) x 3 (regulatory focus: prevention focus/promotion focus/no focus) factorial design. The study lasted approximately 20 min, and participants received €2 (about $3 U.S.) or course credits for their time in the laboratory.

**Experiment 3**:
- One hundred sixty-four (N = 164) female students ($M_{age}$ = 19) at Leiden Univeristy were randomly assigned to conditions in a 2 (stereotype threat) x 2 (regulatory focus) x 2 (task order) factorial design.  


### What is the proportion of those selected for the study who actually participated in the study? 
*Please specify numbers and percentages if possible.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

### Which country/countries are the individuals in the actual sample from?
*If UK, please distinguish between England, Scotland, N. Ireland, and Wales if possible. If from different countries, please give numbers for each. If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)


- not stated


### What ages are covered by the actual sample?
*Please give the numbers of the sample that fall within each of the given categories. If necessary, refer to a page number in the report (e.g. for a useful table). If more than one group is being compared, please describe for each group. If follow-up study, age at entry to the study.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] 0 to 4
- [ ] 5 to 10
- [ ] 11 to 16
- [x] 17 to 20
- [x] 21 and over
- [ ] Not stated/unclear (please specify)

**Experiment 1**:
- mean age = 22 years, no SD reported  

**Experiment 2**:
- mean age = 19 years, no SD reported

**Experiment 3**:
- mean age = 19 years, no SD reported



### What is the socio-economic status of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is the ethnicity of the individuals within the actual sample?
*If more than one group is being compared, please describe for each group.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### What is known about the special educational needs of individuals within the actual sample?
*e.g. specific learning, physical, emotional, behavioural, intellectual difficulties.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### Is there any other useful information about the study participants?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Explicitly stated (please specify no/s.)
- [ ] Implicit (please specify)
- [x] Not stated/unclear (please specify)

### How representative was the achieved sample (as recruited at the start of the study) in relation to the aims of the sampling frame? 
*Please specify basis for your decision.*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [ ] Not applicable (no sampling frame)
- [ ] High (please specify)
- [ ] Medium (please specify)
- [x] Low (please specify)
- [ ] Unclear (please specify)

**Experiment 1** + **Experiment 2**:
- low: almost no information given about the sample. Especially for stereotype related studies, culture for example, could play a vital role. Also very uneven gender distribution 

**Experiment 3**:
- medium: same issues as in Experiment 1 and 2 but this time just one gender.  



### If the study involves studying samples prospectively over time, what proportion of the sample dropped out over the course of the study?
*If the study involves more than one group, please give drop-out rates for each group separately. If necessary, refer to a page number in the report (e.g. for a useful table).*

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear

### For studies that involve following samples prospectively over time, do the authors provide any information on whether and/or how those who dropped out of the study differ from those who remained in the study?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Not applicable (no drop outs)
- [ ] Yes (please specify)
- [ ] No

### If the study involves following samples prospectively over time, do authors provide baseline values of key variables such as those being used as outcomes and relevant socio-demographic variables?

- [ ] Not applicable (e.g. study of policies, documents, etc)
- [x] Not applicable (not following samples prospectively over time)
- [ ] Yes (please specify)
- [ ] No

## Methods - Data collection

### Please describe the main types of data collected and specify if they were used (a) to define the sample; (b) to measure aspects of the sample as findings of the study?

- [ ] Details

**Experiment 1**:
- demographic information (gender, age, study major) -> 
- stereotype threat manipulation -> b
- cognitive control capacity measurement using a simplified Stroop color-naming task -> b
- response times
- error rates/accuracy

**Experiment 2**:
- same as Experiment 1
- regulatory focus manipulation -> b
- manipulation check for stereotype threat -> b

**Experiment 3**:
- same as Experiment 1
- typing task -> b
- modular arithmetic problems -> b
- maze task for regulatory focus manipulation -> b


### Which methods were used to collect the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Curriculum-based assessment
- [ ] Focus group
- [ ] Group interview
- [ ] One to one interview (face to face or by phone)
- [ ] Observation
- [ ] Self-completion questionnaire
- [ ] Self-completion report or diary
- [ ] Exams
- [ ] Clinical test
- [ ] Practical test
- [x] Psychological test
- [ ] Hypothetical scenario including vignettes
- [ ] School/college records (e.g. attendance records etc)
- [ ] Secondary data such as publicly available statistics
- [ ] Other documentation
- [ ] Not stated/unclear (please specify)

### Details of data collection methods or tool(s).
*Please provide details including names for all tools used to collect data and examples of any questions/items given. Also please state whether source is cited in the report.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

**Experiment 1**:
- demographical data (age, gender, study major)
- simplified Stroop task (Nils Jostmann provided the Stroop task)

**Experiment 2**:
- same as Experiment 1
- regulatory focus manipulation
- 7 point likert scale for stereotype threat manipulation check  

**Experiment 3**:
- same as Experiment 1
- typing task (one word at a time)
- maze task (Friedman & Förster, 2001)
- modular arithmetic task (e.g. Beilock & Carr, 2005)


### Who collected the data?
*Please indicate all that apply and give further detail where possible.*

- [ ] Researcher
- [ ] Head teacher/Senior management
- [ ] Teaching or other staff
- [ ] Parents
- [ ] Pupils/students
- [ ] Governors
- [ ] LEA/Government officials
- [ ] Other education practitioner
- [ ] Other (please specify)
- [ ] Not stated/unclear

### Do the authors describe any ways they addressed the reliability of their data collection tools/methods?
*e.g. test-retest methods (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of their data collection tools/methods?
*e.g. mention previous validation of tools, published version of tools, involvement of target population in development of tools. (Where more than one tool was employed please provide details for each.)*

- [ ] Details

### Was there concealment of study allocation or other key factors from those carrying out measurement of outcome – if relevant?
*Not applicable – e.g. analysis of existing data, qualitative study. No – e.g. assessment of reading progress for dyslexic pupils done by teacher who provided intervention. Yes – e.g. researcher assessing pupil knowledge of drugs - unaware of pupil allocation.*

- [ ] Not applicable (please say why)
- [ ] Yes (please specify)
- [ ] No (please specify)

### Where were the data collected?
*e.g. school, home.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Unclear/not stated (please specify)

- University laboratory  


### Are there other important features of data collection?
*e.g. use of video or audio tape; ethical issues such as confidentiality etc.*

- [ ] Details

## Methods - Data analysis

### Which methods were used to analyse the data?
*Please give details e.g. for in-depth interviews, how were the data handled? Details of statistical analysis can be given next.*

- [x] Explicitly stated (please specify)
- [ ] Implicit (please specify)
- [ ] Not stated/unclear (please specify)

### Which statistical methods, if any, were used in the analysis?

- [ ] Details

**Experiment 1**:
- log-transformed response times
- ANOVAs
- interference scores

**Experiment 2**:
- 2 (stereotype threat) x 3 (regulatory focus) ANOVA 
- interference scores
- 2 (stereotype threat) x 3 (regulatory focus) ANOVA on Stroop interference scores 
- contrasted stereotype threat condition in which a prevention focus had been included and the stereotype threat condition in which no regulatory focus had been included against the other four conditions.

**Experiment 3**:
- Math performance (percentage of correct responses): 2 (stereotype threat) x 2 (regulatory focus) x 2 (task order) ANOVA on the percentage of correctly solved math equations
- Math performance (response times): 2 (stereotype threat) x 2 (regulatory focus) x 2 (task order) ANOVA on the average response time 
- Typing performance: 2 (stereotype threat) x 2 (regulatory focus) x 2 (task order) ANOCOVA on typing speed as well as on typing accuracy. 




### What rationale do the authors give for the methods of analysis for the study?
*e.g. for their methods of sampling, data collection, or analysis.*

- [ ] Details

### For evaluation studies that use prospective allocation, please specify the basis on which data analysis was carried out.
*'Intention to intervene' means that data were analysed on the basis of the original number of participants as recruited into the different groups. 'Intervention received' means data were analysed on the basis of the number of participants actually receiving the intervention.*

- [ ] Not applicable (not an evaluation study with prospective allocation)
- [ ] 'Intention to intervene'
- [ ] 'Intervention received'
- [ ] Not stated/unclear (please specify)

### Do the authors describe any ways they have addressed the reliability of data analysis?
*e.g. using more than one researcher to analyse data, looking for negative cases.*

- [ ] Details

### Do the authors describe any ways they have addressed the validity of data analysis?
*e.g. internal or external consistency; checking results with participants.*

- [ ] Details

### Do the authors describe strategies used in the analysis to control for bias from confounding variables?

- [ ] Details

### Please describe any other important features of the analysis.

- [ ] Details

### Please comment on any other analytic or statistical issues if relevant.

- [ ] Details

## Results and Conclusions

### How are the results of the study presented?
*e.g. as quotations/figures within text, in tables, appendices.*

- [ ] Details

**Experiment 1** + **Experiment 2**:
- figure
- in text

**Experiment 3**:
- table 
- in text
- figure


### What are the results of the study as reported by authors?
*Please give details and refer to page numbers in the report(s) of the study where necessary (e.g. for key tables).*

- [ ] Details

**Experiment 1**:
- Repeated measures ANOVAs showed that responses were slower on incongruent trails than on neutral trails, as well as than on congruent trails.
- No difference was found between congruent and neutral trails
- Incongruent trails caused interference as compared with congruent and neutral trails.
- Lower scores on this measure (inference scores) indicate higher cognitive control capacity.
- Stereotype threat hd a significant effect on Stroop interference.
- Stroop interference was lower in the stereotype threat condition
- Stereotype threat had no effect on interference based on errors.
- The effecdt on Stroop interference based on response times remained unchanged when controlling for interference based on errors.
- Thus, these findings were not due to speed-accuracy trade-off, rather, stereotype threat reduced Stroop interference compared with the cognitive control, indicating that stereotype threat facilitated cognitive control.


**Experiment 2**:
- *Stereotypic concerns*: A 2 (stereotype threat) x 3 (regulatory focus) ANOVA yielded only a main effect of stereotype threat. Participants were more concerned that a negative performance would lead others to infer that it was due to their social science studies in the threat condition than in the control condition. No other effects approached significance 
- *Cognitive control capacity*: A 2 (stereotype threat) x 3 (regulatory focus) ANOVA on Stroop interference scores yielded only the predicted interaction effect. Replicating the results of Study 1, stereotype threat tended to facilitate cognitive control when no regulatory focus had been experimentally induced. Stereotype threat (vs. control) also tended to facilitate cognitive control in the prevention condition. Stereotype threat had no effect on cognitive control in the promotion focus condition. The alternative set of simple main effect analyses confirmed that the effect of regulatory focus was significant in the stereotype threat condition but not in the control condition. Contrast analysis was highly significant, thus, strong support was obtained for our predictions.


**Experiment 3**:
- *Math performance (percentage of correct responses)*: The ANOVA revealed a Regulatory Focus x Task Order interaction, qualified by the predicted three-way interaction. Analyses into the Stereotype threat x Regulatory Focus interaction revealed that the interaction was significant when math task was presented first. In this condition, individuals in the prevention focus condition performed better under stereotype threat than in the control condition. In the promotion focus condition, performance did not differ between the stereotype htreat condition and the control condition. Additional analyses demonstrated that regulatory foucs had an effect on math performance in the stereotype threat condition, but not in the control condition. Thus, we found support for the notion that, in the short run, stereotype threat can facilitate math performance when under a prevention focus.  The Stereotype Threat x Regulatory Focus interaction was significant also when the math task was presented after the filler task. The opposite pattern was found, individuals in the prevention focus condition performed slightly worse under stereotype threat than in the control condition. In the promotion focus condition, performance did not differ between the stereotype threat condition and the control condition. Furthermore, regulatory focus had a significant effect in the stereotype threat condition but not in the control condition.
- *Math performance (response times)*: The ANOVA on the average response time for the 2- math items yielded only a significant three-way interaction. When the math task came first, participants in the prevention focus condition solved the problems faster under threat (vs. control), whereas participants in the promotion focus condition needed more time to solve the problems under threat (vs. control). Stereotype Threat x Regulatory Focus interaction did not reach significance in this task order condition. The opposite pattern of results was obtained when the math task was presented after the typing task. Stereotype Threat x Regulatory Focus interaction only reached marginal significance in this task order condition. Most important for the present purposes, these findings clearly hsow that the effect obtained on the percentage of correct responses was not due to a speed-accuracy trade-off.
- *Typing performance*: Baseline typing speed was significantly associated with typing speed on the test, and baseline typing accuracy was related to typing accuracy on the test. No effects involving any of our experimental manipulations emerged on typing speed or on typing accuracy. The three-way interaction did not approach significance on either of the typing performance measures. Whereas task order determined how stereotype threat and regulatory focus affected performance on the math task that relies on cognitive control, this was not the case for the typing task that does not rely heavily on cognitive control.


### Was the precision of the estimate of the intervention or treatment effect reported?
   - CONSIDER:
     - Were confidence intervals (CIs) reported?
   - [ ] Yes
   - [x] No
   - [ ] Can’t tell
   
### Are there any obvious shortcomings in the reporting of the data?

- [x] Yes (please specify)
- [ ] No

**Experiment 1**:
- very basic reporting of the calculations performed, not really replicable. 

**Experiment 2**:
- no

**Experiment 3**:
- no


### Do the authors report on all variables they aimed to study as specified in their aims/research questions?
*This excludes variables just used to describe the sample.*

- [x] Yes (please specify)
- [ ] No

### Do the authors state where the full original data are stored?

- [ ] Yes (please specify)
- [x] No

### What do the author(s) conclude about the findings of the study?
*Please give details and refer to page numbers in the report of the study where necessary.*

- [ ] Details

**Experiment 1**:  
Stereotype threat facilitated cognitive control during the stereotype-related test compared with a control condition, providing initial support for the resource recruitment hypothesis. However, we have yet to demonstrate that the prevention focus was responsible for the effect obtained. 


**Experiment 2**:
The main goal of Study 2 was to examine whether the prevention focus was responsible for the improvements in cognitive control capacity under stereotype threat that we observed in Study 1. Importantly, the results confirmed that stereotype threat facilitates cognitive control when no focus has been experimentally induced as well as when a prevention focus has been induced, but not when a promotion focus has been induced. The fact that responses to stereotype threat were virtually identical in the condition in which no regulatory focus had been included and in the prevention focus condition corroborates previous findings suggesting that stereotype threat generally induces a prevention focus. Moreover, the present data provided a direct evidence that regulatory focus has a *causal* effect on cognitive control under stereotype threat. Including a prevention (vs. promotion) focus significantly improved cognitive control under stereotype threat. By contrast, including a prevention (vs. promotion) focus had no effect on cognitive control in the control condition. This demonstrates that the prevention focus does not facilitate cognitive control across the board, but only in the presence of a salient threat of failure.


**Experiment 3**:
This study demonstrated that stereotype threat (vs. control) can improve performance on a math test when under a prevention focus - provided that the math test was presented immediately following the stereotype threat manipulation. This is consistent with the argument that individuals respond to stereotype threat by recruiting cognitive control resources when under a prevention focus. When the math test was administered after a stereotype-relevant filler task, individuals under a prevention focus performed *worse* under stereotype threat than in the control condition. This is consistent with the notion that regulating or suppressing stereotype-related thoughts and feelings eventually should lead to cognitive exhaustion. Consistent with results from Study 2, regulatory focus affected (short-term and long-term) performance in the stereotype threat condition, but not in the control condition. Performance was unaffected by the stereotype threat manipulation (irrespective of task order condition) when under a promotion focus.  
These findings cannot be explained by different tactical preferences for fast versus accurate responding. Analyses of response times to the math problems indicate that the effect on processing speed was similar to that on correct responding (albeit weaker). This suggests that the effects obtained on correct responding were attributable to differences in cognitive control capacity rather than to tactical preferences. The manipulations had no effects at all on the stereotype-relevant task that did not rely heavily on cognitive control (the typing task), providing additional support for the resource recruitment hypothesis.


**General Discussion**:
The present research provides new insights into how stereotype threat affects cognitive performance in general, and how these effects are connected to prevention-oriented self-regulation in particular. It seems  plausible that the prevention focus should improve self-regulation under such circumstances. Consistent with this line of reasoning, other studies on regulatory focus suggest that individuals under a prevention focus are particularly motivated to engage in a task when the risk of failure is high and that they are inclined to do as as quickly as possible.  
In the first study, we demonstrated the basic phenomenon that stereotype threat facilitates immediate cognitive control. Study 2 provided direct experimental evidence that the prevention focus is responsible for this effect. Specifically, stereotype threat facilitated immediate cognitive control as a default as well as when a prevention focus had been induced, but not when a promotion focus had been induced. Importantly, this study also demonstrated that a prevention focus is not beneficial for cognitive control across the board. Rather, a prevention focus facilitated cognitive control under stereotype threat, but not in the control condition. Finally, in Study 3, we examined the implications of adopting a prevention (vs. promotion) focus in response to stereotype threat for math performance over time. Consistent with our resource recruitment account, stereotype threat improved performance on a math test administered immediately after the threat manipulation under a prevention focus. As expected, however, the benefits of adopting a prevention focus under stereotype threat proved to be limited. When exposed to stereotype threat for a longer period of time prior to the math task, stereotype threat (vs. control) instead impaired math performance among individuals under a prevention focus. Consistent with findings from Study 2, stereotype threat had no effects on performance under a promotion focus, and regulatory focus only affected performance under threat, and not in the control condition. Taken together, these studies strongly suggest that individuals respond to stereotype threat by adopting a prevention focus, which in turn leads to recruitment of cognitive control resources. Although this response has short-term benefits for cognitive control exertion in threatening performance situations, it unfortunately cannot prevent these threatening situations from impairing cognitive performance over longer periods of time.  
Moving beyond previous work, our findings suggest that stereotype threat does not (only) affect cognitive performance because individuals adopt a careful, noncreative style of cognitive processing that is unsuitable for many cognitive tasks.





## Quality of the study - Reporting 

### Is the context of the study adequately described?
*Consider your answer to questions: Why was this study done at this point in time, in those contexts and with those people or institutions? (Section B question 2) Was the study informed by or linked to an existing body of empirical and/or theoretical research? (Section B question 3) Which of the following groups were consulted in working out the aims to be addressed in the study? (Section B question 4) Do the authors report how the study was funded? (Section B question 5) When was the study carried out? (Section B question 6)*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Are the aims of the study clearly reported?
*Consider your answer to questions: What are the broad aims of the study? (Section B question 1) What are the study research questions and/or hypotheses? (Section C question 10)*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the sample used in the study and how the sample was identified and recruited?
*Consider your answer to all questions in Methods on ‘Sampling Strategy’, ‘Recruitment and Consent’, and ‘Actual Sample’.*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods used in the study to collect data?
*Consider your answer to the following questions in Section I: Which methods were used to collect the data? Details of data collection methods or tools Who collected the data? Do the authors describe the setting where the data were collected? Are there other important features of the data collection procedures?*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is there an adequate description of the methods of data analysis?
*Consider your answer to the following questions in Section J: Which methods were used to analyse the data? What statistical methods, if any, were used in the analysis? Who carried out the data analysis?*

- [ ] Yes (please specify)
- [ ] No (please specify)

### Is the study replicable from this report?

- [ ] Yes (please specify)
- [ ] No (please specify)

### Do the authors avoid selective reporting bias?
*(e.g. do they report on all variables they aimed to study as specified in their aims/research questions?)*

- [ ] Yes (please specify)
- [ ] No (please specify)

## Quality of the study - Methods and data

### Are there ethical concerns about the way the study was done?
*Consider consent, funding, privacy, etc.*

- [ ] Yes, some concerns (please specify)
- [ ] No concerns

### Were students and/or parents appropriately involved in the design or conduct of the study?

- [ ] Yes, a lot (please specify)
- [ ] Yes, a little (please specify)
- [ ] No (please specify)

### Is there sufficient justification for why the study was done the way it was?

- [ ] Yes (please specify)
- [ ] No (please specify)

### Was the choice of research design appropriate for addressing the research question(s) posed?

- [ ] Yes (please specify)
- [ ] No (please specify)

### To what extent are the research design and methods employed able to rule out any other sources of error/bias which would lead to alternative explanations for the findings of the study?
*e.g. (1) In an evaluation, was the process by which participants were allocated to or otherwise received the factor being evaluated concealed and not predictable in advance? If not, were sufficient substitute procedures employed with adequate rigour to rule out any alternative explanations of the findings which arise as a result? e.g. (2) Was the attrition rate low and if applicable similar between different groups?*

- [ ] A lot (please specify)
- [ ] A little (please specify)
- [ ] Not at all (please specify)

### How generalisable are the study results?

- [ ] Details

### Weight of evidence - A: Taking account of all quality assessment issues, can the study findings be trusted in answering the study question(s)?
*In some studies it is difficult to distinguish between the findings of the study and the conclusions. In those cases please code the trustworthiness of this combined results/conclusion.** Please remember to complete the weight of evidence questions B-D which are in your review specific data extraction guidelines. ***

- [ ] High trustworthiness (please specify)
- [ ] Medium trustworthiness (please specify)
- [ ] Low trustworthiness (please specify)

### Have sufficient attempts been made to justify the conclusions drawn from the findings so that the conclusions are trustworthy?

- [ ] Not applicable (results and conclusions inseparable)
- [ ] High trustworthiness
- [ ] Medium trustworthiness
- [ ] Low trustworthiness
    

# @wellsNewcastleottawaScaleNOS2014

## **CASE CONTROL STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Exposure categories. A maximum of two stars can be given for Comparability.

## Selection

### Is the case definition adequate?
   - a) yes, with independent validation 
   - b) yes, e.g., record linkage or based on self reports
   - c) no description

### Representativeness of the cases
   - a) consecutive or obviously representative series of cases *
   - b) potential for selection biases or not stated

### Selection of Controls
   - a) community controls *
   - b) hospital controls
   - c) no description

### Definition of Controls
   - a) no history of disease (endpoint) *
   - b) no description of source

## Comparability

### Comparability of cases and controls on the basis of the design or analysis
   - a) study controls for _______________ (Select the most important factor.) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Exposure

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview where blind to case/control status *
   - c) interview not blinded to case/control status
   - d) written self report or medical record only
   - e) no description

### Same method of ascertainment for cases and controls
   - a) yes *
   - b) no

### Non-Response rate
   - a) same rate for both groups *
   - b) non respondents described
   - c) rate different and no designation

---

## **COHORT STUDIES**

**Note:** A study can be awarded a maximum of one star for each numbered item within the Selection and Outcome categories. A maximum of two stars can be given for Comparability.

## Selection

### Representativeness of the exposed cohort
   - a) truly representative of the average _______________ (describe) in the community *
   - b) somewhat representative of the average ______________ in the community *
   - c) selected group of users, e.g., nurses, volunteers
   - d) no description of the derivation of the cohort

### Selection of the non exposed cohort
   - a) drawn from the same community as the exposed cohort *
   - b) drawn from a different source
   - c) no description of the derivation of the non exposed cohort

### Ascertainment of exposure
   - a) secure record (e.g., surgical records) *
   - b) structured interview *
   - c) written self report
   - d) no description

### Demonstration that outcome of interest was not present at start of study
   - a) yes *
   - b) no

## Comparability

### Comparability of cohorts on the basis of the design or analysis
   - a) study controls for _____________ (select the most important factor) *
   - b) study controls for any additional factor * (This criterion could be modified to indicate specific control for a second important factor.)

## Outcome

### Assessment of outcome
   - a) independent blind assessment *
   - b) record linkage *
   - c) self report
   - d) no description

### Was follow-up long enough for outcomes to occur
   - a) yes (select an adequate follow up period for outcome of interest) *
   - b) no

### Adequacy of follow up of cohorts
   - a) complete follow up - all subjects accounted for *
   - b) subjects lost to follow up unlikely to introduce bias - small number lost - > ____ % (select an adequate %) follow up, or description provided of those lost) *
   - c) follow up rate < ____% (select an adequate %) and no description of those lost
   - d) no statement


# @universityofglasgowCriticalAppraisalChecklistn.d.nodate

## DOES THIS REVIEW ADDRESS A CLEAR QUESTION?

### Did the review address a clearly focussed issue?
- Was there enough information on:
  - The population studied
  - The intervention given
  - The outcomes considered
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the authors look for the appropriate sort of papers?
- The ‘best sort of studies’ would:
  - Address the review’s question
  - Have an appropriate study design
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## ARE THE RESULTS OF THIS REVIEW VALID?

### Do you think the important, relevant studies were included?
- Look for:
  - Which bibliographic databases were used
  - Follow up from reference lists
  - Personal contact with experts
  - Search for unpublished as well as published studies
  - Search for non-English language studies
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Did the review’s authors do enough to assess the quality of the included studies?
- The authors need to consider the rigour of the studies they have identified. Lack of rigour may affect the studies results.
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### If the results of the review have been combined, was it reasonable to do so?
- Consider whether:
  - The results were similar from study to study
  - The results of all the included studies are clearly displayed
  - The results of the different studies are similar
  - The reasons for any variations are discussed
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WHAT ARE THE RESULTS?

### What is the overall result of the review?
- Consider:
  - If you are clear about the review’s ‘bottom line’ results
  - What these are (numerically if appropriate)
  - How were the results expressed (NNT, odds ratio, etc)

### How precise are the results?
- Are the results presented with confidence intervals?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

## WILL THE RESULTS HELP LOCALLY?

### Can the results be applied to the local population?
- Consider whether:
  - The patients covered by the review could be sufficiently different from your population to cause concern
  - Your local setting is likely to differ much from that of the review
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Were all important outcomes considered?
- [ ] Yes
- [ ] Can’t tell
- [ ] No

### Are the benefits worth the harms and costs?
- Even if this is not addressed by the review, what do you think?
- [ ] Yes
- [ ] Can’t tell
- [ ] No


# References


::: {#refs custom-style="Bibliography"}
:::
